'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Namespace Objects.MOP

	Partial Public Class MOP1200
		Inherits XPLiteObject
		Dim fPICKNUMBER As String
		<Key()> _
		<Size(17)> _
		Public Property PICKNUMBER() As String
			Get
				Return fPICKNUMBER
			End Get
			Set(ByVal value As String)
				SetPropertyValue(Of String)("PICKNUMBER", fPICKNUMBER, value)
			End Set
		End Property
		Dim fTRX_TYPE As Short
		Public Property TRX_TYPE() As Short
			Get
				Return fTRX_TYPE
			End Get
			Set(ByVal value As Short)
				SetPropertyValue(Of Short)("TRX_TYPE", fTRX_TYPE, value)
			End Set
		End Property
		Dim fNOTEINDX As Decimal
		Public Property NOTEINDX() As Decimal
			Get
				Return fNOTEINDX
			End Get
			Set(ByVal value As Decimal)
				SetPropertyValue(Of Decimal)("NOTEINDX", fNOTEINDX, value)
			End Set
		End Property
		Dim fLSTPRTDT As DateTime
		Public Property LSTPRTDT() As DateTime
			Get
				Return fLSTPRTDT
			End Get
			Set(ByVal value As DateTime)
				SetPropertyValue(Of DateTime)("LSTPRTDT", fLSTPRTDT, value)
			End Set
		End Property
		Dim fTIMESPRT As Short
		Public Property TIMESPRT() As Short
			Get
				Return fTIMESPRT
			End Get
			Set(ByVal value As Short)
				SetPropertyValue(Of Short)("TIMESPRT", fTIMESPRT, value)
			End Set
		End Property
		Dim fUSERID As String
		<Size(15)> _
		Public Property USERID() As String
			Get
				Return fUSERID
			End Get
			Set(ByVal value As String)
				SetPropertyValue(Of String)("USERID", fUSERID, value)
			End Set
		End Property
		Dim fCHANGEDATE_I As DateTime
		Public Property CHANGEDATE_I() As DateTime
			Get
				Return fCHANGEDATE_I
			End Get
			Set(ByVal value As DateTime)
				SetPropertyValue(Of DateTime)("CHANGEDATE_I", fCHANGEDATE_I, value)
			End Set
		End Property
		Dim fDOCDATE As DateTime
		Public Property DOCDATE() As DateTime
			Get
				Return fDOCDATE
			End Get
			Set(ByVal value As DateTime)
				SetPropertyValue(Of DateTime)("DOCDATE", fDOCDATE, value)
			End Set
		End Property
		Dim fPOSTED As Byte
		Public Property POSTED() As Byte
			Get
				Return fPOSTED
			End Get
			Set(ByVal value As Byte)
				SetPropertyValue(Of Byte)("POSTED", fPOSTED, value)
			End Set
		End Property
		Dim fPOSTEDDT As DateTime
		Public Property POSTEDDT() As DateTime
			Get
				Return fPOSTEDDT
			End Get
			Set(ByVal value As DateTime)
				SetPropertyValue(Of DateTime)("POSTEDDT", fPOSTEDDT, value)
			End Set
		End Property
		Dim fVOIDED As Byte
		Public Property VOIDED() As Byte
			Get
				Return fVOIDED
			End Get
			Set(ByVal value As Byte)
				SetPropertyValue(Of Byte)("VOIDED", fVOIDED, value)
			End Set
		End Property
		Dim fCALLEDBY As Short
		Public Property CALLEDBY() As Short
			Get
				Return fCALLEDBY
			End Get
			Set(ByVal value As Short)
				SetPropertyValue(Of Short)("CALLEDBY", fCALLEDBY, value)
			End Set
		End Property
		Dim fDEX_ROW_ID As Integer
		Public Property DEX_ROW_ID() As Integer
			Get
				Return fDEX_ROW_ID
			End Get
			Set(ByVal value As Integer)
				SetPropertyValue(Of Integer)("DEX_ROW_ID", fDEX_ROW_ID, value)
			End Set
		End Property
	End Class

End Namespace
