'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Xpo.Metadata
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Runtime.CompilerServices
Imports System.Reflection
Namespace Objects.DTA

    <MasterProvider.Module.AllowDataModificationsInMasterProvider>
    <Persistent("DTA10100")>
    Partial Public Class DTACodeAssignmentHeader
        Inherits XPLiteObject
        Dim fDTA_GL_Reference As String
        <Size(25)>
        Public Property DTA_GL_Reference() As String
            Get
                Return fDTA_GL_Reference
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(DTA_GL_Reference), fDTA_GL_Reference, value)
            End Set
        End Property
        Dim fDOCNUMBR As String
        <Size(21)>
        Public Property DOCNUMBR() As String
            Get
                Return fDOCNUMBR
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(DOCNUMBR), fDOCNUMBR, value)
            End Set
        End Property
        Dim fRMDTYPAL As Short
        Public Property RMDTYPAL() As Short
            Get
                Return fRMDTYPAL
            End Get
            Set(ByVal value As Short)
                SetPropertyValue(Of Short)(NameOf(RMDTYPAL), fRMDTYPAL, value)
            End Set
        End Property
        Dim fGROUPAMT As Decimal
        Public Property GROUPAMT() As Decimal
            Get
                Return fGROUPAMT
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)(NameOf(GROUPAMT), fGROUPAMT, value)
            End Set
        End Property
        Dim fJRNENTRY As Integer
        Public Property JRNENTRY() As Integer
            Get
                Return fJRNENTRY
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)(NameOf(JRNENTRY), fJRNENTRY, value)
            End Set
        End Property
        Dim fTRXDATE As DateTime
        Public Property TRXDATE() As DateTime
            Get
                Return fTRXDATE
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)(NameOf(TRXDATE), fTRXDATE, value)
            End Set
        End Property
        Dim fPSTGSTUS As Short
        Public Property PSTGSTUS() As Short
            Get
                Return fPSTGSTUS
            End Get
            Set(ByVal value As Short)
                SetPropertyValue(Of Short)(NameOf(PSTGSTUS), fPSTGSTUS, value)
            End Set
        End Property
        Public Structure CompoundKey1Struct
            <Persistent("DTASERIES")>
            Public Property DTASERIES As Short
            <Size(25)>
            <Persistent("DTAREF")>
            Public Property DTAREF As String
            <Persistent("ACTINDX")>
            Public Property ACTINDX As Integer
            <Persistent("SEQNUMBR")>
            Public Property SEQNUMBR As Integer
            <Size(15)>
            <Persistent("GROUPID")>
            Public Property GROUPID As String
        End Structure
        <Key(), Persistent()>
        Public CompoundKey1 As CompoundKey1Struct
        Public Sub New(ByVal session As Session)
            MyBase.New(session)
        End Sub
    End Class

End Namespace
