'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Namespace Objects.CN

    <Persistent("CN01400")>
    <DefaultProperty("CollectorID")>
    Partial Public Class CNCollector
        Inherits XPLiteObject
        Dim fCollectorID As String
        <Key()>
        <Size(15)>
        Public Property CollectorID() As String
            Get
                Return fCollectorID
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("CollectorID", fCollectorID, value)
            End Set
        End Property
        Dim fCollectorName As String
        <Size(65)>
        Public Property CollectorName() As String
            Get
                Return fCollectorName
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("CollectorName", fCollectorName, value)
            End Set
        End Property
        Dim fPosition_Name As String
        <Size(31)>
        Public Property Position_Name() As String
            Get
                Return fPosition_Name
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Position_Name", fPosition_Name, value)
            End Set
        End Property
        Dim fCN_Email_Address As String
        <Size(61)>
        Public Property CN_Email_Address() As String
            Get
                Return fCN_Email_Address
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("CN_Email_Address", fCN_Email_Address, value)
            End Set
        End Property
        Dim fCN_Collector_Phone1 As String
        <Size(25)>
        Public Property CN_Collector_Phone1() As String
            Get
                Return fCN_Collector_Phone1
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("CN_Collector_Phone1", fCN_Collector_Phone1, value)
            End Set
        End Property
        Dim fCN_Collector_Phone2 As String
        <Size(25)>
        Public Property CN_Collector_Phone2() As String
            Get
                Return fCN_Collector_Phone2
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("CN_Collector_Phone2", fCN_Collector_Phone2, value)
            End Set
        End Property
        Dim fCN_Collector_Fax As String
        <Size(25)>
        Public Property CN_Collector_Fax() As String
            Get
                Return fCN_Collector_Fax
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("CN_Collector_Fax", fCN_Collector_Fax, value)
            End Set
        End Property
        Dim fCN_User_Defined1 As String
        <Size(51)>
        Public Property CN_User_Defined1() As String
            Get
                Return fCN_User_Defined1
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("CN_User_Defined1", fCN_User_Defined1, value)
            End Set
        End Property
        Dim fCN_User_Defined2 As String
        <Size(51)>
        Public Property CN_User_Defined2() As String
            Get
                Return fCN_User_Defined2
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("CN_User_Defined2", fCN_User_Defined2, value)
            End Set
        End Property
        Dim fCollectionsUser As Byte
        Public Property CollectionsUser() As Byte
            Get
                Return fCollectionsUser
            End Get
            Set(ByVal value As Byte)
                SetPropertyValue(Of Byte)("CollectionsUser", fCollectionsUser, value)
            End Set
        End Property
        Dim fUSERID As String
        <Size(15)>
        Public Property USERID() As String
            Get
                Return fUSERID
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("USERID", fUSERID, value)
            End Set
        End Property
        Dim fPASSWORD As String
        <Size(15)>
        Public Property PASSWORD() As String
            Get
                Return fPASSWORD
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("PASSWORD", fPASSWORD, value)
            End Set
        End Property
        Dim feCollectUser As Byte
        Public Property eCollectUser() As Byte
            Get
                Return feCollectUser
            End Get
            Set(ByVal value As Byte)
                SetPropertyValue(Of Byte)("eCollectUser", feCollectUser, value)
            End Set
        End Property
        Dim fOpen_CollectPro_Main As Byte
        Public Property Open_CollectPro_Main() As Byte
            Get
                Return fOpen_CollectPro_Main
            End Get
            Set(ByVal value As Byte)
                SetPropertyValue(Of Byte)("Open_CollectPro_Main", fOpen_CollectPro_Main, value)
            End Set
        End Property
        Dim fOpen_CollectPro_Query As Byte
        Public Property Open_CollectPro_Query() As Byte
            Get
                Return fOpen_CollectPro_Query
            End Get
            Set(ByVal value As Byte)
                SetPropertyValue(Of Byte)("Open_CollectPro_Query", fOpen_CollectPro_Query, value)
            End Set
        End Property
        Dim fOpen_CollectPro_To_Do As Byte
        Public Property Open_CollectPro_To_Do() As Byte
            Get
                Return fOpen_CollectPro_To_Do
            End Get
            Set(ByVal value As Byte)
                SetPropertyValue(Of Byte)("Open_CollectPro_To_Do", fOpen_CollectPro_To_Do, value)
            End Set
        End Property
        Dim fCN_Default_Action_Assign As Short
        Public Property CN_Default_Action_Assign() As Short
            Get
                Return fCN_Default_Action_Assign
            End Get
            Set(ByVal value As Short)
                SetPropertyValue(Of Short)("CN_Default_Action_Assign", fCN_Default_Action_Assign, value)
            End Set
        End Property
        Dim fNOTEINDX As Decimal
        Public Property NOTEINDX() As Decimal
            Get
                Return fNOTEINDX
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)("NOTEINDX", fNOTEINDX, value)
            End Set
        End Property
        Dim fCREATDDT As DateTime
        Public Property CREATDDT() As DateTime
            Get
                Return fCREATDDT
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)("CREATDDT", fCREATDDT, value)
            End Set
        End Property
        Dim fMODIFDT As DateTime
        Public Property MODIFDT() As DateTime
            Get
                Return fMODIFDT
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)("MODIFDT", fMODIFDT, value)
            End Set
        End Property
        Dim fLSTUSRED As String
        <Size(15)>
        Public Property LSTUSRED() As String
            Get
                Return fLSTUSRED
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("LSTUSRED", fLSTUSRED, value)
            End Set
        End Property
        Dim fCN_Signature_ID As String
        <Size(15)>
        Public Property CN_Signature_ID() As String
            Get
                Return fCN_Signature_ID
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("CN_Signature_ID", fCN_Signature_ID, value)
            End Set
        End Property
        Dim fRefresh_Collections_Main As Byte
        Public Property Refresh_Collections_Main() As Byte
            Get
                Return fRefresh_Collections_Main
            End Get
            Set(ByVal value As Byte)
                SetPropertyValue(Of Byte)("Refresh_Collections_Main", fRefresh_Collections_Main, value)
            End Set
        End Property

        Dim fDEX_ROW_ID As Integer
        Public Property DEX_ROW_ID() As Integer
            Get
                Return fDEX_ROW_ID
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)("DEX_ROW_ID", fDEX_ROW_ID, value)
            End Set
        End Property
        Public Sub New(ByVal session As Session)
            MyBase.New(session)
        End Sub
    End Class

End Namespace
