'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Namespace Objects.PM

    ''' <summary>
    ''' GP Table PM00400
    ''' </summary>
    <MasterProvider.Module.AllowDataModificationsInMasterProvider>
    <Persistent("PM00400")>
    Partial Public Class PMControlTable
        Inherits XPLiteObject
        Dim fDCSTATUS As Short
        Public Property DCSTATUS() As Short
            Get
                Return fDCSTATUS
            End Get
            Set(ByVal value As Short)
                SetPropertyValue(Of Short)("DCSTATUS", fDCSTATUS, value)
            End Set
        End Property
        Dim fDOCTYPE As Short
        Public Property DOCTYPE() As Short
            Get
                Return fDOCTYPE
            End Get
            Set(ByVal value As Short)
                SetPropertyValue(Of Short)("DOCTYPE", fDOCTYPE, value)
            End Set
        End Property
        Dim fVENDORID As String
        <Size(15)>
        Public Property VENDORID() As String
            Get
                Return fVENDORID
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("VENDORID", fVENDORID, value)
            End Set
        End Property
        Dim fDOCNUMBR As String
        <Size(21)>
        Public Property DOCNUMBR() As String
            Get
                Return fDOCNUMBR
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("DOCNUMBR", fDOCNUMBR, value)
            End Set
        End Property
        Dim fTRXSORCE As String
        <Size(13)>
        Public Property TRXSORCE() As String
            Get
                Return fTRXSORCE
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("TRXSORCE", fTRXSORCE, value)
            End Set
        End Property
        Dim fCHEKBKID As String
        <Size(15)>
        Public Property CHEKBKID() As String
            Get
                Return fCHEKBKID
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("CHEKBKID", fCHEKBKID, value)
            End Set
        End Property
        Dim fDUEDATE As DateTime
        Public Property DUEDATE() As DateTime
            Get
                Return fDUEDATE
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)("DUEDATE", fDUEDATE, value)
            End Set
        End Property
        Dim fDISCDATE As DateTime
        Public Property DISCDATE() As DateTime
            Get
                Return fDISCDATE
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)("DISCDATE", fDISCDATE, value)
            End Set
        End Property
        Dim fBCHSOURC As String
        <Size(15)>
        Public Property BCHSOURC() As String
            Get
                Return fBCHSOURC
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("BCHSOURC", fBCHSOURC, value)
            End Set
        End Property
        Dim fDOCDATE As DateTime
        Public Property DOCDATE() As DateTime
            Get
                Return fDOCDATE
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)("DOCDATE", fDOCDATE, value)
            End Set
        End Property
        Dim fUSERID As String
        <Size(15)>
        Public Property USERID() As String
            Get
                Return fUSERID
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("USERID", fUSERID, value)
            End Set
        End Property
        Public Structure CompoundKey1Struct
            <Size(21)>
            <Persistent("CNTRLNUM")>
            Public Property CNTRLNUM As String
            <Persistent("CNTRLTYP")>
            Public Property CNTRLTYP As Short
        End Structure
        <Key(), Persistent()>
        Public CompoundKey1 As CompoundKey1Struct
        Public Sub New(ByVal session As Session)
            MyBase.New(session)
        End Sub
    End Class

End Namespace
