'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Namespace Objects.PM
    ''' <summary>
    ''' GP Table PM10300
    ''' </summary>
    <MasterProvider.Module.AllowDataModificationsInMasterProvider>
    <Persistent("PM10300")>
    Partial Public Class PMPayment
        Inherits XPLiteObject
        Dim fCHEKBKID As String
        <Size(15)>
        Public Property CHEKBKID() As String
            Get
                Return fCHEKBKID
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("CHEKBKID", fCHEKBKID, value)
            End Set
        End Property
        Dim fDOCDATE As DateTime
        Public Property DOCDATE() As DateTime
            Get
                Return fDOCDATE
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)("DOCDATE", fDOCDATE, value)
            End Set
        End Property
        Dim fDOCNUMBR As String
        <Size(21)>
        Public Property DOCNUMBR() As String
            Get
                Return fDOCNUMBR
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("DOCNUMBR", fDOCNUMBR, value)
            End Set
        End Property
        Dim fAPPLDAMT As Decimal
        Public Property APPLDAMT() As Decimal
            Get
                Return fAPPLDAMT
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)("APPLDAMT", fAPPLDAMT, value)
            End Set
        End Property
        Dim fCURTRXAM As Decimal
        Public Property CURTRXAM() As Decimal
            Get
                Return fCURTRXAM
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)("CURTRXAM", fCURTRXAM, value)
            End Set
        End Property
        Dim fCHEKTOTL As Decimal
        Public Property CHEKTOTL() As Decimal
            Get
                Return fCHEKTOTL
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)("CHEKTOTL", fCHEKTOTL, value)
            End Set
        End Property
        Dim fVENDORID As String
        <Size(15)>
        Public Property VENDORID() As String
            Get
                Return fVENDORID
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("VENDORID", fVENDORID, value)
            End Set
        End Property
        Dim fVENDNAME As String
        <Size(65)>
        Public Property VENDNAME() As String
            Get
                Return fVENDNAME
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("VENDNAME", fVENDNAME, value)
            End Set
        End Property
        Dim fCOMMENT1 As String
        <Size(31)>
        Public Property COMMENT1() As String
            Get
                Return fCOMMENT1
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("COMMENT1", fCOMMENT1, value)
            End Set
        End Property
        Dim fADDRESS1 As String
        <Size(61)>
        Public Property ADDRESS1() As String
            Get
                Return fADDRESS1
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("ADDRESS1", fADDRESS1, value)
            End Set
        End Property
        Dim fADDRESS2 As String
        <Size(61)>
        Public Property ADDRESS2() As String
            Get
                Return fADDRESS2
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("ADDRESS2", fADDRESS2, value)
            End Set
        End Property
        Dim fADDRESS3 As String
        <Size(61)>
        Public Property ADDRESS3() As String
            Get
                Return fADDRESS3
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("ADDRESS3", fADDRESS3, value)
            End Set
        End Property
        Dim fCITY As String
        <Size(35)>
        Public Property CITY() As String
            Get
                Return fCITY
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("CITY", fCITY, value)
            End Set
        End Property
        Dim fSTATE As String
        <Size(29)>
        Public Property STATE() As String
            Get
                Return fSTATE
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("STATE", fSTATE, value)
            End Set
        End Property
        Dim fZIPCODE As String
        <Size(11)>
        Public Property ZIPCODE() As String
            Get
                Return fZIPCODE
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("ZIPCODE", fZIPCODE, value)
            End Set
        End Property
        Dim fCOUNTRY As String
        <Size(61)>
        Public Property COUNTRY() As String
            Get
                Return fCOUNTRY
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("COUNTRY", fCOUNTRY, value)
            End Set
        End Property
        Dim fVNDCHKNM As String
        <Size(65)>
        Public Property VNDCHKNM() As String
            Get
                Return fVNDCHKNM
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("VNDCHKNM", fVNDCHKNM, value)
            End Set
        End Property
        Dim fSOURCDOC As String
        <Size(11)>
        Public Property SOURCDOC() As String
            Get
                Return fSOURCDOC
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("SOURCDOC", fSOURCDOC, value)
            End Set
        End Property
        Dim fDISTKNAM As Decimal
        Public Property DISTKNAM() As Decimal
            Get
                Return fDISTKNAM
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)("DISTKNAM", fDISTKNAM, value)
            End Set
        End Property
        Dim fDISAMTAV As Decimal
        Public Property DISAMTAV() As Decimal
            Get
                Return fDISAMTAV
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)("DISAMTAV", fDISAMTAV, value)
            End Set
        End Property
        Dim fWROFAMNT As Decimal
        Public Property WROFAMNT() As Decimal
            Get
                Return fWROFAMNT
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)("WROFAMNT", fWROFAMNT, value)
            End Set
        End Property
        Dim fCURNCYID As String
        <Size(15)>
        Public Property CURNCYID() As String
            Get
                Return fCURNCYID
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("CURNCYID", fCURNCYID, value)
            End Set
        End Property
        Dim fVOIDED As Byte
        Public Property VOIDED() As Byte
            Get
                Return fVOIDED
            End Get
            Set(ByVal value As Byte)
                SetPropertyValue(Of Byte)("VOIDED", fVOIDED, value)
            End Set
        End Property
        Dim fREPRNTED As Short
        Public Property REPRNTED() As Short
            Get
                Return fREPRNTED
            End Get
            Set(ByVal value As Short)
                SetPropertyValue(Of Short)("REPRNTED", fREPRNTED, value)
            End Set
        End Property
        Dim fGSTDSAMT As Decimal
        Public Property GSTDSAMT() As Decimal
            Get
                Return fGSTDSAMT
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)("GSTDSAMT", fGSTDSAMT, value)
            End Set
        End Property
        Dim fPGRAMSBJ As Short
        Public Property PGRAMSBJ() As Short
            Get
                Return fPGRAMSBJ
            End Get
            Set(ByVal value As Short)
                SetPropertyValue(Of Short)("PGRAMSBJ", fPGRAMSBJ, value)
            End Set
        End Property
        Dim fPPSTAXRT As Short
        Public Property PPSTAXRT() As Short
            Get
                Return fPPSTAXRT
            End Get
            Set(ByVal value As Short)
                SetPropertyValue(Of Short)("PPSTAXRT", fPPSTAXRT, value)
            End Set
        End Property
        Dim fPPSAMDED As Decimal
        Public Property PPSAMDED() As Decimal
            Get
                Return fPPSAMDED
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)("PPSAMDED", fPPSAMDED, value)
            End Set
        End Property
        Dim fLDOCRMTC As Short
        Public Property LDOCRMTC() As Short
            Get
                Return fLDOCRMTC
            End Get
            Set(ByVal value As Short)
                SetPropertyValue(Of Short)("LDOCRMTC", fLDOCRMTC, value)
            End Set
        End Property
        Dim fSDORMBY As Short
        Public Property SDORMBY() As Short
            Get
                Return fSDORMBY
            End Get
            Set(ByVal value As Short)
                SetPropertyValue(Of Short)("SDORMBY", fSDORMBY, value)
            End Set
        End Property
        Dim fKEYFIELD As String
        <Size(21)>
        Public Property KEYFIELD() As String
            Get
                Return fKEYFIELD
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("KEYFIELD", fKEYFIELD, value)
            End Set
        End Property
        Dim fAMWDSNBR As String
        <Size(61)>
        Public Property AMWDSNBR() As String
            Get
                Return fAMWDSNBR
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("AMWDSNBR", fAMWDSNBR, value)
            End Set
        End Property
        Dim fNOTEINDX As Decimal
        Public Property NOTEINDX() As Decimal
            Get
                Return fNOTEINDX
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)("NOTEINDX", fNOTEINDX, value)
            End Set
        End Property
        Dim fVCHRNMBR As String
        <Size(21)>
        Public Property VCHRNMBR() As String
            Get
                Return fVCHRNMBR
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("VCHRNMBR", fVCHRNMBR, value)
            End Set
        End Property
        Dim fCNTRLTYP As Short
        Public Property CNTRLTYP() As Short
            Get
                Return fCNTRLTYP
            End Get
            Set(ByVal value As Short)
                SetPropertyValue(Of Short)("CNTRLTYP", fCNTRLTYP, value)
            End Set
        End Property
        Dim fDOCTYPE As Short
        Public Property DOCTYPE() As Short
            Get
                Return fDOCTYPE
            End Get
            Set(ByVal value As Short)
                SetPropertyValue(Of Short)("DOCTYPE", fDOCTYPE, value)
            End Set
        End Property
        Dim fMODIFDT As DateTime
        Public Property MODIFDT() As DateTime
            Get
                Return fMODIFDT
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)("MODIFDT", fMODIFDT, value)
            End Set
        End Property
        Dim fMDFUSRID As String
        <Size(15)>
        Public Property MDFUSRID() As String
            Get
                Return fMDFUSRID
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("MDFUSRID", fMDFUSRID, value)
            End Set
        End Property
        Dim fPSTGSTUS As Short
        Public Property PSTGSTUS() As Short
            Get
                Return fPSTGSTUS
            End Get
            Set(ByVal value As Short)
                SetPropertyValue(Of Short)("PSTGSTUS", fPSTGSTUS, value)
            End Set
        End Property
        Dim fPOSTEDDT As DateTime
        Public Property POSTEDDT() As DateTime
            Get
                Return fPOSTEDDT
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)("POSTEDDT", fPOSTEDDT, value)
            End Set
        End Property
        Dim fPTDUSRID As String
        <Size(15)>
        Public Property PTDUSRID() As String
            Get
                Return fPTDUSRID
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("PTDUSRID", fPTDUSRID, value)
            End Set
        End Property
        Dim fCHKCOMNT As String
        <Size(61)>
        Public Property CHKCOMNT() As String
            Get
                Return fCHKCOMNT
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("CHKCOMNT", fCHKCOMNT, value)
            End Set
        End Property
        Dim fPSTGDATE As DateTime
        Public Property PSTGDATE() As DateTime
            Get
                Return fPSTGDATE
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)("PSTGDATE", fPSTGDATE, value)
            End Set
        End Property
        Dim fSTRGA255 As String
        <Size(255)>
        Public Property STRGA255() As String
            Get
                Return fSTRGA255
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("STRGA255", fSTRGA255, value)
            End Set
        End Property
        Dim fSTRGB255 As String
        <Size(255)>
        Public Property STRGB255() As String
            Get
                Return fSTRGB255
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("STRGB255", fSTRGB255, value)
            End Set
        End Property
        Dim fSEPRMTNC As Byte
        Public Property SEPRMTNC() As Byte
            Get
                Return fSEPRMTNC
            End Get
            Set(ByVal value As Byte)
                SetPropertyValue(Of Byte)("SEPRMTNC", fSEPRMTNC, value)
            End Set
        End Property
        Dim fSTBOVRFL As Byte
        Public Property STBOVRFL() As Byte
            Get
                Return fSTBOVRFL
            End Get
            Set(ByVal value As Byte)
                SetPropertyValue(Of Byte)("STBOVRFL", fSTBOVRFL, value)
            End Set
        End Property
        Dim fCTYSTZIP As String
        <Size(47)>
        Public Property CTYSTZIP() As String
            Get
                Return fCTYSTZIP
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("CTYSTZIP", fCTYSTZIP, value)
            End Set
        End Property
        Dim fTotDocAmt As Decimal
        Public Property TotDocAmt() As Decimal
            Get
                Return fTotDocAmt
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)("TotDocAmt", fTotDocAmt, value)
            End Set
        End Property
        Dim fTotAmtPaid As Decimal
        Public Property TotAmtPaid() As Decimal
            Get
                Return fTotAmtPaid
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)("TotAmtPaid", fTotAmtPaid, value)
            End Set
        End Property
        Dim fTotCrdAmt As Decimal
        Public Property TotCrdAmt() As Decimal
            Get
                Return fTotCrdAmt
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)("TotCrdAmt", fTotCrdAmt, value)
            End Set
        End Property
        Dim fTotalPaidTot As Decimal
        Public Property TotalPaidTot() As Decimal
            Get
                Return fTotalPaidTot
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)("TotalPaidTot", fTotalPaidTot, value)
            End Set
        End Property
        Dim fTotNegTot As Decimal
        Public Property TotNegTot() As Decimal
            Get
                Return fTotNegTot
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)("TotNegTot", fTotNegTot, value)
            End Set
        End Property
        Dim fTotCrdDocAmt As Decimal
        Public Property TotCrdDocAmt() As Decimal
            Get
                Return fTotCrdDocAmt
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)("TotCrdDocAmt", fTotCrdDocAmt, value)
            End Set
        End Property
        Dim fTotTotDocAmt As Decimal
        Public Property TotTotDocAmt() As Decimal
            Get
                Return fTotTotDocAmt
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)("TotTotDocAmt", fTotTotDocAmt, value)
            End Set
        End Property
        Dim fTotDiscTknAmt As Decimal
        Public Property TotDiscTknAmt() As Decimal
            Get
                Return fTotDiscTknAmt
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)("TotDiscTknAmt", fTotDiscTknAmt, value)
            End Set
        End Property
        Dim fTotWOAmt As Decimal
        Public Property TotWOAmt() As Decimal
            Get
                Return fTotWOAmt
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)("TotWOAmt", fTotWOAmt, value)
            End Set
        End Property
        Dim fTotPPSAmtDed As Decimal
        Public Property TotPPSAmtDed() As Decimal
            Get
                Return fTotPPSAmtDed
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)("TotPPSAmtDed", fTotPPSAmtDed, value)
            End Set
        End Property
        Dim fTotGSTDiscAmt As Decimal
        Public Property TotGSTDiscAmt() As Decimal
            Get
                Return fTotGSTDiscAmt
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)("TotGSTDiscAmt", fTotGSTDiscAmt, value)
            End Set
        End Property
        Dim fTotDiscTknTot As Decimal
        Public Property TotDiscTknTot() As Decimal
            Get
                Return fTotDiscTknTot
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)("TotDiscTknTot", fTotDiscTknTot, value)
            End Set
        End Property
        Dim fTotWOTot As Decimal
        Public Property TotWOTot() As Decimal
            Get
                Return fTotWOTot
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)("TotWOTot", fTotWOTot, value)
            End Set
        End Property
        Dim fOutstanding_Amount As Decimal
        Public Property Outstanding_Amount() As Decimal
            Get
                Return fOutstanding_Amount
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)("Outstanding_Amount", fOutstanding_Amount, value)
            End Set
        End Property
        Dim fNet_Paid_Amount As Decimal
        Public Property Net_Paid_Amount() As Decimal
            Get
                Return fNet_Paid_Amount
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)("Net_Paid_Amount", fNet_Paid_Amount, value)
            End Set
        End Property
        Dim fElectronic As Byte
        Public Property Electronic() As Byte
            Get
                Return fElectronic
            End Get
            Set(ByVal value As Byte)
                SetPropertyValue(Of Byte)("Electronic", fElectronic, value)
            End Set
        End Property
        Dim fPONUMBER As String
        <Size(17)>
        Public Property PONUMBER() As String
            Get
                Return fPONUMBER
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("PONUMBER", fPONUMBER, value)
            End Set
        End Property
        
        Dim fAMTINWDS As String
        <Size(SizeAttribute.Unlimited)>
        Public Property AMTINWDS() As String
            Get
                Return fAMTINWDS
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("AMTINWDS", fAMTINWDS, value)
            End Set
        End Property
        Public Structure CompoundKey1Struct
            <Size(15)>
            <Persistent("BACHNUMB")>
            Public Property BACHNUMB As String
            <Size(15)>
            <Persistent("BCHSOURC")>
            Public Property BCHSOURC As String
            <Size(21)>
            <Persistent("PMNTNMBR")>
            Public Property PMNTNMBR As String
        End Structure
        <Key(), Persistent()>
        Public CompoundKey1 As CompoundKey1Struct
        Public Sub New(ByVal session As Session)
            MyBase.New(session)
        End Sub
    End Class

End Namespace
