'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Namespace Objects.RM

    ''' <summary>
    ''' GP Table RM30101
    ''' </summary>
    <Persistent("RM30101")>
    Public Class RMReceivableDocumentHistory
        Inherits XPLiteObject
        Dim fCPRCSTNM As String
        <Size(15)> _
        Public Property CPRCSTNM() As String
            Get
                Return fCPRCSTNM
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("CPRCSTNM", fCPRCSTNM, value)
            End Set
        End Property
        Dim fCHEKNMBR As String
        <Size(21)> _
        Public Property CHEKNMBR() As String
            Get
                Return fCHEKNMBR
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("CHEKNMBR", fCHEKNMBR, value)
            End Set
        End Property
        Dim fBACHNUMB As String
        <Size(15)> _
        Public Property BACHNUMB() As String
            Get
                Return fBACHNUMB
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("BACHNUMB", fBACHNUMB, value)
            End Set
        End Property
        Dim fBCHSOURC As String
        <Size(15)> _
        Public Property BCHSOURC() As String
            Get
                Return fBCHSOURC
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("BCHSOURC", fBCHSOURC, value)
            End Set
        End Property
        Dim fTRXSORCE As String
        <Size(13)> _
        Public Property TRXSORCE() As String
            Get
                Return fTRXSORCE
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("TRXSORCE", fTRXSORCE, value)
            End Set
        End Property
        Dim fDUEDATE As DateTime
        Public Property DUEDATE() As DateTime
            Get
                Return fDUEDATE
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)("DUEDATE", fDUEDATE, value)
            End Set
        End Property
        Dim fDOCDATE As DateTime
        Public Property DOCDATE() As DateTime
            Get
                Return fDOCDATE
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)("DOCDATE", fDOCDATE, value)
            End Set
        End Property
        Dim fPOSTDATE As DateTime
        Public Property POSTDATE() As DateTime
            Get
                Return fPOSTDATE
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)("POSTDATE", fPOSTDATE, value)
            End Set
        End Property
        Dim fPSTUSRID As String
        <Size(15)> _
        Public Property PSTUSRID() As String
            Get
                Return fPSTUSRID
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("PSTUSRID", fPSTUSRID, value)
            End Set
        End Property
        Dim fGLPOSTDT As DateTime
        Public Property GLPOSTDT() As DateTime
            Get
                Return fGLPOSTDT
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)("GLPOSTDT", fGLPOSTDT, value)
            End Set
        End Property
        Dim fLSTEDTDT As DateTime
        Public Property LSTEDTDT() As DateTime
            Get
                Return fLSTEDTDT
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)("LSTEDTDT", fLSTEDTDT, value)
            End Set
        End Property
        Dim fLSTUSRED As String
        <Size(15)> _
        Public Property LSTUSRED() As String
            Get
                Return fLSTUSRED
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("LSTUSRED", fLSTUSRED, value)
            End Set
        End Property
        Dim fORTRXAMT As Decimal
        Public Property ORTRXAMT() As Decimal
            Get
                Return fORTRXAMT
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)("ORTRXAMT", fORTRXAMT, value)
            End Set
        End Property
        Dim fCURTRXAM As Decimal
        Public Property CURTRXAM() As Decimal
            Get
                Return fCURTRXAM
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)("CURTRXAM", fCURTRXAM, value)
            End Set
        End Property
        Dim fSLSAMNT As Decimal
        Public Property SLSAMNT() As Decimal
            Get
                Return fSLSAMNT
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)("SLSAMNT", fSLSAMNT, value)
            End Set
        End Property
        Dim fCOSTAMNT As Decimal
        Public Property COSTAMNT() As Decimal
            Get
                Return fCOSTAMNT
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)("COSTAMNT", fCOSTAMNT, value)
            End Set
        End Property
        Dim fFRTAMNT As Decimal
        Public Property FRTAMNT() As Decimal
            Get
                Return fFRTAMNT
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)("FRTAMNT", fFRTAMNT, value)
            End Set
        End Property
        Dim fMISCAMNT As Decimal
        Public Property MISCAMNT() As Decimal
            Get
                Return fMISCAMNT
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)("MISCAMNT", fMISCAMNT, value)
            End Set
        End Property
        Dim fTAXAMNT As Decimal
        Public Property TAXAMNT() As Decimal
            Get
                Return fTAXAMNT
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)("TAXAMNT", fTAXAMNT, value)
            End Set
        End Property
        Dim fCOMDLRAM As Decimal
        Public Property COMDLRAM() As Decimal
            Get
                Return fCOMDLRAM
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)("COMDLRAM", fCOMDLRAM, value)
            End Set
        End Property
        Dim fCASHAMNT As Decimal
        Public Property CASHAMNT() As Decimal
            Get
                Return fCASHAMNT
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)("CASHAMNT", fCASHAMNT, value)
            End Set
        End Property
        Dim fDISTKNAM As Decimal
        Public Property DISTKNAM() As Decimal
            Get
                Return fDISTKNAM
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)("DISTKNAM", fDISTKNAM, value)
            End Set
        End Property
        Dim fDISAVAMT As Decimal
        Public Property DISAVAMT() As Decimal
            Get
                Return fDISAVAMT
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)("DISAVAMT", fDISAVAMT, value)
            End Set
        End Property
        Dim fDISCRTND As Decimal
        Public Property DISCRTND() As Decimal
            Get
                Return fDISCRTND
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)("DISCRTND", fDISCRTND, value)
            End Set
        End Property
        Dim fDISCDATE As DateTime
        Public Property DISCDATE() As DateTime
            Get
                Return fDISCDATE
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)("DISCDATE", fDISCDATE, value)
            End Set
        End Property
        Dim fDSCDLRAM As Decimal
        Public Property DSCDLRAM() As Decimal
            Get
                Return fDSCDLRAM
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)("DSCDLRAM", fDSCDLRAM, value)
            End Set
        End Property
        Dim fDSCPCTAM As Short
        Public Property DSCPCTAM() As Short
            Get
                Return fDSCPCTAM
            End Get
            Set(ByVal value As Short)
                SetPropertyValue(Of Short)("DSCPCTAM", fDSCPCTAM, value)
            End Set
        End Property
        Dim fWROFAMNT As Decimal
        Public Property WROFAMNT() As Decimal
            Get
                Return fWROFAMNT
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)("WROFAMNT", fWROFAMNT, value)
            End Set
        End Property
        Dim fTRXDSCRN As String
        <Size(31)> _
        Public Property TRXDSCRN() As String
            Get
                Return fTRXDSCRN
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("TRXDSCRN", fTRXDSCRN, value)
            End Set
        End Property
        Dim fCSPORNBR As String
        <Size(21)> _
        Public Property CSPORNBR() As String
            Get
                Return fCSPORNBR
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("CSPORNBR", fCSPORNBR, value)
            End Set
        End Property
        Dim fSLPRSNID As String
        <Size(15)> _
        Public Property SLPRSNID() As String
            Get
                Return fSLPRSNID
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("SLPRSNID", fSLPRSNID, value)
            End Set
        End Property
        Dim fSLSTERCD As String
        <Size(15)> _
        Public Property SLSTERCD() As String
            Get
                Return fSLSTERCD
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("SLSTERCD", fSLSTERCD, value)
            End Set
        End Property
        Dim fDINVPDOF As DateTime
        Public Property DINVPDOF() As DateTime
            Get
                Return fDINVPDOF
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)("DINVPDOF", fDINVPDOF, value)
            End Set
        End Property
        Dim fPPSAMDED As Decimal
        Public Property PPSAMDED() As Decimal
            Get
                Return fPPSAMDED
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)("PPSAMDED", fPPSAMDED, value)
            End Set
        End Property
        Dim fGSTDSAMT As Decimal
        Public Property GSTDSAMT() As Decimal
            Get
                Return fGSTDSAMT
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)("GSTDSAMT", fGSTDSAMT, value)
            End Set
        End Property
        Dim fDELETE1 As Byte
        Public Property DELETE1() As Byte
            Get
                Return fDELETE1
            End Get
            Set(ByVal value As Byte)
                SetPropertyValue(Of Byte)("DELETE1", fDELETE1, value)
            End Set
        End Property
        Dim fTAXSCHID As String
        <Size(15)> _
        Public Property TAXSCHID() As String
            Get
                Return fTAXSCHID
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("TAXSCHID", fTAXSCHID, value)
            End Set
        End Property
        Dim fSLSCHDID As String
        <Size(15)> _
        Public Property SLSCHDID() As String
            Get
                Return fSLSCHDID
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("SLSCHDID", fSLSCHDID, value)
            End Set
        End Property
        Dim fFRTSCHID As String
        <Size(15)> _
        Public Property FRTSCHID() As String
            Get
                Return fFRTSCHID
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("FRTSCHID", fFRTSCHID, value)
            End Set
        End Property
        Dim fMSCSCHID As String
        <Size(15)> _
        Public Property MSCSCHID() As String
            Get
                Return fMSCSCHID
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("MSCSCHID", fMSCSCHID, value)
            End Set
        End Property
        Dim fCURNCYID As String
        <Size(15)> _
        Public Property CURNCYID() As String
            Get
                Return fCURNCYID
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("CURNCYID", fCURNCYID, value)
            End Set
        End Property
        Dim fSHIPMTHD As String
        <Size(15)> _
        Public Property SHIPMTHD() As String
            Get
                Return fSHIPMTHD
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("SHIPMTHD", fSHIPMTHD, value)
            End Set
        End Property
        Dim fPYMTRMID As String
        <Size(21)> _
        Public Property PYMTRMID() As String
            Get
                Return fPYMTRMID
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("PYMTRMID", fPYMTRMID, value)
            End Set
        End Property
        Dim fTRDISAMT As Decimal
        Public Property TRDISAMT() As Decimal
            Get
                Return fTRDISAMT
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)("TRDISAMT", fTRDISAMT, value)
            End Set
        End Property
        Dim fNOTEINDX As Decimal
        Public Property NOTEINDX() As Decimal
            Get
                Return fNOTEINDX
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)("NOTEINDX", fNOTEINDX, value)
            End Set
        End Property
        Dim fVOIDSTTS As Short
        Public Property VOIDSTTS() As Short
            Get
                Return fVOIDSTTS
            End Get
            Set(ByVal value As Short)
                SetPropertyValue(Of Short)("VOIDSTTS", fVOIDSTTS, value)
            End Set
        End Property
        Dim fVOIDDATE As DateTime
        Public Property VOIDDATE() As DateTime
            Get
                Return fVOIDDATE
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)("VOIDDATE", fVOIDDATE, value)
            End Set
        End Property
        Dim fBALFWDNM As String
        <Size(21)> _
        Public Property BALFWDNM() As String
            Get
                Return fBALFWDNM
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("BALFWDNM", fBALFWDNM, value)
            End Set
        End Property
        Dim fCSHRCTYP As Short
        Public Property CSHRCTYP() As Short
            Get
                Return fCSHRCTYP
            End Get
            Set(ByVal value As Short)
                SetPropertyValue(Of Short)("CSHRCTYP", fCSHRCTYP, value)
            End Set
        End Property
        Dim fTax_Date As DateTime
        Public Property Tax_Date() As DateTime
            Get
                Return fTax_Date
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)("Tax_Date", fTax_Date, value)
            End Set
        End Property
        Dim fAPLYWITH As Byte
        Public Property APLYWITH() As Byte
            Get
                Return fAPLYWITH
            End Get
            Set(ByVal value As Byte)
                SetPropertyValue(Of Byte)("APLYWITH", fAPLYWITH, value)
            End Set
        End Property
        Dim fSALEDATE As DateTime
        Public Property SALEDATE() As DateTime
            Get
                Return fSALEDATE
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)("SALEDATE", fSALEDATE, value)
            End Set
        End Property
        Dim fCORRCTN As Byte
        Public Property CORRCTN() As Byte
            Get
                Return fCORRCTN
            End Get
            Set(ByVal value As Byte)
                SetPropertyValue(Of Byte)("CORRCTN", fCORRCTN, value)
            End Set
        End Property
        Dim fSIMPLIFD As Byte
        Public Property SIMPLIFD() As Byte
            Get
                Return fSIMPLIFD
            End Get
            Set(ByVal value As Byte)
                SetPropertyValue(Of Byte)("SIMPLIFD", fSIMPLIFD, value)
            End Set
        End Property
        Dim fElectronic As Byte
        Public Property Electronic() As Byte
            Get
                Return fElectronic
            End Get
            Set(ByVal value As Byte)
                SetPropertyValue(Of Byte)("Electronic", fElectronic, value)
            End Set
        End Property
        Dim fECTRX As Byte
        Public Property ECTRX() As Byte
            Get
                Return fECTRX
            End Get
            Set(ByVal value As Byte)
                SetPropertyValue(Of Byte)("ECTRX", fECTRX, value)
            End Set
        End Property
        Dim fBKTSLSAM As Decimal
        Public Property BKTSLSAM() As Decimal
            Get
                Return fBKTSLSAM
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)("BKTSLSAM", fBKTSLSAM, value)
            End Set
        End Property
        Dim fBackoutTradeDisc As Decimal
        Public Property BackoutTradeDisc() As Decimal
            Get
                Return fBackoutTradeDisc
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)("BackoutTradeDisc", fBackoutTradeDisc, value)
            End Set
        End Property
        Dim fBKTFRTAM As Decimal
        Public Property BKTFRTAM() As Decimal
            Get
                Return fBKTFRTAM
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)("BKTFRTAM", fBKTFRTAM, value)
            End Set
        End Property
        Dim fBKTMSCAM As Decimal
        Public Property BKTMSCAM() As Decimal
            Get
                Return fBKTMSCAM
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)("BKTMSCAM", fBKTMSCAM, value)
            End Set
        End Property
        Dim fFactoring As Byte
        Public Property Factoring() As Byte
            Get
                Return fFactoring
            End Get
            Set(ByVal value As Byte)
                SetPropertyValue(Of Byte)("Factoring", fFactoring, value)
            End Set
        End Property
        Dim fDIRECTDEBIT As Byte
        Public Property DIRECTDEBIT() As Byte
            Get
                Return fDIRECTDEBIT
            End Get
            Set(ByVal value As Byte)
                SetPropertyValue(Of Byte)("DIRECTDEBIT", fDIRECTDEBIT, value)
            End Set
        End Property
        Dim fADRSCODE As String
        <Size(15)> _
        Public Property ADRSCODE() As String
            Get
                Return fADRSCODE
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("ADRSCODE", fADRSCODE, value)
            End Set
        End Property
        Dim fEFTFLAG As Byte
        Public Property EFTFLAG() As Byte
            Get
                Return fEFTFLAG
            End Get
            Set(ByVal value As Byte)
                SetPropertyValue(Of Byte)("EFTFLAG", fEFTFLAG, value)
            End Set
        End Property
        Dim fDEX_ROW_ID As Integer
        Public Property DEX_ROW_ID() As Integer
            Get
                Return fDEX_ROW_ID
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)("DEX_ROW_ID", fDEX_ROW_ID, value)
            End Set
        End Property
        Public Structure CompoundKey1Struct
            <Size(15)> _
            <Persistent("CUSTNMBR")> _
            Public Property CUSTNMBR As String
            <Size(21)> _
            <Persistent("DOCNUMBR")> _
            Public Property DOCNUMBR As String
            <Persistent("RMDTYPAL")> _
            Public Property RMDTYPAL As Short
        End Structure
        <Key(), Persistent()> _
        Public CompoundKey1 As CompoundKey1Struct
        Public Sub New(ByVal session As Session)
            MyBase.New(session)
        End Sub
    End Class

End Namespace
