'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Namespace Objects.CM

    ''' <summary>
    ''' GP Table CM20300 - All cash receipt transactions with or without deposit
    ''' </summary>
    ''' <remarks></remarks>
    <Persistent("CM20300")>
    Public Class BankDepositCashReceiptTransaction
        Inherits XPLiteObject

        Dim fCMRECNUM As Decimal
        <Key()> _
        Public Property CMRECNUM() As Decimal
            Get

                Return fCMRECNUM
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)("CMRECNUM", fCMRECNUM, value)
            End Set
        End Property
        Dim fsRecNum As String
        <Indexed(Name:="AK5CM20300", Unique:=True)> _
        <Size(21)> _
        Public Property sRecNum() As String
            Get
                Return fsRecNum
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("sRecNum", fsRecNum, value)
            End Set
        End Property
        Dim fCNTRLTYP As Short
        Public Property CNTRLTYP() As Short
            Get
                Return fCNTRLTYP
            End Get
            Set(ByVal value As Short)
                SetPropertyValue(Of Short)("CNTRLTYP", fCNTRLTYP, value)
            End Set
        End Property
        Dim fDEPOSITED As Byte
        Public Property DEPOSITED() As Byte
            Get
                Return fDEPOSITED
            End Get
            Set(ByVal value As Byte)
                SetPropertyValue(Of Byte)("DEPOSITED", fDEPOSITED, value)
            End Set
        End Property
        Dim fMDFUSRID As String
        <Size(15)> _
        Public Property MDFUSRID() As String
            Get
                Return fMDFUSRID
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("MDFUSRID", fMDFUSRID, value)
            End Set
        End Property
        Dim fMODIFDT As DateTime
        Public Property MODIFDT() As DateTime
            Get
                Return fMODIFDT
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)("MODIFDT", fMODIFDT, value)
            End Set
        End Property
        Dim fCHEKBKID As String
        <Size(15)> _
        Public Property CHEKBKID() As String
            Get
                Return fCHEKBKID
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("CHEKBKID", fCHEKBKID, value)
            End Set
        End Property
        Dim fdepositnumber As String
        <Size(21)> _
        Public Property depositnumber() As String
            Get
                Return fdepositnumber
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("depositnumber", fdepositnumber, value)
            End Set
        End Property
        Dim fRCPTNMBR As String
        <Size(21)> _
        Public Property RCPTNMBR() As String
            Get
                Return fRCPTNMBR
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("RCPTNMBR", fRCPTNMBR, value)
            End Set
        End Property
        Dim freceiptdate As DateTime
        Public Property receiptdate() As DateTime
            Get
                Return freceiptdate
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)("receiptdate", freceiptdate, value)
            End Set
        End Property
        Dim fRCPTAMT As Decimal
        Public Property RCPTAMT() As Decimal
            Get
                Return fRCPTAMT
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)("RCPTAMT", fRCPTAMT, value)
            End Set
        End Property
        Dim fRcpType As Short
        Public Property RcpType() As Short
            Get
                Return fRcpType
            End Get
            Set(ByVal value As Short)
                SetPropertyValue(Of Short)("RcpType", fRcpType, value)
            End Set
        End Property
        Dim fCARDNAME As String
        <Size(15)> _
        Public Property CARDNAME() As String
            Get
                Return fCARDNAME
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("CARDNAME", fCARDNAME, value)
            End Set
        End Property
        Dim fCURNCYID As String
        <Size(15)> _
        Public Property CURNCYID() As String
            Get
                Return fCURNCYID
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("CURNCYID", fCURNCYID, value)
            End Set
        End Property
        Dim fBANKNAME As String
        <Size(31)> _
        Public Property BANKNAME() As String
            Get
                Return fBANKNAME
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("BANKNAME", fBANKNAME, value)
            End Set
        End Property
        Dim fBNKBRNCH As String
        <Size(21)> _
        Public Property BNKBRNCH() As String
            Get
                Return fBNKBRNCH
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("BNKBRNCH", fBNKBRNCH, value)
            End Set
        End Property
        Dim fGLPOSTDT As DateTime
        Public Property GLPOSTDT() As DateTime
            Get
                Return fGLPOSTDT
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)("GLPOSTDT", fGLPOSTDT, value)
            End Set
        End Property
        Dim fPOSTEDDT As DateTime
        Public Property POSTEDDT() As DateTime
            Get
                Return fPOSTEDDT
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)("POSTEDDT", fPOSTEDDT, value)
            End Set
        End Property
        Dim fPTDUSRID As String
        <Size(15)> _
        Public Property PTDUSRID() As String
            Get
                Return fPTDUSRID
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("PTDUSRID", fPTDUSRID, value)
            End Set
        End Property
        Dim fCMLinkID As String
        <Size(15)> _
        Public Property CMLinkID() As String
            Get
                Return fCMLinkID
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("CMLinkID", fCMLinkID, value)
            End Set
        End Property
        Dim fRcvdFrom As String
        <Size(31)> _
        Public Property RcvdFrom() As String
            Get
                Return fRcvdFrom
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("RcvdFrom", fRcvdFrom, value)
            End Set
        End Property
        Dim fDSCRIPTN As String
        <Size(31)> _
        Public Property DSCRIPTN() As String
            Get
                Return fDSCRIPTN
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("DSCRIPTN", fDSCRIPTN, value)
            End Set
        End Property
        Dim fVOIDED As Byte
        Public Property VOIDED() As Byte
            Get
                Return fVOIDED
            End Get
            Set(ByVal value As Byte)
                SetPropertyValue(Of Byte)("VOIDED", fVOIDED, value)
            End Set
        End Property
        Dim fVOIDDATE As DateTime
        Public Property VOIDDATE() As DateTime
            Get
                Return fVOIDDATE
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)("VOIDDATE", fVOIDDATE, value)
            End Set
        End Property
        Dim fVOIDPDATE As DateTime
        Public Property VOIDPDATE() As DateTime
            Get
                Return fVOIDPDATE
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)("VOIDPDATE", fVOIDPDATE, value)
            End Set
        End Property
        Dim fVOIDDESC As String
        <Size(31)> _
        Public Property VOIDDESC() As String
            Get
                Return fVOIDDESC
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("VOIDDESC", fVOIDDESC, value)
            End Set
        End Property
        Dim fUSERDEF1 As String
        <Size(21)> _
        Public Property USERDEF1() As String
            Get
                Return fUSERDEF1
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("USERDEF1", fUSERDEF1, value)
            End Set
        End Property
        Dim fUSERDEF2 As String
        <Size(21)> _
        Public Property USERDEF2() As String
            Get
                Return fUSERDEF2
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("USERDEF2", fUSERDEF2, value)
            End Set
        End Property
        Dim fNOTEINDX As Decimal
        Public Property NOTEINDX() As Decimal
            Get
                Return fNOTEINDX
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)("NOTEINDX", fNOTEINDX, value)
            End Set
        End Property
        Dim fRCRDSTTS As Short
        Public Property RCRDSTTS() As Short
            Get
                Return fRCRDSTTS
            End Get
            Set(ByVal value As Short)
                SetPropertyValue(Of Short)("RCRDSTTS", fRCRDSTTS, value)
            End Set
        End Property
        Dim fSOURCDOC As String
        <Size(11)> _
        Public Property SOURCDOC() As String
            Get
                Return fSOURCDOC
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("SOURCDOC", fSOURCDOC, value)
            End Set
        End Property
        Dim fSRCDOCNUM As String
        <Size(21)> _
        Public Property SRCDOCNUM() As String
            Get
                Return fSRCDOCNUM
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("SRCDOCNUM", fSRCDOCNUM, value)
            End Set
        End Property
        Dim fSRCDOCTYP As Short
        Public Property SRCDOCTYP() As Short
            Get
                Return fSRCDOCTYP
            End Get
            Set(ByVal value As Short)
                SetPropertyValue(Of Short)("SRCDOCTYP", fSRCDOCTYP, value)
            End Set
        End Property
        Dim fAUDITTRAIL As String
        <Size(13)> _
        Public Property AUDITTRAIL() As String
            Get
                Return fAUDITTRAIL
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("AUDITTRAIL", fAUDITTRAIL, value)
            End Set
        End Property
        Dim fORIGAMT As Decimal
        Public Property ORIGAMT() As Decimal
            Get
                Return fORIGAMT
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)("ORIGAMT", fORIGAMT, value)
            End Set
        End Property
        Dim fCheckbook_Amount As Decimal
        Public Property Checkbook_Amount() As Decimal
            Get
                Return fCheckbook_Amount
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)("Checkbook_Amount", fCheckbook_Amount, value)
            End Set
        End Property
        Dim fRATETPID As String
        <Size(15)> _
        Public Property RATETPID() As String
            Get
                Return fRATETPID
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("RATETPID", fRATETPID, value)
            End Set
        End Property
        Dim fRCVGRATETPID As String
        <Size(15)> _
        Public Property RCVGRATETPID() As String
            Get
                Return fRCVGRATETPID
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("RCVGRATETPID", fRCVGRATETPID, value)
            End Set
        End Property
        Dim fEXGTBLID As String
        <Size(15)> _
        Public Property EXGTBLID() As String
            Get
                Return fEXGTBLID
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("EXGTBLID", fEXGTBLID, value)
            End Set
        End Property
        Dim fXCHGRATE As Decimal
        Public Property XCHGRATE() As Decimal
            Get
                Return fXCHGRATE
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)("XCHGRATE", fXCHGRATE, value)
            End Set
        End Property
        Dim fReceiving_Exchange_Rate As Decimal
        Public Property Receiving_Exchange_Rate() As Decimal
            Get
                Return fReceiving_Exchange_Rate
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)("Receiving_Exchange_Rate", fReceiving_Exchange_Rate, value)
            End Set
        End Property
        Dim fEXCHDATE As DateTime
        Public Property EXCHDATE() As DateTime
            Get
                Return fEXCHDATE
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)("EXCHDATE", fEXCHDATE, value)
            End Set
        End Property
        Dim fTIME1 As DateTime
        Public Property TIME1() As DateTime
            Get
                Return fTIME1
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)("TIME1", fTIME1, value)
            End Set
        End Property
        Dim fRTCLCMTD As Short
        Public Property RTCLCMTD() As Short
            Get
                Return fRTCLCMTD
            End Get
            Set(ByVal value As Short)
                SetPropertyValue(Of Short)("RTCLCMTD", fRTCLCMTD, value)
            End Set
        End Property
        Dim fRCVGRTCLCMTD As Short
        Public Property RCVGRTCLCMTD() As Short
            Get
                Return fRCVGRTCLCMTD
            End Get
            Set(ByVal value As Short)
                SetPropertyValue(Of Short)("RCVGRTCLCMTD", fRCVGRTCLCMTD, value)
            End Set
        End Property
        Dim fEXPNDATE As DateTime
        Public Property EXPNDATE() As DateTime
            Get
                Return fEXPNDATE
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)("EXPNDATE", fEXPNDATE, value)
            End Set
        End Property
        Dim fCURRNIDX As Short
        Public Property CURRNIDX() As Short
            Get
                Return fCURRNIDX
            End Get
            Set(ByVal value As Short)
                SetPropertyValue(Of Short)("CURRNIDX", fCURRNIDX, value)
            End Set
        End Property
        Dim fDECPLCUR As Short
        Public Property DECPLCUR() As Short
            Get
                Return fDECPLCUR
            End Get
            Set(ByVal value As Short)
                SetPropertyValue(Of Short)("DECPLCUR", fDECPLCUR, value)
            End Set
        End Property
        Dim fRLGANLOS As Decimal
        Public Property RLGANLOS() As Decimal
            Get
                Return fRLGANLOS
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)("RLGANLOS", fRLGANLOS, value)
            End Set
        End Property
        Dim fCash_Account_Index As Integer
        Public Property Cash_Account_Index() As Integer
            Get
                Return fCash_Account_Index
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)("Cash_Account_Index", fCash_Account_Index, value)
            End Set
        End Property
        Dim fRealized_GL_Account_Inde As Integer
        Public Property Realized_GL_Account_Inde() As Integer
            Get
                Return fRealized_GL_Account_Inde
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)("Realized_GL_Account_Inde", fRealized_GL_Account_Inde, value)
            End Set
        End Property
        Dim fDENXRATE As Decimal
        Public Property DENXRATE() As Decimal
            Get
                Return fDENXRATE
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)("DENXRATE", fDENXRATE, value)
            End Set
        End Property
        Dim fMCTRXSTT As Short
        Public Property MCTRXSTT() As Short
            Get
                Return fMCTRXSTT
            End Get
            Set(ByVal value As Short)
                SetPropertyValue(Of Short)("MCTRXSTT", fMCTRXSTT, value)
            End Set
        End Property
        Dim fReceiving_DenomEXRate As Decimal
        Public Property Receiving_DenomEXRate() As Decimal
            Get
                Return fReceiving_DenomEXRate
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)("Receiving_DenomEXRate", fReceiving_DenomEXRate, value)
            End Set
        End Property
        Dim fReceiving_MC_Transaction As Short
        Public Property Receiving_MC_Transaction() As Short
            Get
                Return fReceiving_MC_Transaction
            End Get
            Set(ByVal value As Short)
                SetPropertyValue(Of Short)("Receiving_MC_Transaction", fReceiving_MC_Transaction, value)
            End Set
        End Property
        Dim fPMNTNMBR As String
        <Size(21)> _
        Public Property PMNTNMBR() As String
            Get
                Return fPMNTNMBR
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("PMNTNMBR", fPMNTNMBR, value)
            End Set
        End Property
        Dim fEFTFLAG As Byte
        Public Property EFTFLAG() As Byte
            Get
                Return fEFTFLAG
            End Get
            Set(ByVal value As Byte)
                SetPropertyValue(Of Byte)("EFTFLAG", fEFTFLAG, value)
            End Set
        End Property
        Dim fDEX_ROW_ID As Integer
        Public Property DEX_ROW_ID() As Integer
            Get
                Return fDEX_ROW_ID
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)("DEX_ROW_ID", fDEX_ROW_ID, value)
            End Set
        End Property
        Public Sub New(ByVal session As Session)
            MyBase.New(session)
        End Sub
    End Class

End Namespace
