'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
'
Namespace FirstDataService
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="ServiceSoap", [Namespace]:="http://secure2.e-xact.com/vplug-in/transaction/rpc-enc/")>  _
    Partial Public Class Service
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private SendAndCommitOperationCompleted As System.Threading.SendOrPostCallback
        
        Private TransactionInfoOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.ISS.PaymentGateways.FirstDataGlobal.My.MySettings.Default.ISS_PaymentGateways_FirstDataGlobal_FirstDataService_Service
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event SendAndCommitCompleted As SendAndCommitCompletedEventHandler
        
        '''<remarks/>
        Public Event TransactionInfoCompleted As TransactionInfoCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("http://secure2.e-xact.com/vplug-in/transaction/rpc-enc/SendAndCommit", RequestNamespace:="http://secure2.e-xact.com/vplug-in/transaction/rpc-enc/Request", ResponseNamespace:="http://secure2.e-xact.com/vplug-in/transaction/rpc-enc/Response")>  _
        Public Function SendAndCommit(ByVal SendAndCommitSource As Transaction) As TransactionResult
            Dim results() As Object = Me.Invoke("SendAndCommit", New Object() {SendAndCommitSource})
            Return CType(results(0),TransactionResult)
        End Function
        
        '''<remarks/>
        Public Overloads Sub SendAndCommitAsync(ByVal SendAndCommitSource As Transaction)
            Me.SendAndCommitAsync(SendAndCommitSource, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub SendAndCommitAsync(ByVal SendAndCommitSource As Transaction, ByVal userState As Object)
            If (Me.SendAndCommitOperationCompleted Is Nothing) Then
                Me.SendAndCommitOperationCompleted = AddressOf Me.OnSendAndCommitOperationCompleted
            End If
            Me.InvokeAsync("SendAndCommit", New Object() {SendAndCommitSource}, Me.SendAndCommitOperationCompleted, userState)
        End Sub
        
        Private Sub OnSendAndCommitOperationCompleted(ByVal arg As Object)
            If (Not (Me.SendAndCommitCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent SendAndCommitCompleted(Me, New SendAndCommitCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("http://secure2.e-xact.com/vplug-in/transaction/rpc-enc/TransactionInfo", RequestNamespace:="http://secure2.e-xact.com/vplug-in/transaction/rpc-enc/Request", ResponseNamespace:="http://secure2.e-xact.com/vplug-in/transaction/rpc-enc/Response")>  _
        Public Function TransactionInfo(ByVal TransactionInfoSource As Transaction) As TransactionResult
            Dim results() As Object = Me.Invoke("TransactionInfo", New Object() {TransactionInfoSource})
            Return CType(results(0),TransactionResult)
        End Function
        
        '''<remarks/>
        Public Overloads Sub TransactionInfoAsync(ByVal TransactionInfoSource As Transaction)
            Me.TransactionInfoAsync(TransactionInfoSource, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub TransactionInfoAsync(ByVal TransactionInfoSource As Transaction, ByVal userState As Object)
            If (Me.TransactionInfoOperationCompleted Is Nothing) Then
                Me.TransactionInfoOperationCompleted = AddressOf Me.OnTransactionInfoOperationCompleted
            End If
            Me.InvokeAsync("TransactionInfo", New Object() {TransactionInfoSource}, Me.TransactionInfoOperationCompleted, userState)
        End Sub
        
        Private Sub OnTransactionInfoOperationCompleted(ByVal arg As Object)
            If (Not (Me.TransactionInfoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent TransactionInfoCompleted(Me, New TransactionInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.Xml.Serialization.SoapIncludeAttribute(GetType(TransactionResult)),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="http://secure2.e-xact.com/vplug-in/transaction/rpc-enc/encodedTypes")>  _
    Partial Public Class Transaction
        
        Private exactIDField As String
        
        Private passwordField As String
        
        Private transaction_TypeField As String
        
        Private dollarAmountField As String
        
        Private surchargeAmountField As String
        
        Private card_NumberField As String
        
        Private transaction_TagField As String
        
        Private track1Field As String
        
        Private track2Field As String
        
        Private pANField As String
        
        Private authorization_NumField As String
        
        Private expiry_DateField As String
        
        Private cardHoldersNameField As String
        
        Private verificationStr1Field As String
        
        Private verificationStr2Field As String
        
        Private cVD_Presence_IndField As String
        
        Private zipCodeField As String
        
        Private tax1AmountField As String
        
        Private tax1NumberField As String
        
        Private tax2AmountField As String
        
        Private tax2NumberField As String
        
        Private secure_AuthRequiredField As String
        
        Private secure_AuthResultField As String
        
        Private ecommerce_FlagField As String
        
        Private xIDField As String
        
        Private cAVVField As String
        
        Private cAVV_AlgorithmField As String
        
        Private reference_NoField As String
        
        Private customer_RefField As String
        
        Private reference_3Field As String
        
        Private languageField As String
        
        Private client_IPField As String
        
        Private client_EmailField As String
        
        Private user_NameField As String
        
        Private currencyField As String
        
        Private partialRedemptionField As Boolean
        
        '''<remarks/>
        Public Property ExactID() As String
            Get
                Return Me.exactIDField
            End Get
            Set
                Me.exactIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Password() As String
            Get
                Return Me.passwordField
            End Get
            Set
                Me.passwordField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Transaction_Type() As String
            Get
                Return Me.transaction_TypeField
            End Get
            Set
                Me.transaction_TypeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property DollarAmount() As String
            Get
                Return Me.dollarAmountField
            End Get
            Set
                Me.dollarAmountField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property SurchargeAmount() As String
            Get
                Return Me.surchargeAmountField
            End Get
            Set
                Me.surchargeAmountField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Card_Number() As String
            Get
                Return Me.card_NumberField
            End Get
            Set
                Me.card_NumberField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Transaction_Tag() As String
            Get
                Return Me.transaction_TagField
            End Get
            Set
                Me.transaction_TagField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Track1() As String
            Get
                Return Me.track1Field
            End Get
            Set
                Me.track1Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Track2() As String
            Get
                Return Me.track2Field
            End Get
            Set
                Me.track2Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PAN() As String
            Get
                Return Me.pANField
            End Get
            Set
                Me.pANField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Authorization_Num() As String
            Get
                Return Me.authorization_NumField
            End Get
            Set
                Me.authorization_NumField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Expiry_Date() As String
            Get
                Return Me.expiry_DateField
            End Get
            Set
                Me.expiry_DateField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CardHoldersName() As String
            Get
                Return Me.cardHoldersNameField
            End Get
            Set
                Me.cardHoldersNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property VerificationStr1() As String
            Get
                Return Me.verificationStr1Field
            End Get
            Set
                Me.verificationStr1Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property VerificationStr2() As String
            Get
                Return Me.verificationStr2Field
            End Get
            Set
                Me.verificationStr2Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CVD_Presence_Ind() As String
            Get
                Return Me.cVD_Presence_IndField
            End Get
            Set
                Me.cVD_Presence_IndField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ZipCode() As String
            Get
                Return Me.zipCodeField
            End Get
            Set
                Me.zipCodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Tax1Amount() As String
            Get
                Return Me.tax1AmountField
            End Get
            Set
                Me.tax1AmountField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Tax1Number() As String
            Get
                Return Me.tax1NumberField
            End Get
            Set
                Me.tax1NumberField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Tax2Amount() As String
            Get
                Return Me.tax2AmountField
            End Get
            Set
                Me.tax2AmountField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Tax2Number() As String
            Get
                Return Me.tax2NumberField
            End Get
            Set
                Me.tax2NumberField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Secure_AuthRequired() As String
            Get
                Return Me.secure_AuthRequiredField
            End Get
            Set
                Me.secure_AuthRequiredField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Secure_AuthResult() As String
            Get
                Return Me.secure_AuthResultField
            End Get
            Set
                Me.secure_AuthResultField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Ecommerce_Flag() As String
            Get
                Return Me.ecommerce_FlagField
            End Get
            Set
                Me.ecommerce_FlagField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property XID() As String
            Get
                Return Me.xIDField
            End Get
            Set
                Me.xIDField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CAVV() As String
            Get
                Return Me.cAVVField
            End Get
            Set
                Me.cAVVField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CAVV_Algorithm() As String
            Get
                Return Me.cAVV_AlgorithmField
            End Get
            Set
                Me.cAVV_AlgorithmField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Reference_No() As String
            Get
                Return Me.reference_NoField
            End Get
            Set
                Me.reference_NoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Customer_Ref() As String
            Get
                Return Me.customer_RefField
            End Get
            Set
                Me.customer_RefField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Reference_3() As String
            Get
                Return Me.reference_3Field
            End Get
            Set
                Me.reference_3Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Language() As String
            Get
                Return Me.languageField
            End Get
            Set
                Me.languageField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Client_IP() As String
            Get
                Return Me.client_IPField
            End Get
            Set
                Me.client_IPField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Client_Email() As String
            Get
                Return Me.client_EmailField
            End Get
            Set
                Me.client_EmailField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property User_Name() As String
            Get
                Return Me.user_NameField
            End Get
            Set
                Me.user_NameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Currency() As String
            Get
                Return Me.currencyField
            End Get
            Set
                Me.currencyField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property PartialRedemption() As Boolean
            Get
                Return Me.partialRedemptionField
            End Get
            Set
                Me.partialRedemptionField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="http://secure2.e-xact.com/vplug-in/transaction/rpc-enc/encodedTypes")>  _
    Partial Public Class TransactionResult
        Inherits Transaction
        
        Private logonMessageField As String
        
        Private error_NumberField As String
        
        Private error_DescriptionField As String
        
        Private transaction_ErrorField As Boolean
        
        Private transaction_ApprovedField As Boolean
        
        Private eXact_Resp_CodeField As String
        
        Private eXact_MessageField As String
        
        Private bank_Resp_CodeField As String
        
        Private bank_MessageField As String
        
        Private bank_Resp_Code_2Field As String
        
        Private sequenceNoField As String
        
        Private aVSField As String
        
        Private cVV2Field As String
        
        Private retrieval_Ref_NoField As String
        
        Private cAVV_ResponseField As String
        
        Private amountRequestedField As String
        
        Private merchantNameField As String
        
        Private merchantAddressField As String
        
        Private merchantCityField As String
        
        Private merchantProvinceField As String
        
        Private merchantCountryField As String
        
        Private merchantPostalField As String
        
        Private merchantURLField As String
        
        Private cTRField As String
        
        '''<remarks/>
        Public Property LogonMessage() As String
            Get
                Return Me.logonMessageField
            End Get
            Set
                Me.logonMessageField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Error_Number() As String
            Get
                Return Me.error_NumberField
            End Get
            Set
                Me.error_NumberField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Error_Description() As String
            Get
                Return Me.error_DescriptionField
            End Get
            Set
                Me.error_DescriptionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Transaction_Error() As Boolean
            Get
                Return Me.transaction_ErrorField
            End Get
            Set
                Me.transaction_ErrorField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Transaction_Approved() As Boolean
            Get
                Return Me.transaction_ApprovedField
            End Get
            Set
                Me.transaction_ApprovedField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property EXact_Resp_Code() As String
            Get
                Return Me.eXact_Resp_CodeField
            End Get
            Set
                Me.eXact_Resp_CodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property EXact_Message() As String
            Get
                Return Me.eXact_MessageField
            End Get
            Set
                Me.eXact_MessageField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Bank_Resp_Code() As String
            Get
                Return Me.bank_Resp_CodeField
            End Get
            Set
                Me.bank_Resp_CodeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Bank_Message() As String
            Get
                Return Me.bank_MessageField
            End Get
            Set
                Me.bank_MessageField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Bank_Resp_Code_2() As String
            Get
                Return Me.bank_Resp_Code_2Field
            End Get
            Set
                Me.bank_Resp_Code_2Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property SequenceNo() As String
            Get
                Return Me.sequenceNoField
            End Get
            Set
                Me.sequenceNoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property AVS() As String
            Get
                Return Me.aVSField
            End Get
            Set
                Me.aVSField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CVV2() As String
            Get
                Return Me.cVV2Field
            End Get
            Set
                Me.cVV2Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Retrieval_Ref_No() As String
            Get
                Return Me.retrieval_Ref_NoField
            End Get
            Set
                Me.retrieval_Ref_NoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CAVV_Response() As String
            Get
                Return Me.cAVV_ResponseField
            End Get
            Set
                Me.cAVV_ResponseField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property AmountRequested() As String
            Get
                Return Me.amountRequestedField
            End Get
            Set
                Me.amountRequestedField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property MerchantName() As String
            Get
                Return Me.merchantNameField
            End Get
            Set
                Me.merchantNameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property MerchantAddress() As String
            Get
                Return Me.merchantAddressField
            End Get
            Set
                Me.merchantAddressField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property MerchantCity() As String
            Get
                Return Me.merchantCityField
            End Get
            Set
                Me.merchantCityField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property MerchantProvince() As String
            Get
                Return Me.merchantProvinceField
            End Get
            Set
                Me.merchantProvinceField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property MerchantCountry() As String
            Get
                Return Me.merchantCountryField
            End Get
            Set
                Me.merchantCountryField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property MerchantPostal() As String
            Get
                Return Me.merchantPostalField
            End Get
            Set
                Me.merchantPostalField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property MerchantURL() As String
            Get
                Return Me.merchantURLField
            End Get
            Set
                Me.merchantURLField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property CTR() As String
            Get
                Return Me.cTRField
            End Get
            Set
                Me.cTRField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub SendAndCommitCompletedEventHandler(ByVal sender As Object, ByVal e As SendAndCommitCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class SendAndCommitCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As TransactionResult
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),TransactionResult)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub TransactionInfoCompletedEventHandler(ByVal sender As Object, ByVal e As TransactionInfoCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class TransactionInfoCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As TransactionResult
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),TransactionResult)
            End Get
        End Property
    End Class
End Namespace
