'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Xpo.Metadata
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Runtime.CompilerServices
Imports System.Reflection
Namespace Objects.DD

    Partial Public Class DDEmployeeDirectDepositMaster
        Inherits XPLiteObject
        Dim fINACTIVE As Byte
        Public Property INACTIVE() As Byte
            Get
                Return fINACTIVE
            End Get
            Set(ByVal value As Byte)
                SetPropertyValue(Of Byte)(NameOf(INACTIVE), fINACTIVE, value)
            End Set
        End Property
        Dim fDEDNMTHD As Short
        Public Property DEDNMTHD() As Short
            Get
                Return fDEDNMTHD
            End Get
            Set(ByVal value As Short)
                SetPropertyValue(Of Short)(NameOf(DEDNMTHD), fDEDNMTHD, value)
            End Set
        End Property
        Dim fDEDUCTON As String
        <Size(7)>
        Public Property DEDUCTON() As String
            Get
                Return fDEDUCTON
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(DEDUCTON), fDEDUCTON, value)
            End Set
        End Property
        Dim fDDPRE As Byte
        Public Property DDPRE() As Byte
            Get
                Return fDDPRE
            End Get
            Set(ByVal value As Byte)
                SetPropertyValue(Of Byte)(NameOf(DDPRE), fDDPRE, value)
            End Set
        End Property
        Dim fDDPRECNT As Short
        Public Property DDPRECNT() As Short
            Get
                Return fDDPRECNT
            End Get
            Set(ByVal value As Short)
                SetPropertyValue(Of Short)(NameOf(DDPRECNT), fDDPRECNT, value)
            End Set
        End Property
        Dim fDDPCT As Short
        Public Property DDPCT() As Short
            Get
                Return fDDPCT
            End Get
            Set(ByVal value As Short)
                SetPropertyValue(Of Short)(NameOf(DDPCT), fDDPCT, value)
            End Set
        End Property
        Dim fDDAMTDLR As Decimal
        Public Property DDAMTDLR() As Decimal
            Get
                Return fDDAMTDLR
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)(NameOf(DDAMTDLR), fDDAMTDLR, value)
            End Set
        End Property
        Dim fDDACTNUM As String
        <Size(17)>
        Public Property DDACTNUM() As String
            Get
                Return fDDACTNUM
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(DDACTNUM), fDDACTNUM, value)
            End Set
        End Property
        Dim fDDTRANUM As String
        <Size(9)>
        Public Property DDTRANUM() As String
            Get
                Return fDDTRANUM
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(DDTRANUM), fDDTRANUM, value)
            End Set
        End Property
        Dim fDDTRANS As String
        <Size(3)>
        Public Property DDTRANS() As String
            Get
                Return fDDTRANS
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(DDTRANS), fDDTRANS, value)
            End Set
        End Property

        Public Structure CompoundKey1Struct
            <Size(15)>
            <Persistent("EMPLOYID")>
            Public Property EMPLOYID As String
            <Persistent("INDXLONG")>
            Public Property INDXLONG As Integer
        End Structure
        <Key(), Persistent()>
        Public CompoundKey1 As CompoundKey1Struct
    End Class

End Namespace
