'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Namespace Objects.CN

    Partial Public Class NoteDocHistory
        Inherits XPLiteObject
        Dim fCUSTNMBR As String
        <Size(15)>
        Public Property CUSTNMBR() As String
            Get
                Return fCUSTNMBR
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("CUSTNMBR", fCUSTNMBR, value)
            End Set
        End Property
        Dim fCPRCSTNM As String
        <Size(15)>
        Public Property CPRCSTNM() As String
            Get
                Return fCPRCSTNM
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("CPRCSTNM", fCPRCSTNM, value)
            End Set
        End Property
        Dim fRevisionDate As DateTime
        Public Property RevisionDate() As DateTime
            Get
                Return fRevisionDate
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)("RevisionDate", fRevisionDate, value)
            End Set
        End Property
        Dim fRevisionTime As DateTime
        Public Property RevisionTime() As DateTime
            Get
                Return fRevisionTime
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)("RevisionTime", fRevisionTime, value)
            End Set
        End Property
        Dim fUSERID As String
        <Size(15)>
        Public Property USERID() As String
            Get
                Return fUSERID
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("USERID", fUSERID, value)
            End Set
        End Property
        Dim fActionType As Short
        Public Property ActionType() As Short
            Get
                Return fActionType
            End Get
            Set(ByVal value As Short)
                SetPropertyValue(Of Short)("ActionType", fActionType, value)
            End Set
        End Property
        Dim fActionAmount As Decimal
        Public Property ActionAmount() As Decimal
            Get
                Return fActionAmount
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)("ActionAmount", fActionAmount, value)
            End Set
        End Property
        Dim fCURTRXAM As Decimal
        Public Property CURTRXAM() As Decimal
            Get
                Return fCURTRXAM
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)("CURTRXAM", fCURTRXAM, value)
            End Set
        End Property
        Dim fCURNCYID As String
        <Size(15)>
        Public Property CURNCYID() As String
            Get
                Return fCURNCYID
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("CURNCYID", fCURNCYID, value)
            End Set
        End Property
        Dim fCURRNIDX As Short
        Public Property CURRNIDX() As Short
            Get
                Return fCURRNIDX
            End Get
            Set(ByVal value As Short)
                SetPropertyValue(Of Short)("CURRNIDX", fCURRNIDX, value)
            End Set
        End Property
        Dim fDEX_ROW_ID As Integer
        Public Property DEX_ROW_ID() As Integer
            Get
                Return fDEX_ROW_ID
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)("DEX_ROW_ID", fDEX_ROW_ID, value)
            End Set
        End Property
        Public Structure CompoundKey1Struct
            <Persistent("RMDTYPAL")>
            Public Property RMDTYPAL As Short
            <Size(21)>
            <Persistent("DOCNUMBR")>
            Public Property DOCNUMBR As String
            <Persistent("NOTEINDX")>
            Public Property NOTEINDX As Decimal
            <Persistent("RevisionNumber")>
            Public Property RevisionNumber As Short
        End Structure

        <Key(), Persistent()>
        Public CompoundKey1 As CompoundKey1Struct
    End Class

End Namespace
