'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Namespace Objects.CN

    <DefaultProperty("Query_ID")>
    Partial Public Class CNQuery
        Inherits XPLiteObject
        Dim fQuery_ID As String
        <Key()>
        <Size(15)>
        Public Property Query_ID() As String
            Get
                Return fQuery_ID
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Query_ID", fQuery_ID, value)
            End Set
        End Property
        Dim fQuery_Description As String
        <Size(31)>
        Public Property Query_Description() As String
            Get
                Return fQuery_Description
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Query_Description", fQuery_Description, value)
            End Set
        End Property
        Dim fSTCUSTID As String
        <Size(15)>
        Public Property STCUSTID() As String
            Get
                Return fSTCUSTID
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("STCUSTID", fSTCUSTID, value)
            End Set
        End Property
        Dim fSTCUSTNM As String
        <Size(65)>
        Public Property STCUSTNM() As String
            Get
                Return fSTCUSTNM
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("STCUSTNM", fSTCUSTNM, value)
            End Set
        End Property
        Dim fSTTCLSID As String
        <Size(15)>
        Public Property STTCLSID() As String
            Get
                Return fSTTCLSID
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("STTCLSID", fSTTCLSID, value)
            End Set
        End Property
        Dim fSTTUDEF1 As String
        <Size(21)>
        Public Property STTUDEF1() As String
            Get
                Return fSTTUDEF1
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("STTUDEF1", fSTTUDEF1, value)
            End Set
        End Property
        Dim fSTSPRSID As String
        <Size(15)>
        Public Property STSPRSID() As String
            Get
                Return fSTSPRSID
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("STSPRSID", fSTSPRSID, value)
            End Set
        End Property
        Dim fSTSLSTER As String
        <Size(15)>
        Public Property STSLSTER() As String
            Get
                Return fSTSLSTER
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("STSLSTER", fSTSLSTER, value)
            End Set
        End Property
        Dim fStartPrefContactMethod As Short
        Public Property StartPrefContactMethod() As Short
            Get
                Return fStartPrefContactMethod
            End Get
            Set(ByVal value As Short)
                SetPropertyValue(Of Short)("StartPrefContactMethod", fStartPrefContactMethod, value)
            End Set
        End Property
        Dim fCNStartTimeZone As Short
        Public Property CNStartTimeZone() As Short
            Get
                Return fCNStartTimeZone
            End Get
            Set(ByVal value As Short)
                SetPropertyValue(Of Short)("CNStartTimeZone", fCNStartTimeZone, value)
            End Set
        End Property
        Dim fSTRTUDEF As String
        <Size(21)>
        Public Property STRTUDEF() As String
            Get
                Return fSTRTUDEF
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("STRTUDEF", fSTRTUDEF, value)
            End Set
        End Property
        Dim fSTUDDAT1 As DateTime
        Public Property STUDDAT1() As DateTime
            Get
                Return fSTUDDAT1
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)("STUDDAT1", fSTUDDAT1, value)
            End Set
        End Property
        Dim fSTUDTAB1 As String
        <Size(21)>
        Public Property STUDTAB1() As String
            Get
                Return fSTUDTAB1
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("STUDTAB1", fSTUDTAB1, value)
            End Set
        End Property
        Dim fENCUSTID As String
        <Size(15)>
        Public Property ENCUSTID() As String
            Get
                Return fENCUSTID
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("ENCUSTID", fENCUSTID, value)
            End Set
        End Property
        Dim fENCSTNAM As String
        <Size(65)>
        Public Property ENCSTNAM() As String
            Get
                Return fENCSTNAM
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("ENCSTNAM", fENCSTNAM, value)
            End Set
        End Property
        Dim fENDCLSID As String
        <Size(15)>
        Public Property ENDCLSID() As String
            Get
                Return fENDCLSID
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("ENDCLSID", fENDCLSID, value)
            End Set
        End Property
        Dim fENUSRDF1 As String
        <Size(21)>
        Public Property ENUSRDF1() As String
            Get
                Return fENUSRDF1
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("ENUSRDF1", fENUSRDF1, value)
            End Set
        End Property
        Dim fENSPSNID As String
        <Size(15)>
        Public Property ENSPSNID() As String
            Get
                Return fENSPSNID
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("ENSPSNID", fENSPSNID, value)
            End Set
        End Property
        Dim fENSLSTER As String
        <Size(15)>
        Public Property ENSLSTER() As String
            Get
                Return fENSLSTER
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("ENSLSTER", fENSLSTER, value)
            End Set
        End Property
        Dim fCNEndTimeZone As Short
        Public Property CNEndTimeZone() As Short
            Get
                Return fCNEndTimeZone
            End Get
            Set(ByVal value As Short)
                SetPropertyValue(Of Short)("CNEndTimeZone", fCNEndTimeZone, value)
            End Set
        End Property
        Dim fEndPrefContactMethod As Short
        Public Property EndPrefContactMethod() As Short
            Get
                Return fEndPrefContactMethod
            End Get
            Set(ByVal value As Short)
                SetPropertyValue(Of Short)("EndPrefContactMethod", fEndPrefContactMethod, value)
            End Set
        End Property
        Dim fENUSRDEF As String
        <Size(21)>
        Public Property ENUSRDEF() As String
            Get
                Return fENUSRDEF
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("ENUSRDEF", fENUSRDEF, value)
            End Set
        End Property
        Dim fENDUDDT1 As DateTime
        Public Property ENDUDDT1() As DateTime
            Get
                Return fENDUDDT1
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)("ENDUDDT1", fENDUDDT1, value)
            End Set
        End Property
        Dim fENDUDTBL As String
        <Size(21)>
        Public Property ENDUDTBL() As String
            Get
                Return fENDUDTBL
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("ENDUDTBL", fENDUDTBL, value)
            End Set
        End Property
        Dim fStartCreditControlCycle As Short
        Public Property StartCreditControlCycle() As Short
            Get
                Return fStartCreditControlCycle
            End Get
            Set(ByVal value As Short)
                SetPropertyValue(Of Short)("StartCreditControlCycle", fStartCreditControlCycle, value)
            End Set
        End Property
        Dim fEndCreditControlCyle As Short
        Public Property EndCreditControlCyle() As Short
            Get
                Return fEndCreditControlCyle
            End Get
            Set(ByVal value As Short)
                SetPropertyValue(Of Short)("EndCreditControlCyle", fEndCreditControlCyle, value)
            End Set
        End Property
        Dim fCONNAACT As Byte
        Public Property CONNAACT() As Byte
            Get
                Return fCONNAACT
            End Get
            Set(ByVal value As Byte)
                SetPropertyValue(Of Byte)("CONNAACT", fCONNAACT, value)
            End Set
        End Property
        Dim fDateSelection As Short
        Public Property DateSelection() As Short
            Get
                Return fDateSelection
            End Get
            Set(ByVal value As Short)
                SetPropertyValue(Of Short)("DateSelection", fDateSelection, value)
            End Set
        End Property
        Dim fQRYSTCDTPER As Short
        Public Property QRYSTCDTPER() As Short
            Get
                Return fQRYSTCDTPER
            End Get
            Set(ByVal value As Short)
                SetPropertyValue(Of Short)("QRYSTCDTPER", fQRYSTCDTPER, value)
            End Set
        End Property
        Dim fQryEndCrLimitPeriod As Short
        Public Property QryEndCrLimitPeriod() As Short
            Get
                Return fQryEndCrLimitPeriod
            End Get
            Set(ByVal value As Short)
                SetPropertyValue(Of Short)("QryEndCrLimitPeriod", fQryEndCrLimitPeriod, value)
            End Set
        End Property
        Dim fQRYSTCDTAMT As Decimal
        Public Property QRYSTCDTAMT() As Decimal
            Get
                Return fQRYSTCDTAMT
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)("QRYSTCDTAMT", fQRYSTCDTAMT, value)
            End Set
        End Property
        Dim fQryEndCreditLimitAmt As Decimal
        Public Property QryEndCreditLimitAmt() As Decimal
            Get
                Return fQryEndCreditLimitAmt
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)("QryEndCreditLimitAmt", fQryEndCreditLimitAmt, value)
            End Set
        End Property
        Dim fQryStartDateToken As Short
        Public Property QryStartDateToken() As Short
            Get
                Return fQryStartDateToken
            End Get
            Set(ByVal value As Short)
                SetPropertyValue(Of Short)("QryStartDateToken", fQryStartDateToken, value)
            End Set
        End Property
        Dim fQryEndDateToken As Short
        Public Property QryEndDateToken() As Short
            Get
                Return fQryEndDateToken
            End Get
            Set(ByVal value As Short)
                SetPropertyValue(Of Short)("QryEndDateToken", fQryEndDateToken, value)
            End Set
        End Property
        Dim fSTRTNGDT As DateTime
        Public Property STRTNGDT() As DateTime
            Get
                Return fSTRTNGDT
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)("STRTNGDT", fSTRTNGDT, value)
            End Set
        End Property
        Dim fENDINGDT As DateTime
        Public Property ENDINGDT() As DateTime
            Get
                Return fENDINGDT
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)("ENDINGDT", fENDINGDT, value)
            End Set
        End Property
        Dim fStarting_Trx_Days As Short
        Public Property Starting_Trx_Days() As Short
            Get
                Return fStarting_Trx_Days
            End Get
            Set(ByVal value As Short)
                SetPropertyValue(Of Short)("Starting_Trx_Days", fStarting_Trx_Days, value)
            End Set
        End Property
        Dim fEnding_Trx_Days As Short
        Public Property Ending_Trx_Days() As Short
            Get
                Return fEnding_Trx_Days
            End Get
            Set(ByVal value As Short)
                SetPropertyValue(Of Short)("Ending_Trx_Days", fEnding_Trx_Days, value)
            End Set
        End Property
        Dim fStart_Caller_ID As String
        <Size(15)>
        Public Property Start_Caller_ID() As String
            Get
                Return fStart_Caller_ID
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Start_Caller_ID", fStart_Caller_ID, value)
            End Set
        End Property
        Dim fStart_Contact_Date As DateTime
        Public Property Start_Contact_Date() As DateTime
            Get
                Return fStart_Contact_Date
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)("Start_Contact_Date", fStart_Contact_Date, value)
            End Set
        End Property
        Dim fStart_Action_Assigned_To As String
        <Size(15)>
        Public Property Start_Action_Assigned_To() As String
            Get
                Return fStart_Action_Assigned_To
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Start_Action_Assigned_To", fStart_Action_Assigned_To, value)
            End Set
        End Property
        Dim fStart_Action_Promised As String
        <Size(17)>
        Public Property Start_Action_Promised() As String
            Get
                Return fStart_Action_Promised
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Start_Action_Promised", fStart_Action_Promised, value)
            End Set
        End Property
        Dim fStart_Action_Date As DateTime
        Public Property Start_Action_Date() As DateTime
            Get
                Return fStart_Action_Date
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)("Start_Action_Date", fStart_Action_Date, value)
            End Set
        End Property
        Dim fSNOTPRTY As Short
        Public Property SNOTPRTY() As Short
            Get
                Return fSNOTPRTY
            End Get
            Set(ByVal value As Short)
                SetPropertyValue(Of Short)("SNOTPRTY", fSNOTPRTY, value)
            End Set
        End Property
        Dim fQRYACTCOM As Short
        Public Property QRYACTCOM() As Short
            Get
                Return fQRYACTCOM
            End Get
            Set(ByVal value As Short)
                SetPropertyValue(Of Short)("QRYACTCOM", fQRYACTCOM, value)
            End Set
        End Property
        Dim fEnd_Caller_ID As String
        <Size(15)>
        Public Property End_Caller_ID() As String
            Get
                Return fEnd_Caller_ID
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("End_Caller_ID", fEnd_Caller_ID, value)
            End Set
        End Property
        Dim fEnd_Contact_Date As DateTime
        Public Property End_Contact_Date() As DateTime
            Get
                Return fEnd_Contact_Date
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)("End_Contact_Date", fEnd_Contact_Date, value)
            End Set
        End Property
        Dim fEnd_Action_Assigned_To As String
        <Size(15)>
        Public Property End_Action_Assigned_To() As String
            Get
                Return fEnd_Action_Assigned_To
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("End_Action_Assigned_To", fEnd_Action_Assigned_To, value)
            End Set
        End Property
        Dim fEnd_Action_Promised As String
        <Size(17)>
        Public Property End_Action_Promised() As String
            Get
                Return fEnd_Action_Promised
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("End_Action_Promised", fEnd_Action_Promised, value)
            End Set
        End Property
        Dim fEnd_Action_Date As DateTime
        Public Property End_Action_Date() As DateTime
            Get
                Return fEnd_Action_Date
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)("End_Action_Date", fEnd_Action_Date, value)
            End Set
        End Property
        Dim fENOTPRTY As Short
        Public Property ENOTPRTY() As Short
            Get
                Return fENOTPRTY
            End Get
            Set(ByVal value As Short)
                SetPropertyValue(Of Short)("ENOTPRTY", fENOTPRTY, value)
            End Set
        End Property
        Dim fQCMFLAG As Byte
        Public Property QCMFLAG() As Byte
            Get
                Return fQCMFLAG
            End Get
            Set(ByVal value As Byte)
                SetPropertyValue(Of Byte)("QCMFLAG", fQCMFLAG, value)
            End Set
        End Property
        Dim fStart_Credit_Manager As String
        <Size(15)>
        Public Property Start_Credit_Manager() As String
            Get
                Return fStart_Credit_Manager
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Start_Credit_Manager", fStart_Credit_Manager, value)
            End Set
        End Property
        Dim fEnd_Credit_Manager As String
        <Size(15)>
        Public Property End_Credit_Manager() As String
            Get
                Return fEnd_Credit_Manager
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("End_Credit_Manager", fEnd_Credit_Manager, value)
            End Set
        End Property
        Dim fCUSTCSTS As Short
        Public Property CUSTCSTS() As Short
            Get
                Return fCUSTCSTS
            End Get
            Set(ByVal value As Short)
                SetPropertyValue(Of Short)("CUSTCSTS", fCUSTCSTS, value)
            End Set
        End Property
        Dim fQueryBalanceReturned As Short
        Public Property QueryBalanceReturned() As Short
            Get
                Return fQueryBalanceReturned
            End Get
            Set(ByVal value As Short)
                SetPropertyValue(Of Short)("QueryBalanceReturned", fQueryBalanceReturned, value)
            End Set
        End Property
        Dim fQueryExcludeOlderBalance As Byte
        Public Property QueryExcludeOlderBalance() As Byte
            Get
                Return fQueryExcludeOlderBalance
            End Get
            Set(ByVal value As Byte)
                SetPropertyValue(Of Byte)("QueryExcludeOlderBalance", fQueryExcludeOlderBalance, value)
            End Set
        End Property
        Dim fQryExcludeifPaymentMade As Byte
        Public Property QryExcludeifPaymentMade() As Byte
            Get
                Return fQryExcludeifPaymentMade
            End Get
            Set(ByVal value As Byte)
                SetPropertyValue(Of Byte)("QryExcludeifPaymentMade", fQryExcludeifPaymentMade, value)
            End Set
        End Property
        Dim fQueryNumberofDays As Short
        Public Property QueryNumberofDays() As Short
            Get
                Return fQueryNumberofDays
            End Get
            Set(ByVal value As Short)
                SetPropertyValue(Of Short)("QueryNumberofDays", fQueryNumberofDays, value)
            End Set
        End Property
        Dim fQueryNoteExists As Short
        Public Property QueryNoteExists() As Short
            Get
                Return fQueryNoteExists
            End Get
            Set(ByVal value As Short)
                SetPropertyValue(Of Short)("QueryNoteExists", fQueryNoteExists, value)
            End Set
        End Property
        Dim fSTUDTAB2 As String
        <Size(21)>
        Public Property STUDTAB2() As String
            Get
                Return fSTUDTAB2
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("STUDTAB2", fSTUDTAB2, value)
            End Set
        End Property
        Dim fENDUDTBL2 As String
        <Size(21)>
        Public Property ENDUDTBL2() As String
            Get
                Return fENDUDTBL2
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("ENDUDTBL2", fENDUDTBL2, value)
            End Set
        End Property
        Dim fUSERLANG As Short
        Public Property USERLANG() As Short
            Get
                Return fUSERLANG
            End Get
            Set(ByVal value As Short)
                SetPropertyValue(Of Short)("USERLANG", fUSERLANG, value)
            End Set
        End Property
        Dim fCN_Credit_LevelStart As Short
        Public Property CN_Credit_LevelStart() As Short
            Get
                Return fCN_Credit_LevelStart
            End Get
            Set(ByVal value As Short)
                SetPropertyValue(Of Short)("CN_Credit_LevelStart", fCN_Credit_LevelStart, value)
            End Set
        End Property
        Dim fCN_Credit_LevelEnd As Short
        Public Property CN_Credit_LevelEnd() As Short
            Get
                Return fCN_Credit_LevelEnd
            End Get
            Set(ByVal value As Short)
                SetPropertyValue(Of Short)("CN_Credit_LevelEnd", fCN_Credit_LevelEnd, value)
            End Set
        End Property
        Dim fQuery_Exclude_Partial_Pa As Byte
        Public Property Query_Exclude_Partial_Pa() As Byte
            Get
                Return fQuery_Exclude_Partial_Pa
            End Get
            Set(ByVal value As Byte)
                SetPropertyValue(Of Byte)("Query_Exclude_Partial_Pa", fQuery_Exclude_Partial_Pa, value)
            End Set
        End Property
        Dim fCN_BalanceOverCreditLim As Byte
        Public Property CN_BalanceOverCreditLim() As Byte
            Get
                Return fCN_BalanceOverCreditLim
            End Get
            Set(ByVal value As Byte)
                SetPropertyValue(Of Byte)("CN_BalanceOverCreditLim", fCN_BalanceOverCreditLim, value)
            End Set
        End Property
        Dim fDEX_ROW_ID As Integer
        Public Property DEX_ROW_ID() As Integer
            Get
                Return fDEX_ROW_ID
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)("DEX_ROW_ID", fDEX_ROW_ID, value)
            End Set
        End Property
    End Class

End Namespace
