'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Namespace Objects.CN
    ''' <summary>
    ''' GP Table CN10200
    ''' </summary>
    <Persistent("CN10200")>
    Partial Public Class CNQueryStats
        Inherits XPLiteObject
        Dim fUSERID As String
        <Size(15)>
        Public Property USERID() As String
            Get
                Return fUSERID
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("USERID", fUSERID, value)
            End Set
        End Property
        Dim fQueryExecuteTime As Integer
        Public Property QueryExecuteTime() As Integer
            Get
                Return fQueryExecuteTime
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)("QueryExecuteTime", fQueryExecuteTime, value)
            End Set
        End Property
        Dim fQuery_Total_Records As Integer
        Public Property Query_Total_Records() As Integer
            Get
                Return fQuery_Total_Records
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)("Query_Total_Records", fQuery_Total_Records, value)
            End Set
        End Property
        Dim fQueryRecordsFound As Integer
        Public Property QueryRecordsFound() As Integer
            Get
                Return fQueryRecordsFound
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)("QueryRecordsFound", fQueryRecordsFound, value)
            End Set
        End Property
        Dim fQueryTotalBalance As Decimal
        Public Property QueryTotalBalance() As Decimal
            Get
                Return fQueryTotalBalance
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)("QueryTotalBalance", fQueryTotalBalance, value)
            End Set
        End Property
        Dim fQueryTotalPastDue As Decimal
        Public Property QueryTotalPastDue() As Decimal
            Get
                Return fQueryTotalPastDue
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)("QueryTotalPastDue", fQueryTotalPastDue, value)
            End Set
        End Property
        Dim fQueryCurrentRecord As String
        <Size(15)>
        Public Property QueryCurrentRecord() As String
            Get
                Return fQueryCurrentRecord
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("QueryCurrentRecord", fQueryCurrentRecord, value)
            End Set
        End Property
        Dim fDEX_ROW_ID As Integer
        Public Property DEX_ROW_ID() As Integer
            Get
                Return fDEX_ROW_ID
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)("DEX_ROW_ID", fDEX_ROW_ID, value)
            End Set
        End Property
        Public Structure CompoundKey1Struct
            <Size(15)>
            <Persistent("Query_ID")>
            Public Property Query_ID As String
            <Persistent("DATE1")>
            Public Property DATE1 As DateTime
            <Persistent("TIME1")>
            Public Property TIME1 As DateTime
        End Structure
        <Key(), Persistent()>
        Public CompoundKey1 As CompoundKey1Struct
        Public Sub New(ByVal session As Session)
            MyBase.New(session)
        End Sub
    End Class

End Namespace
