'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Xpo.Metadata
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Runtime.CompilerServices
Imports System.Reflection
Namespace CommerceIntegrations

    ''' <summary>
    ''' For a standard order, 
    ''' </summary>
    <Persistent("spAuditLog")>
    <MasterProvider.Module.AllowDataModificationsInMasterProvider>
    Partial Public Class AuditLog
        Inherits XPLiteObject
        Dim fAuditId As Integer
        <Key(True)>
        Public Property AuditId() As Integer
            Get
                Return fAuditId
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)(NameOf(AuditId), fAuditId, value)
            End Set
        End Property
        Dim fOrderNumber As String
        <Size(21)>
        Public Property OrderNumber() As String
            Get
                Return fOrderNumber
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(OrderNumber), fOrderNumber, value)
            End Set
        End Property
        Dim fAuditDateTime As DateTime
        Public Property AuditDateTime() As DateTime
            Get
                Return fAuditDateTime
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)(NameOf(AuditDateTime), fAuditDateTime, value)
            End Set
        End Property
        Dim fUsername As String
        <Size(64)>
        Public Property Username() As String
            Get
                Return fUsername
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(Username), fUsername, value)
            End Set
        End Property
        Dim fBatch As String
        <Size(15)>
        Public Property Batch() As String
            Get
                Return fBatch
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(Batch), fBatch, value)
            End Set
        End Property
        Dim fPriority As Short
        <ColumnDbDefaultValue("((0))")>
        Public Property Priority() As Short
            Get
                Return fPriority
            End Get
            Set(ByVal value As Short)
                SetPropertyValue(Of Short)(NameOf(Priority), fPriority, value)
            End Set
        End Property
        Dim fAuditText As String
        <Size(SizeAttribute.Unlimited)>
        Public Property AuditText() As String
            Get
                Return fAuditText
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(AuditText), fAuditText, value)
            End Set
        End Property
        Dim fSales_Doc_Type As String
        <Size(25)>
        Public Property Sales_Doc_Type() As String
            Get
                Return fSales_Doc_Type
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(Sales_Doc_Type), fSales_Doc_Type, value)
            End Set
        End Property
        Public Sub New(ByVal session As Session)
            MyBase.New(session)
        End Sub
    End Class

End Namespace
