'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Xpo.Metadata
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Runtime.CompilerServices
Imports System.Reflection
Namespace Objects.CLM

    <Persistent("CLM00200")>
    Partial Public Class CLMLicenseMaster
        Inherits XPLiteObject
        Dim fCLM_License_Code As String
        <Size(7)>
        Public Property CLM_License_Code() As String
            Get
                Return fCLM_License_Code
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(CLM_License_Code), fCLM_License_Code, value)
            End Set
        End Property
        Dim fCLM_Issued_By As String
        <Size(15)>
        Public Property CLM_Issued_By() As String
            Get
                Return fCLM_Issued_By
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(CLM_Issued_By), fCLM_Issued_By, value)
            End Set
        End Property
        Dim fSTATE As String
        <Size(29)>
        Public Property STATE() As String
            Get
                Return fSTATE
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(STATE), fSTATE, value)
            End Set
        End Property
        Dim fCLM_Org_Issue_Date As DateTime
        Public Property CLM_Org_Issue_Date() As DateTime
            Get
                Return fCLM_Org_Issue_Date
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)(NameOf(CLM_Org_Issue_Date), fCLM_Org_Issue_Date, value)
            End Set
        End Property
        Dim fCLM_Date_Renewed As DateTime
        Public Property CLM_Date_Renewed() As DateTime
            Get
                Return fCLM_Date_Renewed
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)(NameOf(CLM_Date_Renewed), fCLM_Date_Renewed, value)
            End Set
        End Property
        Dim fEXPNDATE As DateTime
        Public Property EXPNDATE() As DateTime
            Get
                Return fEXPNDATE
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)(NameOf(EXPNDATE), fEXPNDATE, value)
            End Set
        End Property
        Dim fUSERDEF1 As String
        <Size(21)>
        Public Property USERDEF1() As String
            Get
                Return fUSERDEF1
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(USERDEF1), fUSERDEF1, value)
            End Set
        End Property
        Dim fUSERDEF2 As String
        <Size(21)>
        Public Property USERDEF2() As String
            Get
                Return fUSERDEF2
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(USERDEF2), fUSERDEF2, value)
            End Set
        End Property
        Dim fUSRDEF03 As String
        <Size(21)>
        Public Property USRDEF03() As String
            Get
                Return fUSRDEF03
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(USRDEF03), fUSRDEF03, value)
            End Set
        End Property
        Dim fUSRDEF04 As String
        <Size(21)>
        Public Property USRDEF04() As String
            Get
                Return fUSRDEF04
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(USRDEF04), fUSRDEF04, value)
            End Set
        End Property
        Dim fINACTIVE As Byte
        Public Property INACTIVE() As Byte
            Get
                Return fINACTIVE
            End Get
            Set(ByVal value As Byte)
                SetPropertyValue(Of Byte)(NameOf(INACTIVE), fINACTIVE, value)
            End Set
        End Property
        Dim fCHANGEBY_I As String
        <Size(15)>
        Public Property CHANGEBY_I() As String
            Get
                Return fCHANGEBY_I
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(CHANGEBY_I), fCHANGEBY_I, value)
            End Set
        End Property
        Dim fCHANGEDATE_I As DateTime
        Public Property CHANGEDATE_I() As DateTime
            Get
                Return fCHANGEDATE_I
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)(NameOf(CHANGEDATE_I), fCHANGEDATE_I, value)
            End Set
        End Property
        Dim fTIME1 As DateTime
        Public Property TIME1() As DateTime
            Get
                Return fTIME1
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)(NameOf(TIME1), fTIME1, value)
            End Set
        End Property
        Dim fNOTEINDX As Decimal
        Public Property NOTEINDX() As Decimal
            Get
                Return fNOTEINDX
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)(NameOf(NOTEINDX), fNOTEINDX, value)
            End Set
        End Property

        Public Structure CompoundKey1Struct
            <Size(15)>
            <Persistent("EMPLOYID")>
            Public Property EMPLOYID As String
            <Size(31)>
            <Persistent("CLM_License_Number")>
            Public Property CLM_License_Number As String
        End Structure
        <Key(), Persistent()>
        Public CompoundKey1 As CompoundKey1Struct
    End Class

End Namespace
