'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Xpo.Metadata
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Runtime.CompilerServices
Imports System.Reflection
Namespace Objects.UPR

    <Persistent("UPR00300")>
    Partial Public Class UPREmployeeTax
        Inherits XPLiteObject
        Dim fNOTEINDX As Decimal
        Public Property NOTEINDX() As Decimal
            Get
                Return fNOTEINDX
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)(NameOf(NOTEINDX), fNOTEINDX, value)
            End Set
        End Property
        Dim fEMPLOYID As String
        <Key()>
        <Size(15)>
        Public Property EMPLOYID() As String
            Get
                Return fEMPLOYID
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(EMPLOYID), fEMPLOYID, value)
            End Set
        End Property
        Dim fEXMFRFED As Byte
        Public Property EXMFRFED() As Byte
            Get
                Return fEXMFRFED
            End Get
            Set(ByVal value As Byte)
                SetPropertyValue(Of Byte)(NameOf(EXMFRFED), fEXMFRFED, value)
            End Set
        End Property
        Dim fFDFLGSTS As String
        <Size(7)>
        Public Property FDFLGSTS() As String
            Get
                Return fFDFLGSTS
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(FDFLGSTS), fFDFLGSTS, value)
            End Set
        End Property
        Dim fFEDEXMPT As Short
        Public Property FEDEXMPT() As Short
            Get
                Return fFEDEXMPT
            End Get
            Set(ByVal value As Short)
                SetPropertyValue(Of Short)(NameOf(FEDEXMPT), fFEDEXMPT, value)
            End Set
        End Property
        Dim fADFDWHDG As Decimal
        Public Property ADFDWHDG() As Decimal
            Get
                Return fADFDWHDG
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)(NameOf(ADFDWHDG), fADFDWHDG, value)
            End Set
        End Property
        Dim fESTFEDWH As Decimal
        Public Property ESTFEDWH() As Decimal
            Get
                Return fESTFEDWH
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)(NameOf(ESTFEDWH), fESTFEDWH, value)
            End Set
        End Property
        Dim fSTATECD As String
        <Size(3)>
        Public Property STATECD() As String
            Get
                Return fSTATECD
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(STATECD), fSTATECD, value)
            End Set
        End Property
        Dim fLOCALTAX As String
        <Size(7)>
        Public Property LOCALTAX() As String
            Get
                Return fLOCALTAX
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(LOCALTAX), fLOCALTAX, value)
            End Set
        End Property
        Dim fW2BF942E As Byte
        Public Property W2BF942E() As Byte
            Get
                Return fW2BF942E
            End Get
            Set(ByVal value As Byte)
                SetPropertyValue(Of Byte)(NameOf(W2BF942E), fW2BF942E, value)
            End Set
        End Property
        Dim fW2BFDCSD As Byte
        Public Property W2BFDCSD() As Byte
            Get
                Return fW2BFDCSD
            End Get
            Set(ByVal value As Byte)
                SetPropertyValue(Of Byte)(NameOf(W2BFDCSD), fW2BFDCSD, value)
            End Set
        End Property
        Dim fW2BFDCMP As Byte
        Public Property W2BFDCMP() As Byte
            Get
                Return fW2BFDCMP
            End Get
            Set(ByVal value As Byte)
                SetPropertyValue(Of Byte)(NameOf(W2BFDCMP), fW2BFDCMP, value)
            End Set
        End Property
        Dim fW2BFLREP As Byte
        Public Property W2BFLREP() As Byte
            Get
                Return fW2BFLREP
            End Get
            Set(ByVal value As Byte)
                SetPropertyValue(Of Byte)(NameOf(W2BFLREP), fW2BFLREP, value)
            End Set
        End Property
        Dim fW2BFPPLN As Byte
        Public Property W2BFPPLN() As Byte
            Get
                Return fW2BFPPLN
            End Get
            Set(ByVal value As Byte)
                SetPropertyValue(Of Byte)(NameOf(W2BFPPLN), fW2BFPPLN, value)
            End Set
        End Property
        Dim fW2BFSTEM As Byte
        Public Property W2BFSTEM() As Byte
            Get
                Return fW2BFSTEM
            End Get
            Set(ByVal value As Byte)
                SetPropertyValue(Of Byte)(NameOf(W2BFSTEM), fW2BFSTEM, value)
            End Set
        End Property
        Dim fMCRQGEMP As Byte
        Public Property MCRQGEMP() As Byte
            Get
                Return fMCRQGEMP
            End Get
            Set(ByVal value As Byte)
                SetPropertyValue(Of Byte)(NameOf(MCRQGEMP), fMCRQGEMP, value)
            End Set
        End Property
        Dim fEICFLGST As String
        <Size(7)>
        Public Property EICFLGST() As String
            Get
                Return fEICFLGST
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(EICFLGST), fEICFLGST, value)
            End Set
        End Property
        Dim fNYTXDiff As Byte
        Public Property NYTXDiff() As Byte
            Get
                Return fNYTXDiff
            End Get
            Set(ByVal value As Byte)
                SetPropertyValue(Of Byte)(NameOf(NYTXDiff), fNYTXDiff, value)
            End Set
        End Property
        Dim fQualifiedHire As Byte
        Public Property QualifiedHire() As Byte
            Get
                Return fQualifiedHire
            End Get
            Set(ByVal value As Byte)
                SetPropertyValue(Of Byte)(NameOf(QualifiedHire), fQualifiedHire, value)
            End Set
        End Property
        Dim fMarriedWithholdAsSingle As Byte
        Public Property MarriedWithholdAsSingle() As Byte
            Get
                Return fMarriedWithholdAsSingle
            End Get
            Set(ByVal value As Byte)
                SetPropertyValue(Of Byte)(NameOf(MarriedWithholdAsSingle), fMarriedWithholdAsSingle, value)
            End Set
        End Property
    End Class

End Namespace
