'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Xpo.Metadata
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Runtime.CompilerServices
Imports System.Reflection
Namespace Objects.UPR

    Partial Public Class UPREmployeeEducationInformation
        Inherits XPLiteObject
        Dim fUNIVERSITY As String
        <Size(31)>
        Public Property UNIVERSITY() As String
            Get
                Return fUNIVERSITY
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(UNIVERSITY), fUNIVERSITY, value)
            End Set
        End Property
        Dim fDEGREE As String
        <Size(31)>
        Public Property DEGREE() As String
            Get
                Return fDEGREE
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(DEGREE), fDEGREE, value)
            End Set
        End Property
        Dim fMAJOR As String
        <Size(31)>
        Public Property MAJOR() As String
            Get
                Return fMAJOR
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(MAJOR), fMAJOR, value)
            End Set
        End Property
        Dim fGPA As String
        <Size(5)>
        Public Property GPA() As String
            Get
                Return fGPA
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(GPA), fGPA, value)
            End Set
        End Property
        Dim fGPABASE As String
        <Size(3)>
        Public Property GPABASE() As String
            Get
                Return fGPABASE
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(GPABASE), fGPABASE, value)
            End Set
        End Property
        Dim fGRADUATIONYEAR As String
        <Size(5)>
        Public Property GRADUATIONYEAR() As String
            Get
                Return fGRADUATIONYEAR
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(GRADUATIONYEAR), fGRADUATIONYEAR, value)
            End Set
        End Property
        Dim fYEARS As String
        <Size(3)>
        Public Property YEARS() As String
            Get
                Return fYEARS
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(YEARS), fYEARS, value)
            End Set
        End Property
        Dim fNOTEINDX As Decimal
        Public Property NOTEINDX() As Decimal
            Get
                Return fNOTEINDX
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)(NameOf(NOTEINDX), fNOTEINDX, value)
            End Set
        End Property
        Dim fCHANGEBY_I As String
        <Size(15)>
        Public Property CHANGEBY_I() As String
            Get
                Return fCHANGEBY_I
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(CHANGEBY_I), fCHANGEBY_I, value)
            End Set
        End Property
        Dim fCHANGEDATE_I As DateTime
        Public Property CHANGEDATE_I() As DateTime
            Get
                Return fCHANGEDATE_I
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)(NameOf(CHANGEDATE_I), fCHANGEDATE_I, value)
            End Set
        End Property

        Public Structure CompoundKey1Struct
            <Size(15)>
            <Persistent("EMPLOYID")>
            Public Property EMPLOYID As String
            <Persistent("SEQNUMBR")>
            Public Property SEQNUMBR As Integer
        End Structure
        <Key(), Persistent()>
        Public CompoundKey1 As CompoundKey1Struct
    End Class

End Namespace
