'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Xpo.Metadata
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Runtime.CompilerServices
Imports System.Reflection
Namespace Objects.UPR

    <Persistent("UPR00700")>
    Partial Public Class UPREmployeeStateTaxMaster
        Inherits XPLiteObject
        Dim _mTXFLGSTS As String
        <Size(7)>
        Public Property TXFLGSTS() As String
            Get
                Return _mTXFLGSTS
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(TXFLGSTS), _mTXFLGSTS, value)
            End Set
        End Property
        Dim _mEXMFBLND As Byte

        Public Property EXMFBLND() As Byte
            Get
                Return _mEXMFBLND
            End Get
            Set(ByVal value As Byte)
                SetPropertyValue(Of Byte)(NameOf(EXMFBLND), _mEXMFBLND, value)
            End Set
        End Property
        Dim _mEXFBLSPS As Byte

        Public Property EXFBLSPS() As Byte
            Get
                Return _mEXFBLSPS
            End Get
            Set(ByVal value As Byte)
                SetPropertyValue(Of Byte)(NameOf(EXFBLSPS), _mEXFBLSPS, value)
            End Set
        End Property
        Dim _mEXFORO65 As Byte

        Public Property EXFORO65() As Byte
            Get
                Return _mEXFORO65
            End Get
            Set(ByVal value As Byte)
                SetPropertyValue(Of Byte)(NameOf(EXFORO65), _mEXFORO65, value)
            End Set
        End Property
        Dim _mEXMFRSLF As Byte

        Public Property EXMFRSLF() As Byte
            Get
                Return _mEXMFRSLF
            End Get
            Set(ByVal value As Byte)
                SetPropertyValue(Of Byte)(NameOf(EXMFRSLF), _mEXMFRSLF, value)
            End Set
        End Property
        Dim _mEXMFSPAL As Byte

        Public Property EXMFSPAL() As Byte
            Get
                Return _mEXMFSPAL
            End Get
            Set(ByVal value As Byte)
                SetPropertyValue(Of Byte)(NameOf(EXMFSPAL), _mEXMFSPAL, value)
            End Set
        End Property
        Dim _mEXMFRSPS As Byte

        Public Property EXMFRSPS() As Byte
            Get
                Return _mEXMFRSPS
            End Get
            Set(ByVal value As Byte)
                SetPropertyValue(Of Byte)(NameOf(EXMFRSPS), _mEXMFRSPS, value)
            End Set
        End Property
        Dim _mEXFSPO65 As Byte

        Public Property EXFSPO65() As Byte
            Get
                Return _mEXFSPO65
            End Get
            Set(ByVal value As Byte)
                SetPropertyValue(Of Byte)(NameOf(EXFSPO65), _mEXFSPO65, value)
            End Set
        End Property
        Dim _mPRSNEXPT As Short

        Public Property PRSNEXPT() As Short
            Get
                Return _mPRSNEXPT
            End Get
            Set(ByVal value As Short)
                SetPropertyValue(Of Short)(NameOf(PRSNEXPT), _mPRSNEXPT, value)
            End Set
        End Property
        Dim _mDEPNDNTS As Short

        Public Property DEPNDNTS() As Short
            Get
                Return _mDEPNDNTS
            End Get
            Set(ByVal value As Short)
                SetPropertyValue(Of Short)(NameOf(DEPNDNTS), _mDEPNDNTS, value)
            End Set
        End Property
        Dim _mADNLALOW As Short

        Public Property ADNLALOW() As Short
            Get
                Return _mADNLALOW
            End Get
            Set(ByVal value As Short)
                SetPropertyValue(Of Short)(NameOf(ADNLALOW), _mADNLALOW, value)
            End Set
        End Property
        Dim _mESTDEDAL As Short

        Public Property ESTDEDAL() As Short
            Get
                Return _mESTDEDAL
            End Get
            Set(ByVal value As Short)
                SetPropertyValue(Of Short)(NameOf(ESTDEDAL), _mESTDEDAL, value)
            End Set
        End Property
        Dim _mEXMTAMNT As Decimal

        Public Property EXMTAMNT() As Decimal
            Get
                Return _mEXMTAMNT
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)(NameOf(EXMTAMNT), _mEXMTAMNT, value)
            End Set
        End Property
        Dim _mADSTWHDG As Decimal

        Public Property ADSTWHDG() As Decimal
            Get
                Return _mADSTWHDG
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)(NameOf(ADSTWHDG), _mADSTWHDG, value)
            End Set
        End Property
        Dim _mESTSTWHD As Decimal

        Public Property ESTSTWHD() As Decimal
            Get
                Return _mESTSTWHD
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)(NameOf(ESTSTWHD), _mESTSTWHD, value)
            End Set
        End Property
        Dim _mINACTIVE As Byte

        Public Property INACTIVE() As Byte
            Get
                Return _mINACTIVE
            End Get
            Set(ByVal value As Byte)
                SetPropertyValue(Of Byte)(NameOf(INACTIVE), _mINACTIVE, value)
            End Set
        End Property
        Dim _mNOTEINDX As Decimal

        Public Property NOTEINDX() As Decimal
            Get
                Return _mNOTEINDX
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)(NameOf(NOTEINDX), _mNOTEINDX, value)
            End Set
        End Property
        Dim _mDEX_ROW_ID As Integer
        Public Property DEX_ROW_ID() As Integer
            Get
                Return _mDEX_ROW_ID
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)(NameOf(DEX_ROW_ID), _mDEX_ROW_ID, value)
            End Set
        End Property
        Public Structure CompoundKey1Struct
            <Size(15)>
            <Persistent("EMPLOYID")>
            Public Property EMPLOYID As String
            <Size(3)>
            <Persistent("STATECD")>
            Public Property STATECD As String
        End Structure
        <Key(), Persistent()>
        Public CompoundKey1 As CompoundKey1Struct
    End Class

End Namespace
