'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Xpo.Metadata
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Runtime.CompilerServices
Imports System.Reflection
Namespace Objects.UPR

    <Persistent("UPR41700")>
    Partial Public Class UPREmployeeSupervisor
        Inherits XPLiteObject
        Dim fSUPERVISORCODE_I As String
        <Key()>
        <Size(7)>
        Public Property SUPERVISORCODE_I() As String
            Get
                Return fSUPERVISORCODE_I
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(SUPERVISORCODE_I), fSUPERVISORCODE_I, value)
            End Set
        End Property
        Dim fSUPERVISOR As String
        <Size(31)>
        Public Property SUPERVISOR() As String
            Get
                Return fSUPERVISOR
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(SUPERVISOR), fSUPERVISOR, value)
            End Set
        End Property
        Dim fEMPLOYID As String
        <Size(15)>
        Public Property EMPLOYID() As String
            Get
                Return fEMPLOYID
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(EMPLOYID), fEMPLOYID, value)
            End Set
        End Property
        Dim fNOTEINDX As Decimal
        Public Property NOTEINDX() As Decimal
            Get
                Return fNOTEINDX
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)(NameOf(NOTEINDX), fNOTEINDX, value)
            End Set
        End Property
        Dim fCHANGEBY_I As String
        <Size(15)>
        Public Property CHANGEBY_I() As String
            Get
                Return fCHANGEBY_I
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(CHANGEBY_I), fCHANGEBY_I, value)
            End Set
        End Property
        Dim fCHANGEDATE_I As DateTime
        Public Property CHANGEDATE_I() As DateTime
            Get
                Return fCHANGEDATE_I
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)(NameOf(CHANGEDATE_I), fCHANGEDATE_I, value)
            End Set
        End Property
        Dim fDEX_ROW_ID As Integer
        Public Property DEX_ROW_ID() As Integer
            Get
                Return fDEX_ROW_ID
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)(NameOf(DEX_ROW_ID), fDEX_ROW_ID, value)
            End Set
        End Property
    End Class

End Namespace
