'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Xpo.Metadata
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Runtime.CompilerServices
Imports System.Reflection
Namespace Objects.UPR


    Partial Public Class UPREmployeeAddressMaster
        Inherits XPLiteObject
        Dim _mADDRESS1 As String
        <Size(61)>
        Public Property ADDRESS1() As String
            Get
                Return _mADDRESS1
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(ADDRESS1), _mADDRESS1, value)
            End Set
        End Property
        Dim _mADDRESS2 As String
        <Size(61)>
        Public Property ADDRESS2() As String
            Get
                Return _mADDRESS2
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(ADDRESS2), _mADDRESS2, value)
            End Set
        End Property
        Dim _mADDRESS3 As String
        <Size(61)>
        Public Property ADDRESS3() As String
            Get
                Return _mADDRESS3
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(ADDRESS3), _mADDRESS3, value)
            End Set
        End Property
        Dim _mCITY As String
        <Size(35)>
        Public Property CITY() As String
            Get
                Return _mCITY
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(CITY), _mCITY, value)
            End Set
        End Property
        Dim _mSTATE As String
        <Size(29)>
        Public Property STATE() As String
            Get
                Return _mSTATE
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(STATE), _mSTATE, value)
            End Set
        End Property
        Dim _mZIPCODE As String
        <Size(11)>
        Public Property ZIPCODE() As String
            Get
                Return _mZIPCODE
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(ZIPCODE), _mZIPCODE, value)
            End Set
        End Property
        Dim _mCOUNTY As String
        <Size(61)> Public Property COUNTY() As String
            Get
                Return _mCOUNTY
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(COUNTY), _mCOUNTY, value)
            End Set
        End Property
        Dim _mCOUNTRY As String
        <Size(61)> Public Property COUNTRY() As String
            Get
                Return _mCOUNTRY
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(COUNTRY), _mCOUNTRY, value)
            End Set
        End Property
        Dim _mPHONE1 As String
        <Size(21)>
        Public Property PHONE1() As String
            Get
                Return _mPHONE1
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(PHONE1), _mPHONE1, value)
            End Set
        End Property
        Dim _mPHONE2 As String
        <Size(21)>
        Public Property PHONE2() As String
            Get
                Return _mPHONE2
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(PHONE2), _mPHONE2, value)
            End Set
        End Property
        Dim _mPHONE3 As String
        <Size(21)>
        Public Property PHONE3() As String
            Get
                Return _mPHONE3
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(PHONE3), _mPHONE3, value)
            End Set
        End Property
        Dim _mFAX As String
        <Size(21)>
        Public Property FAX() As String
            Get
                Return _mFAX
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(FAX), _mFAX, value)
            End Set
        End Property
        Dim _mForeign_Address As Byte

        Public Property Foreign_Address() As Byte
            Get
                Return _mForeign_Address
            End Get
            Set(ByVal value As Byte)
                SetPropertyValue(Of Byte)(NameOf(Foreign_Address), _mForeign_Address, value)
            End Set
        End Property
        Dim _mForeign_StateProvince As String
        <Size(23)>
        Public Property Foreign_StateProvince() As String
            Get
                Return _mForeign_StateProvince
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(Foreign_StateProvince), _mForeign_StateProvince, value)
            End Set
        End Property
        Dim _mForeign_Postal_Code As String
        <Size(15)>
        Public Property Foreign_Postal_Code() As String
            Get
                Return _mForeign_Postal_Code
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(Foreign_Postal_Code), _mForeign_Postal_Code, value)
            End Set
        End Property
        Dim _mCCode As String
        <Size(7)>
        Public Property CCode() As String
            Get
                Return _mCCode
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(CCode), _mCCode, value)
            End Set
        End Property
        Dim _mDEX_ROW_ID As Integer
        Public Property DEX_ROW_ID() As Integer
            Get
                Return _mDEX_ROW_ID
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)(NameOf(DEX_ROW_ID), _mDEX_ROW_ID, value)
            End Set
        End Property
        Public Structure CompoundKey1Struct
            <Size(15)>
            <Persistent("EMPLOYID")>
            Public Property EMPLOYID As String
            <Size(15)>
            <Persistent("ADRSCODE")>
            Public Property ADRSCODE As String
        End Structure
        <Key(), Persistent()>
        Public CompoundKey1 As CompoundKey1Struct
    End Class

End Namespace
