'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Namespace Objects.SY
    ''' <summary>
    ''' GP Table SY40101
    ''' </summary>
    <Persistent("SY40101")>
    <DefaultProperty("YEAR1")>
    Partial Public Class SYFiscalYear
        Inherits XPLiteObject
        Dim fYEAR1 As Short
        <Key()> _
        Public Property YEAR1() As Short
            Get
                Return fYEAR1
            End Get
            Set(ByVal value As Short)
                SetPropertyValue(Of Short)("YEAR1", fYEAR1, value)
            End Set
        End Property
        Dim fFSTFSCDY As DateTime
        <Indexed(Name:="AK2SY40101", Unique:=True)> _
        Public Property FSTFSCDY() As DateTime
            Get
                Return fFSTFSCDY
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)("FSTFSCDY", fFSTFSCDY, value)
            End Set
        End Property
        Dim fLSTFSCDY As DateTime
        Public Property LSTFSCDY() As DateTime
            Get
                Return fLSTFSCDY
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)("LSTFSCDY", fLSTFSCDY, value)
            End Set
        End Property
        Dim fNUMOFPER As Short
        Public Property NUMOFPER() As Short
            Get
                Return fNUMOFPER
            End Get
            Set(ByVal value As Short)
                SetPropertyValue(Of Short)("NUMOFPER", fNUMOFPER, value)
            End Set
        End Property
        Dim fHISTORYR As Byte
        Public Property HISTORYR() As Byte
            Get
                Return fHISTORYR
            End Get
            Set(ByVal value As Byte)
                SetPropertyValue(Of Byte)("HISTORYR", fHISTORYR, value)
            End Set
        End Property
        Dim fDEX_ROW_ID As Integer
        Public Property DEX_ROW_ID() As Integer
            Get
                Return fDEX_ROW_ID
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)("DEX_ROW_ID", fDEX_ROW_ID, value)
            End Set
        End Property
        Public Sub New(ByVal session As Session)
            MyBase.New(session)
        End Sub
    End Class

End Namespace
