'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Xpo.Metadata
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Runtime.CompilerServices
Imports System.Reflection
Namespace Objects.SOP

    <Persistent("SOP10102")>
    Partial Public Class SOPSalesOrderLineDistribution
        Inherits XPLiteObject
        Dim fDISTTYPE As Short
        Public Property DISTTYPE() As Short
            Get
                Return fDISTTYPE
            End Get
            Set(ByVal value As Short)
                SetPropertyValue(Of Short)(NameOf(DISTTYPE), fDISTTYPE, value)
            End Set
        End Property
        Dim fDistRef As String
        <Size(31)>
        Public Property DistRef() As String
            Get
                Return fDistRef
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(DistRef), fDistRef, value)
            End Set
        End Property
        Dim fACTINDX As Integer
        Public Property ACTINDX() As Integer
            Get
                Return fACTINDX
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)(NameOf(ACTINDX), fACTINDX, value)
            End Set
        End Property
        Dim fDEBITAMT As Decimal
        Public Property DEBITAMT() As Decimal
            Get
                Return fDEBITAMT
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)(NameOf(DEBITAMT), fDEBITAMT, value)
            End Set
        End Property
        Dim fORDBTAMT As Decimal
        Public Property ORDBTAMT() As Decimal
            Get
                Return fORDBTAMT
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)(NameOf(ORDBTAMT), fORDBTAMT, value)
            End Set
        End Property
        Dim fCRDTAMNT As Decimal
        Public Property CRDTAMNT() As Decimal
            Get
                Return fCRDTAMNT
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)(NameOf(CRDTAMNT), fCRDTAMNT, value)
            End Set
        End Property
        Dim fORCRDAMT As Decimal
        Public Property ORCRDAMT() As Decimal
            Get
                Return fORCRDAMT
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)(NameOf(ORCRDAMT), fORCRDAMT, value)
            End Set
        End Property
        Dim fCURRNIDX As Short
        Public Property CURRNIDX() As Short
            Get
                Return fCURRNIDX
            End Get
            Set(ByVal value As Short)
                SetPropertyValue(Of Short)(NameOf(CURRNIDX), fCURRNIDX, value)
            End Set
        End Property
        Dim fTRXSORCE As String
        <Size(13)>
        Public Property TRXSORCE() As String
            Get
                Return fTRXSORCE
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(TRXSORCE), fTRXSORCE, value)
            End Set
        End Property
        Dim fPOSTED As Byte
        Public Property POSTED() As Byte
            Get
                Return fPOSTED
            End Get
            Set(ByVal value As Byte)
                SetPropertyValue(Of Byte)(NameOf(POSTED), fPOSTED, value)
            End Set
        End Property
        Dim fContract_Exchange_Rate As Decimal
        Public Property Contract_Exchange_Rate() As Decimal
            Get
                Return fContract_Exchange_Rate
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)(NameOf(Contract_Exchange_Rate), fContract_Exchange_Rate, value)
            End Set
        End Property

        Public Structure CompoundKey1Struct
            <Persistent("SOPTYPE")>
            Public Property SOPTYPE As Short
            <Size(21)>
            <Persistent("SOPNUMBE")>
            Public Property SOPNUMBE As String
            <Persistent("SEQNUMBR")>
            Public Property SEQNUMBR As Integer
        End Structure
        <Key(), Persistent()>
        Public CompoundKey1 As CompoundKey1Struct
        Public Sub New(ByVal session As Session)
            MyBase.New(session)
        End Sub
    End Class

End Namespace
