'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Xpo.Metadata
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Runtime.CompilerServices
Imports System.Reflection
Namespace Objects.UPR

    <Indices("DEPRTMNT;EMPLOYID", "JOBTITLE;EMPLOYID", "EMPLOYID;LASTNAME;EMPLCLAS;DEPRTMNT;INACTIVE")>
    <Persistent("UPR00100")>
    Partial Public Class UPREmployeeMaster
        Inherits XPLiteObject
        Dim _mEMPLOYID As String
        <Key()>
        <Size(15)>
        Public Property EMPLOYID() As String
            Get
                Return _mEMPLOYID
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(EMPLOYID), _mEMPLOYID, value)
            End Set
        End Property
        Dim _mEMPLCLAS As String
        <Indexed("EMPLOYID", Name:="AK4UPR00100", Unique:=True)>
        <Size(15)>
        Public Property EMPLCLAS() As String
            Get
                Return _mEMPLCLAS
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(EMPLCLAS), _mEMPLCLAS, value)
            End Set
        End Property
        Dim _mINACTIVE As Byte

        Public Property INACTIVE() As Byte
            Get
                Return _mINACTIVE
            End Get
            Set(ByVal value As Byte)
                SetPropertyValue(Of Byte)(NameOf(INACTIVE), _mINACTIVE, value)
            End Set
        End Property
        Dim _mLASTNAME As String
        <Indexed("FRSTNAME;MIDLNAME;EMPLOYID", Name:="AK2UPR00100", Unique:=True)>
        <Size(21)>
        Public Property LASTNAME() As String
            Get
                Return _mLASTNAME
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(LASTNAME), _mLASTNAME, value)
            End Set
        End Property
        Dim _mFRSTNAME As String
        <Size(15)>
        Public Property FRSTNAME() As String
            Get
                Return _mFRSTNAME
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(FRSTNAME), _mFRSTNAME, value)
            End Set
        End Property
        Dim _mMIDLNAME As String
        <Size(15)>
        Public Property MIDLNAME() As String
            Get
                Return _mMIDLNAME
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(MIDLNAME), _mMIDLNAME, value)
            End Set
        End Property
        Dim _mADRSCODE As String
        <Size(15)>
        Public Property ADRSCODE() As String
            Get
                Return _mADRSCODE
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(ADRSCODE), _mADRSCODE, value)
            End Set
        End Property
        Dim _mSOCSCNUM As String
        <Indexed("DEX_ROW_ID", Name:="AK8UPR00100", Unique:=True)>
        <Size(15)>
        Public Property SOCSCNUM() As String
            Get
                Return _mSOCSCNUM
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(SOCSCNUM), _mSOCSCNUM, value)
            End Set
        End Property
        Dim _mBRTHDATE As DateTime

        Public Property BRTHDATE() As DateTime
            Get
                Return _mBRTHDATE
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)(NameOf(BRTHDATE), _mBRTHDATE, value)
            End Set
        End Property
        Dim _mGENDER As Short

        Public Property GENDER() As Short
            Get
                Return _mGENDER
            End Get
            Set(ByVal value As Short)
                SetPropertyValue(Of Short)(NameOf(GENDER), _mGENDER, value)
            End Set
        End Property
        Dim _mETHNORGN As Short

        Public Property ETHNORGN() As Short
            Get
                Return _mETHNORGN
            End Get
            Set(ByVal value As Short)
                SetPropertyValue(Of Short)(NameOf(ETHNORGN), _mETHNORGN, value)
            End Set
        End Property
        Dim _mCalc_Min_Wage_Bal As Byte

        Public Property Calc_Min_Wage_Bal() As Byte
            Get
                Return _mCalc_Min_Wage_Bal
            End Get
            Set(ByVal value As Byte)
                SetPropertyValue(Of Byte)(NameOf(Calc_Min_Wage_Bal), _mCalc_Min_Wage_Bal, value)
            End Set
        End Property
        Dim _mDIVISIONCODE_I As String
        <Indexed("DEPRTMNT;JOBTITLE;EMPLOYID", Name:="AK10UPR00100", Unique:=True)>
        <Size(7)>
        Public Property DIVISIONCODE_I() As String
            Get
                Return _mDIVISIONCODE_I
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(DIVISIONCODE_I), _mDIVISIONCODE_I, value)
            End Set
        End Property
        Dim _mDEPRTMNT As String
        <Size(7)>
        Public Property DEPRTMNT() As String
            Get
                Return _mDEPRTMNT
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(DEPRTMNT), _mDEPRTMNT, value)
            End Set
        End Property
        Dim _mJOBTITLE As String
        <Size(7)>
        Public Property JOBTITLE() As String
            Get
                Return _mJOBTITLE
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(JOBTITLE), _mJOBTITLE, value)
            End Set
        End Property
        Dim _mSUPERVISORCODE_I As String
        <Indexed("DEX_ROW_ID", Name:="AK11UPR00100", Unique:=True)>
        <Size(7)>
        Public Property SUPERVISORCODE_I() As String
            Get
                Return _mSUPERVISORCODE_I
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(SUPERVISORCODE_I), _mSUPERVISORCODE_I, value)
            End Set
        End Property
        Dim _mLOCATNID As String
        <Indexed("DEX_ROW_ID", Name:="AK12UPR00100", Unique:=True)>
        <Size(15)>
        Public Property LOCATNID() As String
            Get
                Return _mLOCATNID
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(LOCATNID), _mLOCATNID, value)
            End Set
        End Property
        Dim _mWCACFPAY As Short

        Public Property WCACFPAY() As Short
            Get
                Return _mWCACFPAY
            End Get
            Set(ByVal value As Short)
                SetPropertyValue(Of Short)(NameOf(WCACFPAY), _mWCACFPAY, value)
            End Set
        End Property
        Dim _mACTINDX As Integer

        Public Property ACTINDX() As Integer
            Get
                Return _mACTINDX
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)(NameOf(ACTINDX), _mACTINDX, value)
            End Set
        End Property
        Dim _mWKHRPRYR As Short

        Public Property WKHRPRYR() As Short
            Get
                Return _mWKHRPRYR
            End Get
            Set(ByVal value As Short)
                SetPropertyValue(Of Short)(NameOf(WKHRPRYR), _mWKHRPRYR, value)
            End Set
        End Property
        Dim _mSTRTDATE As DateTime

        Public Property STRTDATE() As DateTime
            Get
                Return _mSTRTDATE
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)(NameOf(STRTDATE), _mSTRTDATE, value)
            End Set
        End Property
        Dim _mDEMPINAC As DateTime

        Public Property DEMPINAC() As DateTime
            Get
                Return _mDEMPINAC
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)(NameOf(DEMPINAC), _mDEMPINAC, value)
            End Set
        End Property
        Dim _mRSNEMPIN As String
        <Size(31)>
        Public Property RSNEMPIN() As String
            Get
                Return _mRSNEMPIN
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(RSNEMPIN), _mRSNEMPIN, value)
            End Set
        End Property
        Dim _mMINETPAY As Decimal

        Public Property MINETPAY() As Decimal
            Get
                Return _mMINETPAY
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)(NameOf(MINETPAY), _mMINETPAY, value)
            End Set
        End Property
        Dim _mSUTASTAT As String
        <Size(3)>
        Public Property SUTASTAT() As String
            Get
                Return _mSUTASTAT
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(SUTASTAT), _mSUTASTAT, value)
            End Set
        End Property
        Dim _mWRKRCOMP As String
        <Indexed("EMPLOYID", Name:="AK7UPR00100", Unique:=True)>
        <Size(7)>
        Public Property WRKRCOMP() As String
            Get
                Return _mWRKRCOMP
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(WRKRCOMP), _mWRKRCOMP, value)
            End Set
        End Property
        Dim _mATACRVAC As Byte

        Public Property ATACRVAC() As Byte
            Get
                Return _mATACRVAC
            End Get
            Set(ByVal value As Byte)
                SetPropertyValue(Of Byte)(NameOf(ATACRVAC), _mATACRVAC, value)
            End Set
        End Property
        Dim _mVACCRAMT As Integer

        Public Property VACCRAMT() As Integer
            Get
                Return _mVACCRAMT
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)(NameOf(VACCRAMT), _mVACCRAMT, value)
            End Set
        End Property
        Dim _mVACCRMTH As Short

        Public Property VACCRMTH() As Short
            Get
                Return _mVACCRMTH
            End Get
            Set(ByVal value As Short)
                SetPropertyValue(Of Short)(NameOf(VACCRMTH), _mVACCRMTH, value)
            End Set
        End Property
        Dim _mVACAPRYR As Integer

        Public Property VACAPRYR() As Integer
            Get
                Return _mVACAPRYR
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)(NameOf(VACAPRYR), _mVACAPRYR, value)
            End Set
        End Property
        Dim _mVACAVLBL As Integer

        Public Property VACAVLBL() As Integer
            Get
                Return _mVACAVLBL
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)(NameOf(VACAVLBL), _mVACAVLBL, value)
            End Set
        End Property
        Dim _mWRNVCNFLSBLWZR As Byte

        Public Property WRNVCNFLSBLWZR() As Byte
            Get
                Return _mWRNVCNFLSBLWZR
            End Get
            Set(ByVal value As Byte)
                SetPropertyValue(Of Byte)(NameOf(WRNVCNFLSBLWZR), _mWRNVCNFLSBLWZR, value)
            End Set
        End Property
        Dim _mATACRSTM As Byte

        Public Property ATACRSTM() As Byte
            Get
                Return _mATACRSTM
            End Get
            Set(ByVal value As Byte)
                SetPropertyValue(Of Byte)(NameOf(ATACRSTM), _mATACRSTM, value)
            End Set
        End Property
        Dim _mSTMACMTH As Short

        Public Property STMACMTH() As Short
            Get
                Return _mSTMACMTH
            End Get
            Set(ByVal value As Short)
                SetPropertyValue(Of Short)(NameOf(STMACMTH), _mSTMACMTH, value)
            End Set
        End Property
        Dim _mSKTMACAM As Integer

        Public Property SKTMACAM() As Integer
            Get
                Return _mSKTMACAM
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)(NameOf(SKTMACAM), _mSKTMACAM, value)
            End Set
        End Property
        Dim _mSIKTIMAV As Integer

        Public Property SIKTIMAV() As Integer
            Get
                Return _mSIKTIMAV
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)(NameOf(SIKTIMAV), _mSIKTIMAV, value)
            End Set
        End Property
        Dim _mSKTMHPYR As Integer

        Public Property SKTMHPYR() As Integer
            Get
                Return _mSKTMHPYR
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)(NameOf(SKTMHPYR), _mSKTMHPYR, value)
            End Set
        End Property
        Dim _mWRNSTFLSBLWZR As Byte

        Public Property WRNSTFLSBLWZR() As Byte
            Get
                Return _mWRNSTFLSBLWZR
            End Get
            Set(ByVal value As Byte)
                SetPropertyValue(Of Byte)(NameOf(WRNSTFLSBLWZR), _mWRNSTFLSBLWZR, value)
            End Set
        End Property
        Dim _mUSERDEF1 As String
        <Size(21)>
        Public Property USERDEF1() As String
            Get
                Return _mUSERDEF1
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(USERDEF1), _mUSERDEF1, value)
            End Set
        End Property
        Dim _mUSERDEF2 As String
        <Size(21)>
        Public Property USERDEF2() As String
            Get
                Return _mUSERDEF2
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(USERDEF2), _mUSERDEF2, value)
            End Set
        End Property
        Dim _mEMPLOYMENTTYPE As Short

        Public Property EMPLOYMENTTYPE() As Short
            Get
                Return _mEMPLOYMENTTYPE
            End Get
            Set(ByVal value As Short)
                SetPropertyValue(Of Short)(NameOf(EMPLOYMENTTYPE), _mEMPLOYMENTTYPE, value)
            End Set
        End Property
        Dim _mMARITALSTATUS As Short

        Public Property MARITALSTATUS() As Short
            Get
                Return _mMARITALSTATUS
            End Get
            Set(ByVal value As Short)
                SetPropertyValue(Of Short)(NameOf(MARITALSTATUS), _mMARITALSTATUS, value)
            End Set
        End Property
        Dim _mBENADJDATE As DateTime

        Public Property BENADJDATE() As DateTime
            Get
                Return _mBENADJDATE
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)(NameOf(BENADJDATE), _mBENADJDATE, value)
            End Set
        End Property
        Dim _mLASTDAYWORKED_I As DateTime

        Public Property LASTDAYWORKED_I() As DateTime
            Get
                Return _mLASTDAYWORKED_I
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)(NameOf(LASTDAYWORKED_I), _mLASTDAYWORKED_I, value)
            End Set
        End Property
        Dim _mBIRTHDAY As Short

        Public Property BIRTHDAY() As Short
            Get
                Return _mBIRTHDAY
            End Get
            Set(ByVal value As Short)
                SetPropertyValue(Of Short)(NameOf(BIRTHDAY), _mBIRTHDAY, value)
            End Set
        End Property
        Dim _mBIRTHMONTH As Short

        Public Property BIRTHMONTH() As Short
            Get
                Return _mBIRTHMONTH
            End Get
            Set(ByVal value As Short)
                SetPropertyValue(Of Short)(NameOf(BIRTHMONTH), _mBIRTHMONTH, value)
            End Set
        End Property
        Dim _mSPOUSE As String
        <Size(15)>
        Public Property SPOUSE() As String
            Get
                Return _mSPOUSE
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(SPOUSE), _mSPOUSE, value)
            End Set
        End Property
        Dim _mSPOUSESSN As String
        <Size(15)>
        Public Property SPOUSESSN() As String
            Get
                Return _mSPOUSESSN
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(SPOUSESSN), _mSPOUSESSN, value)
            End Set
        End Property
        Dim _mNICKNAME As String
        <Size(21)>
        Public Property NICKNAME() As String
            Get
                Return _mNICKNAME
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(NICKNAME), _mNICKNAME, value)
            End Set
        End Property
        Dim _mALTERNATENAME As String
        <Size(21)>
        Public Property ALTERNATENAME() As String
            Get
                Return _mALTERNATENAME
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(ALTERNATENAME), _mALTERNATENAME, value)
            End Set
        End Property
        Dim _mHRSTATUS As Short

        Public Property HRSTATUS() As Short
            Get
                Return _mHRSTATUS
            End Get
            Set(ByVal value As Short)
                SetPropertyValue(Of Short)(NameOf(HRSTATUS), _mHRSTATUS, value)
            End Set
        End Property
        Dim _mDATEOFLASTREVIEW_I As DateTime

        Public Property DATEOFLASTREVIEW_I() As DateTime
            Get
                Return _mDATEOFLASTREVIEW_I
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)(NameOf(DATEOFLASTREVIEW_I), _mDATEOFLASTREVIEW_I, value)
            End Set
        End Property
        Dim _mDATEOFNEXTREVIEW_I As DateTime

        Public Property DATEOFNEXTREVIEW_I() As DateTime
            Get
                Return _mDATEOFNEXTREVIEW_I
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)(NameOf(DATEOFNEXTREVIEW_I), _mDATEOFNEXTREVIEW_I, value)
            End Set
        End Property
        Dim _mBENEFITEXPIRE_I As DateTime

        Public Property BENEFITEXPIRE_I() As DateTime
            Get
                Return _mBENEFITEXPIRE_I
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)(NameOf(BENEFITEXPIRE_I), _mBENEFITEXPIRE_I, value)
            End Set
        End Property
        Dim _mHANDICAPPED As Byte

        Public Property HANDICAPPED() As Byte
            Get
                Return _mHANDICAPPED
            End Get
            Set(ByVal value As Byte)
                SetPropertyValue(Of Byte)(NameOf(HANDICAPPED), _mHANDICAPPED, value)
            End Set
        End Property
        Dim _mVETERAN As Byte

        Public Property VETERAN() As Byte
            Get
                Return _mVETERAN
            End Get
            Set(ByVal value As Byte)
                SetPropertyValue(Of Byte)(NameOf(VETERAN), _mVETERAN, value)
            End Set
        End Property
        Dim _mVIETNAMVETERAN As Byte

        Public Property VIETNAMVETERAN() As Byte
            Get
                Return _mVIETNAMVETERAN
            End Get
            Set(ByVal value As Byte)
                SetPropertyValue(Of Byte)(NameOf(VIETNAMVETERAN), _mVIETNAMVETERAN, value)
            End Set
        End Property
        Dim _mDISABLEDVETERAN As Byte

        Public Property DISABLEDVETERAN() As Byte
            Get
                Return _mDISABLEDVETERAN
            End Get
            Set(ByVal value As Byte)
                SetPropertyValue(Of Byte)(NameOf(DISABLEDVETERAN), _mDISABLEDVETERAN, value)
            End Set
        End Property
        Dim _mUNIONEMPLOYEE As Byte

        Public Property UNIONEMPLOYEE() As Byte
            Get
                Return _mUNIONEMPLOYEE
            End Get
            Set(ByVal value As Byte)
                SetPropertyValue(Of Byte)(NameOf(UNIONEMPLOYEE), _mUNIONEMPLOYEE, value)
            End Set
        End Property
        Dim _mSMOKER_I As Byte

        Public Property SMOKER_I() As Byte
            Get
                Return _mSMOKER_I
            End Get
            Set(ByVal value As Byte)
                SetPropertyValue(Of Byte)(NameOf(SMOKER_I), _mSMOKER_I, value)
            End Set
        End Property
        Dim _mCITIZEN As Byte

        Public Property CITIZEN() As Byte
            Get
                Return _mCITIZEN
            End Get
            Set(ByVal value As Byte)
                SetPropertyValue(Of Byte)(NameOf(CITIZEN), _mCITIZEN, value)
            End Set
        End Property
        Dim _mVERIFIED As Byte

        Public Property VERIFIED() As Byte
            Get
                Return _mVERIFIED
            End Get
            Set(ByVal value As Byte)
                SetPropertyValue(Of Byte)(NameOf(VERIFIED), _mVERIFIED, value)
            End Set
        End Property
        Dim _mI9RENEW As DateTime

        Public Property I9RENEW() As DateTime
            Get
                Return _mI9RENEW
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)(NameOf(I9RENEW), _mI9RENEW, value)
            End Set
        End Property
        Dim _mPrimary_Pay_Record As String
        <Size(7)>
        Public Property Primary_Pay_Record() As String
            Get
                Return _mPrimary_Pay_Record
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(Primary_Pay_Record), _mPrimary_Pay_Record, value)
            End Set
        End Property
        Dim _mCHANGEBY_I As String
        <Size(15)>
        Public Property CHANGEBY_I() As String
            Get
                Return _mCHANGEBY_I
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(CHANGEBY_I), _mCHANGEBY_I, value)
            End Set
        End Property
        Dim _mCHANGEDATE_I As DateTime

        Public Property CHANGEDATE_I() As DateTime
            Get
                Return _mCHANGEDATE_I
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)(NameOf(CHANGEDATE_I), _mCHANGEDATE_I, value)
            End Set
        End Property
        Dim _mNOTEINDX As Decimal

        Public Property NOTEINDX() As Decimal
            Get
                Return _mNOTEINDX
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)(NameOf(NOTEINDX), _mNOTEINDX, value)
            End Set
        End Property
        Dim _mNOTEINDX2 As Decimal

        Public Property NOTEINDX2() As Decimal
            Get
                Return _mNOTEINDX2
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)(NameOf(NOTEINDX2), _mNOTEINDX2, value)
            End Set
        End Property
        Dim _mUNIONCD As String
        <Size(7)>
        Public Property UNIONCD() As String
            Get
                Return _mUNIONCD
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(UNIONCD), _mUNIONCD, value)
            End Set
        End Property
        Dim _mRATECLSS As String
        <Size(15)>
        Public Property RATECLSS() As String
            Get
                Return _mRATECLSS
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(RATECLSS), _mRATECLSS, value)
            End Set
        End Property
        Dim _mFEDCLSSCD As String
        <Size(11)>
        Public Property FEDCLSSCD() As String
            Get
                Return _mFEDCLSSCD
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(FEDCLSSCD), _mFEDCLSSCD, value)
            End Set
        End Property
        Dim _mOTHERVET As Byte

        Public Property OTHERVET() As Byte
            Get
                Return _mOTHERVET
            End Get
            Set(ByVal value As Byte)
                SetPropertyValue(Of Byte)(NameOf(OTHERVET), _mOTHERVET, value)
            End Set
        End Property
        Dim _mMilitary_Discharge_Date As DateTime

        Public Property Military_Discharge_Date() As DateTime
            Get
                Return _mMilitary_Discharge_Date
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)(NameOf(Military_Discharge_Date), _mMilitary_Discharge_Date, value)
            End Set
        End Property
        Dim _mEMPLSUFF As String
        <Size(5)>
        Public Property EMPLSUFF() As String
            Get
                Return _mEMPLSUFF
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(EMPLSUFF), _mEMPLSUFF, value)
            End Set
        End Property
        Dim _mSTATUSCD As String
        <Size(15)>
        Public Property STATUSCD() As String
            Get
                Return _mSTATUSCD
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(STATUSCD), _mSTATUSCD, value)
            End Set
        End Property
        Dim _mWorkflow_Approval_Status As Short

        Public Property Workflow_Approval_Status() As Short
            Get
                Return _mWorkflow_Approval_Status
            End Get
            Set(ByVal value As Short)
                SetPropertyValue(Of Short)(NameOf(Workflow_Approval_Status), _mWorkflow_Approval_Status, value)
            End Set
        End Property
        Dim _mWorkflow_Priority As Short

        Public Property Workflow_Priority() As Short
            Get
                Return _mWorkflow_Priority
            End Get
            Set(ByVal value As Short)
                SetPropertyValue(Of Short)(NameOf(Workflow_Priority), _mWorkflow_Priority, value)
            End Set
        End Property
        Dim _mWorkflow_Status As Short

        Public Property Workflow_Status() As Short
            Get
                Return _mWorkflow_Status
            End Get
            Set(ByVal value As Short)
                SetPropertyValue(Of Short)(NameOf(Workflow_Status), _mWorkflow_Status, value)
            End Set
        End Property
        Dim _mAFSMVET As Byte

        Public Property AFSMVET() As Byte
            Get
                Return _mAFSMVET
            End Get
            Set(ByVal value As Byte)
                SetPropertyValue(Of Byte)(NameOf(AFSMVET), _mAFSMVET, value)
            End Set
        End Property
        Dim _mRECSEPVET As Byte

        Public Property RECSEPVET() As Byte
            Get
                Return _mRECSEPVET
            End Get
            Set(ByVal value As Byte)
                SetPropertyValue(Of Byte)(NameOf(RECSEPVET), _mRECSEPVET, value)
            End Set
        End Property
        Dim _mUSERID As String
        <Indexed("DEX_ROW_ID", Name:="AK13UPR00100", Unique:=True)>
        <Size(15)>
        Public Property USERID() As String
            Get
                Return _mUSERID
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(USERID), _mUSERID, value)
            End Set
        End Property
        Dim _mDEX_ROW_TS As DateTime

        Public Property DEX_ROW_TS() As DateTime
            Get
                Return _mDEX_ROW_TS
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)(NameOf(DEX_ROW_TS), _mDEX_ROW_TS, value)
            End Set
        End Property
        Dim _mDEX_ROW_ID As Integer
        Public Property DEX_ROW_ID() As Integer
            Get
                Return _mDEX_ROW_ID
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)(NameOf(DEX_ROW_ID), _mDEX_ROW_ID, value)
            End Set
        End Property
    End Class

End Namespace
