'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Xpo.Metadata
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Runtime.CompilerServices
Imports System.Reflection
Namespace Objects.SY

    <Persistent("SY00600")>
    Partial Public Class SYCompanyLocation
        Inherits XPLiteObject
        Dim fLOCATNNM As String
        <Size(31)>
        Public Property LOCATNNM() As String
            Get
                Return fLOCATNNM
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(LOCATNNM), fLOCATNNM, value)
            End Set
        End Property
        Dim fADRSCODE As String
        <Size(15)>
        Public Property ADRSCODE() As String
            Get
                Return fADRSCODE
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(ADRSCODE), fADRSCODE, value)
            End Set
        End Property
        Dim fADRCNTCT As String
        <Size(61)>
        Public Property ADRCNTCT() As String
            Get
                Return fADRCNTCT
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(ADRCNTCT), fADRCNTCT, value)
            End Set
        End Property
        Dim fADDRESS1 As String
        <Size(61)>
        Public Property ADDRESS1() As String
            Get
                Return fADDRESS1
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(ADDRESS1), fADDRESS1, value)
            End Set
        End Property
        Dim fADDRESS2 As String
        <Size(61)>
        Public Property ADDRESS2() As String
            Get
                Return fADDRESS2
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(ADDRESS2), fADDRESS2, value)
            End Set
        End Property
        Dim fADDRESS3 As String
        <Size(61)>
        Public Property ADDRESS3() As String
            Get
                Return fADDRESS3
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(ADDRESS3), fADDRESS3, value)
            End Set
        End Property
        Dim fCITY As String
        <Size(35)>
        Public Property CITY() As String
            Get
                Return fCITY
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(CITY), fCITY, value)
            End Set
        End Property
        Dim fCOUNTY As String
        <Size(61)>
        Public Property COUNTY() As String
            Get
                Return fCOUNTY
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(COUNTY), fCOUNTY, value)
            End Set
        End Property
        Dim fSTATE As String
        <Size(29)>
        Public Property STATE() As String
            Get
                Return fSTATE
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(STATE), fSTATE, value)
            End Set
        End Property
        Dim fZIPCODE As String
        <Size(11)>
        Public Property ZIPCODE() As String
            Get
                Return fZIPCODE
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(ZIPCODE), fZIPCODE, value)
            End Set
        End Property
        Dim fCOUNTRY As String
        <Size(61)>
        Public Property COUNTRY() As String
            Get
                Return fCOUNTRY
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(COUNTRY), fCOUNTRY, value)
            End Set
        End Property
        Dim fPHONE1 As String
        <Size(21)>
        Public Property PHONE1() As String
            Get
                Return fPHONE1
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(PHONE1), fPHONE1, value)
            End Set
        End Property
        Dim fPHONE2 As String
        <Size(21)>
        Public Property PHONE2() As String
            Get
                Return fPHONE2
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(PHONE2), fPHONE2, value)
            End Set
        End Property
        Dim fPHONE3 As String
        <Size(21)>
        Public Property PHONE3() As String
            Get
                Return fPHONE3
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(PHONE3), fPHONE3, value)
            End Set
        End Property
        Dim fFAXNUMBR As String
        <Size(21)>
        Public Property FAXNUMBR() As String
            Get
                Return fFAXNUMBR
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(FAXNUMBR), fFAXNUMBR, value)
            End Set
        End Property
        Dim fCHANGEBY_I As String
        <Size(15)>
        Public Property CHANGEBY_I() As String
            Get
                Return fCHANGEBY_I
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(CHANGEBY_I), fCHANGEBY_I, value)
            End Set
        End Property
        Dim fCHANGEDATE_I As DateTime
        Public Property CHANGEDATE_I() As DateTime
            Get
                Return fCHANGEDATE_I
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)(NameOf(CHANGEDATE_I), fCHANGEDATE_I, value)
            End Set
        End Property
        Dim fNOTEINDX As Decimal
        Public Property NOTEINDX() As Decimal
            Get
                Return fNOTEINDX
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)(NameOf(NOTEINDX), fNOTEINDX, value)
            End Set
        End Property
        Dim fCCode As String
        <Size(7)>
        Public Property CCode() As String
            Get
                Return fCCode
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(CCode), fCCode, value)
            End Set
        End Property
        Dim fDEX_ROW_ID As Integer
        Public Property DEX_ROW_ID() As Integer
            Get
                Return fDEX_ROW_ID
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)(NameOf(DEX_ROW_ID), fDEX_ROW_ID, value)
            End Set
        End Property
        Public Structure CompoundKey1Struct
            <Persistent("CMPANYID")>
            Public Property CMPANYID As Short
            <Size(15)>
            <Persistent("LOCATNID")>
            Public Property LOCATNID As String
        End Structure
        <Key(), Persistent()>
        Public CompoundKey1 As CompoundKey1Struct
    End Class

End Namespace
