'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Namespace Objects.SY


    <Indices("CompoundKey1;PERNAME;DEX_ROW_ID", "CompoundKey1;PERIODDT;DEX_ROW_ID")>
    <Persistent("SY40100")>
    Partial Public Class SYFiscalYearDetail
        Inherits XPLiteObject
        Dim fCLOSED As Byte
        Public Property CLOSED() As Byte
            Get
                Return fCLOSED
            End Get
            Set(ByVal value As Byte)
                SetPropertyValue(Of Byte)("CLOSED", fCLOSED, value)
            End Set
        End Property
        Dim fPERIODDT As DateTime
        Public Property PERIODDT() As DateTime
            Get
                Return fPERIODDT
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)("PERIODDT", fPERIODDT, value)
            End Set
        End Property
        Dim fPERNAME As String
        <Size(21)>
        Public Property PERNAME() As String
            Get
                Return fPERNAME
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("PERNAME", fPERNAME, value)
            End Set
        End Property
        Dim fPSERIES_1 As Byte
        Public Property PSERIES_1() As Byte
            Get
                Return fPSERIES_1
            End Get
            Set(ByVal value As Byte)
                SetPropertyValue(Of Byte)("PSERIES_1", fPSERIES_1, value)
            End Set
        End Property
        Dim fPSERIES_2 As Byte
        Public Property PSERIES_2() As Byte
            Get
                Return fPSERIES_2
            End Get
            Set(ByVal value As Byte)
                SetPropertyValue(Of Byte)("PSERIES_2", fPSERIES_2, value)
            End Set
        End Property
        Dim fPSERIES_3 As Byte
        Public Property PSERIES_3() As Byte
            Get
                Return fPSERIES_3
            End Get
            Set(ByVal value As Byte)
                SetPropertyValue(Of Byte)("PSERIES_3", fPSERIES_3, value)
            End Set
        End Property
        Dim fPSERIES_4 As Byte
        Public Property PSERIES_4() As Byte
            Get
                Return fPSERIES_4
            End Get
            Set(ByVal value As Byte)
                SetPropertyValue(Of Byte)("PSERIES_4", fPSERIES_4, value)
            End Set
        End Property
        Dim fPSERIES_5 As Byte
        Public Property PSERIES_5() As Byte
            Get
                Return fPSERIES_5
            End Get
            Set(ByVal value As Byte)
                SetPropertyValue(Of Byte)("PSERIES_5", fPSERIES_5, value)
            End Set
        End Property
        Dim fPSERIES_6 As Byte
        Public Property PSERIES_6() As Byte
            Get
                Return fPSERIES_6
            End Get
            Set(ByVal value As Byte)
                SetPropertyValue(Of Byte)("PSERIES_6", fPSERIES_6, value)
            End Set
        End Property
        Dim fPERDENDT As DateTime
        Public Property PERDENDT() As DateTime
            Get
                Return fPERDENDT
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)("PERDENDT", fPERDENDT, value)
            End Set
        End Property
        Dim fDEX_ROW_TS As DateTime
        Public Property DEX_ROW_TS() As DateTime
            Get
                Return fDEX_ROW_TS
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)("DEX_ROW_TS", fDEX_ROW_TS, value)
            End Set
        End Property
        Dim fDEX_ROW_ID As Integer
        Public Property DEX_ROW_ID() As Integer
            Get
                Return fDEX_ROW_ID
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)("DEX_ROW_ID", fDEX_ROW_ID, value)
            End Set
        End Property
        Public Structure CompoundKey1Struct
            <Persistent("SERIES")>
            Public Property SERIES As Short
            <Size(51)>
            <Persistent("ODESCTN")>
            Public Property ODESCTN As String
            <Persistent("FORIGIN")>
            Public Property FORIGIN As Byte
            <Persistent("PERIODID")>
            Public Property PERIODID As Short
            <Persistent("YEAR1")>
            Public Property YEAR1 As Short
        End Structure
        <Indexed(Name:="AK2SY40100", Unique:=True)>
        <Key(), Persistent()>
        Public CompoundKey1 As CompoundKey1Struct
    End Class

End Namespace
