'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Namespace Objects.CN
    Partial Public Class ActionDefinition
        Inherits XPLiteObject
        Dim fAction_Promised As String
        <Key()>
        <Size(17)>
        Public Property Action_Promised() As String
            Get
                Return fAction_Promised
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Action_Promised", fAction_Promised, value)
            End Set
        End Property
        Dim fAction_Promised_Descripti As String
        <Size(31)>
        Public Property Action_Promised_Descripti() As String
            Get
                Return fAction_Promised_Descripti
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Action_Promised_Descripti", fAction_Promised_Descripti, value)
            End Set
        End Property
        Dim fAction_Completed As Byte
        Public Property Action_Completed() As Byte
            Get
                Return fAction_Completed
            End Get
            Set(ByVal value As Byte)
                SetPropertyValue(Of Byte)("Action_Completed", fAction_Completed, value)
            End Set
        End Property
        Dim fActionType As Short
        <Indexed("Action_Promised", Name:="AK2CN00200", Unique:=True)>
        Public Property ActionType() As Short
            Get
                Return fActionType
            End Get
            Set(ByVal value As Short)
                SetPropertyValue(Of Short)("ActionType", fActionType, value)
            End Set
        End Property
        Dim fFollowupActionDays As Short
        Public Property FollowupActionDays() As Short
            Get
                Return fFollowupActionDays
            End Get
            Set(ByVal value As Short)
                SetPropertyValue(Of Short)("FollowupActionDays", fFollowupActionDays, value)
            End Set
        End Property
        Dim fUSERDEF1 As String
        <Size(21)>
        Public Property USERDEF1() As String
            Get
                Return fUSERDEF1
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("USERDEF1", fUSERDEF1, value)
            End Set
        End Property
        Dim fUSERDEF2 As String
        <Size(21)>
        Public Property USERDEF2() As String
            Get
                Return fUSERDEF2
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("USERDEF2", fUSERDEF2, value)
            End Set
        End Property
        Dim fDEX_ROW_ID As Integer
        Public Property DEX_ROW_ID() As Integer
            Get
                Return fDEX_ROW_ID
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)("DEX_ROW_ID", fDEX_ROW_ID, value)
            End Set
        End Property
    End Class

End Namespace
