'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Namespace Objects.CN


    Partial Public Class NoteHeader
        Inherits XPLiteObject
        Dim fCUSTNMBR As String

        <Size(15)>
        Public Property CUSTNMBR() As String
            Get
                Return fCUSTNMBR
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("CUSTNMBR", fCUSTNMBR, value)
            End Set
        End Property
        Dim fCPRCSTNM As String

        <Size(15)>
        Public Property CPRCSTNM() As String
            Get
                Return fCPRCSTNM
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("CPRCSTNM", fCPRCSTNM, value)
            End Set
        End Property
        Dim fDATE1 As DateTime
        Public Property DATE1() As DateTime
            Get
                Return fDATE1
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)("DATE1", fDATE1, value)
            End Set
        End Property
        Dim fContact_Date As DateTime
        Public Property Contact_Date() As DateTime
            Get
                Return fContact_Date
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)("Contact_Date", fContact_Date, value)
            End Set
        End Property
        Dim fTIME1 As DateTime
        Public Property TIME1() As DateTime
            Get
                Return fTIME1
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)("TIME1", fTIME1, value)
            End Set
        End Property
        Dim fContact_Time As DateTime
        Public Property Contact_Time() As DateTime
            Get
                Return fContact_Time
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)("Contact_Time", fContact_Time, value)
            End Set
        End Property
        Dim fNOTEINDX As Decimal
        <Key()>
        Public Property NOTEINDX() As Decimal
            Get
                Return fNOTEINDX
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)("NOTEINDX", fNOTEINDX, value)
            End Set
        End Property
        Dim fRevisionNumber As Short
        Public Property RevisionNumber() As Short
            Get
                Return fRevisionNumber
            End Get
            Set(ByVal value As Short)
                SetPropertyValue(Of Short)("RevisionNumber", fRevisionNumber, value)
            End Set
        End Property
        Dim fCN_Group_Note As Byte
        Public Property CN_Group_Note() As Byte
            Get
                Return fCN_Group_Note
            End Get
            Set(ByVal value As Byte)
                SetPropertyValue(Of Byte)("CN_Group_Note", fCN_Group_Note, value)
            End Set
        End Property
        Dim fCaller_ID_String As String
        <Size(15)>
        Public Property Caller_ID_String() As String
            Get
                Return fCaller_ID_String
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Caller_ID_String", fCaller_ID_String, value)
            End Set
        End Property
        Dim fAction_Promised As String
        <Size(17)>
        Public Property Action_Promised() As String
            Get
                Return fAction_Promised
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Action_Promised", fAction_Promised, value)
            End Set
        End Property
        Dim fActionType As Short
        Public Property ActionType() As Short
            Get
                Return fActionType
            End Get
            Set(ByVal value As Short)
                SetPropertyValue(Of Short)("ActionType", fActionType, value)
            End Set
        End Property
        Dim fAction_Date As DateTime
        Public Property Action_Date() As DateTime
            Get
                Return fAction_Date
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)("Action_Date", fAction_Date, value)
            End Set
        End Property
        Dim fAction_Assigned_To As String

        <Size(15)>
        Public Property Action_Assigned_To() As String
            Get
                Return fAction_Assigned_To
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Action_Assigned_To", fAction_Assigned_To, value)
            End Set
        End Property
        Dim fAction_Completed As Byte
        Public Property Action_Completed() As Byte
            Get
                Return fAction_Completed
            End Get
            Set(ByVal value As Byte)
                SetPropertyValue(Of Byte)("Action_Completed", fAction_Completed, value)
            End Set
        End Property
        Dim fACTCMDSP As Byte
        Public Property ACTCMDSP() As Byte
            Get
                Return fACTCMDSP
            End Get
            Set(ByVal value As Byte)
                SetPropertyValue(Of Byte)("ACTCMDSP", fACTCMDSP, value)
            End Set
        End Property
        Dim fAction_Completed_Date As DateTime
        Public Property Action_Completed_Date() As DateTime
            Get
                Return fAction_Completed_Date
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)("Action_Completed_Date", fAction_Completed_Date, value)
            End Set
        End Property
        Dim fAction_Completed_Time As DateTime
        Public Property Action_Completed_Time() As DateTime
            Get
                Return fAction_Completed_Time
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)("Action_Completed_Time", fAction_Completed_Time, value)
            End Set
        End Property
        Dim fAmount_Promised As Decimal
        Public Property Amount_Promised() As Decimal
            Get
                Return fAmount_Promised
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)("Amount_Promised", fAmount_Promised, value)
            End Set
        End Property
        Dim fAmount_Received As Decimal
        Public Property Amount_Received() As Decimal
            Get
                Return fAmount_Received
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)("Amount_Received", fAmount_Received, value)
            End Set
        End Property
        Dim fUSERID As String
        <Size(15)>
        Public Property USERID() As String
            Get
                Return fUSERID
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("USERID", fUSERID, value)
            End Set
        End Property
        Dim fNote_Display_String As String
        <Size(71)>
        Public Property Note_Display_String() As String
            Get
                Return fNote_Display_String
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Note_Display_String", fNote_Display_String, value)
            End Set
        End Property
        Dim fCNTCPRSN As String
        <Size(61)>
        Public Property CNTCPRSN() As String
            Get
                Return fCNTCPRSN
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("CNTCPRSN", fCNTCPRSN, value)
            End Set
        End Property
        Dim fADRSCODE As String
        <Size(15)>
        Public Property ADRSCODE() As String
            Get
                Return fADRSCODE
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("ADRSCODE", fADRSCODE, value)
            End Set
        End Property
        Dim fUSERDEF1 As String
        <Size(21)>
        Public Property USERDEF1() As String
            Get
                Return fUSERDEF1
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("USERDEF1", fUSERDEF1, value)
            End Set
        End Property
        Dim fUSERDEF2 As String
        <Size(21)>
        Public Property USERDEF2() As String
            Get
                Return fUSERDEF2
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("USERDEF2", fUSERDEF2, value)
            End Set
        End Property
        Dim fUSRDAT01 As DateTime
        Public Property USRDAT01() As DateTime
            Get
                Return fUSRDAT01
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)("USRDAT01", fUSRDAT01, value)
            End Set
        End Property
        Dim fPRIORT As Short
        Public Property PRIORT() As Short
            Get
                Return fPRIORT
            End Get
            Set(ByVal value As Short)
                SetPropertyValue(Of Short)("PRIORT", fPRIORT, value)
            End Set
        End Property
        Dim fNOTECAT As String
        <Size(15)>
        Public Property NOTECAT() As String
            Get
                Return fNOTECAT
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("NOTECAT", fNOTECAT, value)
            End Set
        End Property
        Dim fDEX_ROW_ID As Integer
        Public Property DEX_ROW_ID() As Integer
            Get
                Return fDEX_ROW_ID
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)("DEX_ROW_ID", fDEX_ROW_ID, value)
            End Set
        End Property
    End Class

End Namespace
