'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Xpo.Metadata
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Runtime.CompilerServices
Imports System.Reflection
Namespace Objects.EX

    <Persistent("EX010130")>
    Partial Public Class EXEmployeeExtraFields
        Inherits XPLiteObject
        Dim fEMPID_I As String
        <Key()>
        <Size(15)>
        Public Property EMPID_I() As String
            Get
                Return fEMPID_I
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(EMPID_I), fEMPID_I, value)
            End Set
        End Property
        Dim fDATE1_I As DateTime
        Public Property DATE1_I() As DateTime
            Get
                Return fDATE1_I
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)(NameOf(DATE1_I), fDATE1_I, value)
            End Set
        End Property
        Dim fDATE2_I As DateTime
        Public Property DATE2_I() As DateTime
            Get
                Return fDATE2_I
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)(NameOf(DATE2_I), fDATE2_I, value)
            End Set
        End Property
        Dim fDATE3_I As DateTime
        Public Property DATE3_I() As DateTime
            Get
                Return fDATE3_I
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)(NameOf(DATE3_I), fDATE3_I, value)
            End Set
        End Property
        Dim fDATE4_I As DateTime
        Public Property DATE4_I() As DateTime
            Get
                Return fDATE4_I
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)(NameOf(DATE4_I), fDATE4_I, value)
            End Set
        End Property
        Dim fDATE5_I As DateTime
        Public Property DATE5_I() As DateTime
            Get
                Return fDATE5_I
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)(NameOf(DATE5_I), fDATE5_I, value)
            End Set
        End Property
        Dim fSTRINGS_I_1 As String
        <Size(31)>
        Public Property STRINGS_I_1() As String
            Get
                Return fSTRINGS_I_1
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(STRINGS_I_1), fSTRINGS_I_1, value)
            End Set
        End Property
        Dim fSTRINGS_I_2 As String
        <Size(31)>
        Public Property STRINGS_I_2() As String
            Get
                Return fSTRINGS_I_2
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(STRINGS_I_2), fSTRINGS_I_2, value)
            End Set
        End Property
        Dim fSTRINGS_I_3 As String
        <Size(31)>
        Public Property STRINGS_I_3() As String
            Get
                Return fSTRINGS_I_3
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(STRINGS_I_3), fSTRINGS_I_3, value)
            End Set
        End Property
        Dim fSTRINGS_I_4 As String
        <Size(31)>
        Public Property STRINGS_I_4() As String
            Get
                Return fSTRINGS_I_4
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(STRINGS_I_4), fSTRINGS_I_4, value)
            End Set
        End Property
        Dim fSTRINGS_I_5 As String
        <Size(31)>
        Public Property STRINGS_I_5() As String
            Get
                Return fSTRINGS_I_5
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(STRINGS_I_5), fSTRINGS_I_5, value)
            End Set
        End Property
        Dim fNUMERICEXTRA_1 As Integer
        Public Property NUMERICEXTRA_1() As Integer
            Get
                Return fNUMERICEXTRA_1
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)(NameOf(NUMERICEXTRA_1), fNUMERICEXTRA_1, value)
            End Set
        End Property
        Dim fNUMERICEXTRA_2 As Integer
        Public Property NUMERICEXTRA_2() As Integer
            Get
                Return fNUMERICEXTRA_2
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)(NameOf(NUMERICEXTRA_2), fNUMERICEXTRA_2, value)
            End Set
        End Property
        Dim fNUMERICEXTRA_3 As Integer
        Public Property NUMERICEXTRA_3() As Integer
            Get
                Return fNUMERICEXTRA_3
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)(NameOf(NUMERICEXTRA_3), fNUMERICEXTRA_3, value)
            End Set
        End Property
        Dim fNUMERICEXTRA_4 As Integer
        Public Property NUMERICEXTRA_4() As Integer
            Get
                Return fNUMERICEXTRA_4
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)(NameOf(NUMERICEXTRA_4), fNUMERICEXTRA_4, value)
            End Set
        End Property
        Dim fNUMERICEXTRA_5 As Integer
        Public Property NUMERICEXTRA_5() As Integer
            Get
                Return fNUMERICEXTRA_5
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)(NameOf(NUMERICEXTRA_5), fNUMERICEXTRA_5, value)
            End Set
        End Property
        Dim fDOLLARS_I_1 As Decimal
        Public Property DOLLARS_I_1() As Decimal
            Get
                Return fDOLLARS_I_1
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)(NameOf(DOLLARS_I_1), fDOLLARS_I_1, value)
            End Set
        End Property
        Dim fDOLLARS_I_2 As Decimal
        Public Property DOLLARS_I_2() As Decimal
            Get
                Return fDOLLARS_I_2
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)(NameOf(DOLLARS_I_2), fDOLLARS_I_2, value)
            End Set
        End Property
        Dim fDOLLARS_I_3 As Decimal
        Public Property DOLLARS_I_3() As Decimal
            Get
                Return fDOLLARS_I_3
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)(NameOf(DOLLARS_I_3), fDOLLARS_I_3, value)
            End Set
        End Property
        Dim fDOLLARS_I_4 As Decimal
        Public Property DOLLARS_I_4() As Decimal
            Get
                Return fDOLLARS_I_4
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)(NameOf(DOLLARS_I_4), fDOLLARS_I_4, value)
            End Set
        End Property
        Dim fDOLLARS_I_5 As Decimal
        Public Property DOLLARS_I_5() As Decimal
            Get
                Return fDOLLARS_I_5
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)(NameOf(DOLLARS_I_5), fDOLLARS_I_5, value)
            End Set
        End Property
        Dim fCHECKBOXES_I_1 As Byte
        Public Property CHECKBOXES_I_1() As Byte
            Get
                Return fCHECKBOXES_I_1
            End Get
            Set(ByVal value As Byte)
                SetPropertyValue(Of Byte)(NameOf(CHECKBOXES_I_1), fCHECKBOXES_I_1, value)
            End Set
        End Property
        Dim fCHECKBOXES_I_2 As Byte
        Public Property CHECKBOXES_I_2() As Byte
            Get
                Return fCHECKBOXES_I_2
            End Get
            Set(ByVal value As Byte)
                SetPropertyValue(Of Byte)(NameOf(CHECKBOXES_I_2), fCHECKBOXES_I_2, value)
            End Set
        End Property
        Dim fCHECKBOXES_I_3 As Byte
        Public Property CHECKBOXES_I_3() As Byte
            Get
                Return fCHECKBOXES_I_3
            End Get
            Set(ByVal value As Byte)
                SetPropertyValue(Of Byte)(NameOf(CHECKBOXES_I_3), fCHECKBOXES_I_3, value)
            End Set
        End Property
        Dim fCHECKBOXES_I_4 As Byte
        Public Property CHECKBOXES_I_4() As Byte
            Get
                Return fCHECKBOXES_I_4
            End Get
            Set(ByVal value As Byte)
                SetPropertyValue(Of Byte)(NameOf(CHECKBOXES_I_4), fCHECKBOXES_I_4, value)
            End Set
        End Property
        Dim fCHECKBOXES_I_5 As Byte
        Public Property CHECKBOXES_I_5() As Byte
            Get
                Return fCHECKBOXES_I_5
            End Get
            Set(ByVal value As Byte)
                SetPropertyValue(Of Byte)(NameOf(CHECKBOXES_I_5), fCHECKBOXES_I_5, value)
            End Set
        End Property
        Dim fNOTESINDEX_I As Decimal
        Public Property NOTESINDEX_I() As Decimal
            Get
                Return fNOTESINDEX_I
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)(NameOf(NOTESINDEX_I), fNOTESINDEX_I, value)
            End Set
        End Property
        Dim fCHANGEBY_I As String
        <Size(15)>
        Public Property CHANGEBY_I() As String
            Get
                Return fCHANGEBY_I
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(CHANGEBY_I), fCHANGEBY_I, value)
            End Set
        End Property
        Dim fCHANGEDATE_I As DateTime
        Public Property CHANGEDATE_I() As DateTime
            Get
                Return fCHANGEDATE_I
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)(NameOf(CHANGEDATE_I), fCHANGEDATE_I, value)
            End Set
        End Property



    End Class

End Namespace
