'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Namespace Objects.GL


    ''' <summary>
    ''' GP Table GL00201
    ''' </summary>
    ''' <remarks></remarks>
    <Persistent("GL00200")>
    <MasterProvider.Module.AllowDataModificationsInMasterProvider()>
    Partial Public Class GLBudgetHeader
        Inherits XPLiteObject
        Dim fBUDGETID As String
        <Key()> _
        <Size(15)> _
        Public Property BUDGETID() As String
            Get
                Return fBUDGETID
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("BUDGETID", fBUDGETID, value)
            End Set
        End Property
        Dim fBUDCOMNT As String
        <Size(31)> _
        Public Property BUDCOMNT() As String
            Get
                Return fBUDCOMNT
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("BUDCOMNT", fBUDCOMNT, value)
            End Set
        End Property
        Dim fYEAR1 As Short
        Public Property YEAR1() As Short
            Get
                Return fYEAR1
            End Get
            Set(ByVal value As Short)
                SetPropertyValue(Of Short)("YEAR1", fYEAR1, value)
            End Set
        End Property
        Dim fBased_On As Short
        Public Property Based_On() As Short
            Get
                Return fBased_On
            End Get
            Set(ByVal value As Short)
                SetPropertyValue(Of Short)("Based_On", fBased_On, value)
            End Set
        End Property
        Dim fFrom_Date As DateTime
        Public Property From_Date() As DateTime
            Get
                Return fFrom_Date
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)("From_Date", fFrom_Date, value)
            End Set
        End Property
        Dim fTODATE As DateTime
        Public Property TODATE() As DateTime
            Get
                Return fTODATE
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)("TODATE", fTODATE, value)
            End Set
        End Property
        Dim fNOTEINDX As Decimal
        Public Property NOTEINDX() As Decimal
            Get
                Return fNOTEINDX
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)("NOTEINDX", fNOTEINDX, value)
            End Set
        End Property

        Public Sub New(ByVal session As Session)
            MyBase.New(session)
        End Sub
    End Class

End Namespace
