'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Namespace Objects.GL
    ''' <summary>
    ''' GP Table GL00201
    ''' </summary>
    ''' <remarks></remarks>
    <Persistent("GL00201")>
    <MasterProvider.Module.AllowDataModificationsInMasterProvider()>
    Partial Public Class GLBudgetDetail
        Inherits XPLiteObject
        
        Dim fBUDGETAMT As Decimal
        Public Property BUDGETAMT() As Decimal
            Get
                Return fBUDGETAMT
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)("BUDGETAMT", fBUDGETAMT, value)
            End Set
        End Property
        Dim fACCATNUM As Short
        Public Property ACCATNUM() As Short
            Get
                Return fACCATNUM
            End Get
            Set(ByVal value As Short)
                SetPropertyValue(Of Short)("ACCATNUM", fACCATNUM, value)
            End Set
        End Property
        Dim fYEAR1 As Short
        Public Property YEAR1() As Short
            Get
                Return fYEAR1
            End Get
            Set(ByVal value As Short)
                SetPropertyValue(Of Short)("YEAR1", fYEAR1, value)
            End Set
        End Property

        Public Structure CompoundKey1Struct
            <Size(15)> _
            <Persistent("BUDGETID")> _
            Public Property BUDGETID As String
            <Persistent("PERIODDT")> _
            Public Property PERIODDT As DateTime
            <Persistent("PERIODID")> _
            Public Property PERIODID As Short
            <Persistent("ACTINDX")> _
            Public Property ACTINDX As Integer
        End Structure
        <Key(), Persistent()> _
        Public CompoundKey1 As CompoundKey1Struct
        Public Sub New(ByVal session As Session)
            MyBase.New(session)
        End Sub
    End Class

End Namespace
