'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Namespace Objects.GL

    Partial Public Class GLHistoricalYearAccountSummary
        Inherits XPLiteObject
        Dim fACTNUMBR_1 As String
        <Size(9)>
        Public Property ACTNUMBR_1() As String
            Get
                Return fACTNUMBR_1
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("ACTNUMBR_1", fACTNUMBR_1, value)
            End Set
        End Property
        Dim fACTNUMBR_2 As String
        <Size(9)>
        Public Property ACTNUMBR_2() As String
            Get
                Return fACTNUMBR_2
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("ACTNUMBR_2", fACTNUMBR_2, value)
            End Set
        End Property
        Dim fACTNUMBR_3 As String
        <Size(9)>
        Public Property ACTNUMBR_3() As String
            Get
                Return fACTNUMBR_3
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("ACTNUMBR_3", fACTNUMBR_3, value)
            End Set
        End Property
        Dim fACTNUMBR_4 As String
        <Size(9)>
        Public Property ACTNUMBR_4() As String
            Get
                Return fACTNUMBR_4
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("ACTNUMBR_4", fACTNUMBR_4, value)
            End Set
        End Property
        Dim fACTNUMBR_5 As String
        <Size(9)>
        Public Property ACTNUMBR_5() As String
            Get
                Return fACTNUMBR_5
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("ACTNUMBR_5", fACTNUMBR_5, value)
            End Set
        End Property
        Dim fACCATNUM As Short
        Public Property ACCATNUM() As Short
            Get
                Return fACCATNUM
            End Get
            Set(ByVal value As Short)
                SetPropertyValue(Of Short)("ACCATNUM", fACCATNUM, value)
            End Set
        End Property
        Dim fPERDBLNC As Decimal
        Public Property PERDBLNC() As Decimal
            Get
                Return fPERDBLNC
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)("PERDBLNC", fPERDBLNC, value)
            End Set
        End Property
        Dim fDEBITAMT As Decimal
        Public Property DEBITAMT() As Decimal
            Get
                Return fDEBITAMT
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)("DEBITAMT", fDEBITAMT, value)
            End Set
        End Property
        Dim fCRDTAMNT As Decimal
        Public Property CRDTAMNT() As Decimal
            Get
                Return fCRDTAMNT
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)("CRDTAMNT", fCRDTAMNT, value)
            End Set
        End Property
        Dim fDEX_ROW_ID As Integer
        Public Property DEX_ROW_ID() As Integer
            Get
                Return fDEX_ROW_ID
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)("DEX_ROW_ID", fDEX_ROW_ID, value)
            End Set
        End Property
        Public Structure CompoundKey1Struct
            <Persistent("ACTINDX")>
            Public Property ACTINDX As Integer
            <Persistent("YEAR1")>
            Public Property YEAR1 As Short
            <Persistent("PERIODID")>
            Public Property PERIODID As Short
            <Persistent("Ledger_ID")>
            Public Property Ledger_ID As Short
        End Structure
        <Indexed(Name:="AK3GL10111", Unique:=True)>
        <Key(), Persistent()>
        Public Oid As CompoundKey1Struct
    End Class

End Namespace
