'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Xpo.Metadata
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Runtime.CompilerServices
Imports System.Reflection
Namespace Objects.DD

    <Persistent("DD00100")>
    Partial Public Class DDEmployeeDirectDepositHeader
        Inherits XPLiteObject
        Dim fEMPLOYID As String
        <Key()>
        <Size(15)>
        Public Property EMPLOYID() As String
            Get
                Return fEMPLOYID
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(EMPLOYID), fEMPLOYID, value)
            End Set
        End Property
        Dim fINACTIVE As Byte
        Public Property INACTIVE() As Byte
            Get
                Return fINACTIVE
            End Get
            Set(ByVal value As Byte)
                SetPropertyValue(Of Byte)(NameOf(INACTIVE), fINACTIVE, value)
            End Set
        End Property
        Dim fDDREMAIN As Integer
        Public Property DDREMAIN() As Integer
            Get
                Return fDDREMAIN
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)(NameOf(DDREMAIN), fDDREMAIN, value)
            End Set
        End Property
        Dim fINDXLONG As Integer
        Public Property INDXLONG() As Integer
            Get
                Return fINDXLONG
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)(NameOf(INDXLONG), fINDXLONG, value)
            End Set
        End Property

    End Class

End Namespace
