'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Xpo.Metadata
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Runtime.CompilerServices
Imports System.Reflection
Namespace Objects.PC

    <Persistent("PC40301")>
    Partial Public Class PCPositionClassSetup
        Inherits XPLiteObject
        Dim fDSCRIPTN As String
        <Size(31)>
        Public Property DSCRIPTN() As String
            Get
                Return fDSCRIPTN
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(DSCRIPTN), fDSCRIPTN, value)
            End Set
        End Property
        Dim fACTINDX As Integer
        Public Property ACTINDX() As Integer
            Get
                Return fACTINDX
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)(NameOf(ACTINDX), fACTINDX, value)
            End Set
        End Property
        Dim fATACRSTM As Byte
        Public Property ATACRSTM() As Byte
            Get
                Return fATACRSTM
            End Get
            Set(ByVal value As Byte)
                SetPropertyValue(Of Byte)(NameOf(ATACRSTM), fATACRSTM, value)
            End Set
        End Property
        Dim fATACRVAC As Byte
        Public Property ATACRVAC() As Byte
            Get
                Return fATACRVAC
            End Get
            Set(ByVal value As Byte)
                SetPropertyValue(Of Byte)(NameOf(ATACRVAC), fATACRVAC, value)
            End Set
        End Property
        Dim fBUDGETPERMSEATAMT As Short
        Public Property BUDGETPERMSEATAMT() As Short
            Get
                Return fBUDGETPERMSEATAMT
            End Get
            Set(ByVal value As Short)
                SetPropertyValue(Of Short)(NameOf(BUDGETPERMSEATAMT), fBUDGETPERMSEATAMT, value)
            End Set
        End Property
        Dim fBUDGETTEMPSEATAMT As Short
        Public Property BUDGETTEMPSEATAMT() As Short
            Get
                Return fBUDGETTEMPSEATAMT
            End Get
            Set(ByVal value As Short)
                SetPropertyValue(Of Short)(NameOf(BUDGETTEMPSEATAMT), fBUDGETTEMPSEATAMT, value)
            End Set
        End Property
        Dim fBUGETBENPERCENT As Decimal
        Public Property BUGETBENPERCENT() As Decimal
            Get
                Return fBUGETBENPERCENT
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)(NameOf(BUGETBENPERCENT), fBUGETBENPERCENT, value)
            End Set
        End Property
        Dim fBUDGETTAXPERCENT As Decimal
        Public Property BUDGETTAXPERCENT() As Decimal
            Get
                Return fBUDGETTAXPERCENT
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)(NameOf(BUDGETTAXPERCENT), fBUDGETTAXPERCENT, value)
            End Set
        End Property
        Dim fBUDGETBENAMOUNT As Decimal
        Public Property BUDGETBENAMOUNT() As Decimal
            Get
                Return fBUDGETBENAMOUNT
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)(NameOf(BUDGETBENAMOUNT), fBUDGETBENAMOUNT, value)
            End Set
        End Property
        Dim fBUDGETTAXAMOUNT As Decimal
        Public Property BUDGETTAXAMOUNT() As Decimal
            Get
                Return fBUDGETTAXAMOUNT
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)(NameOf(BUDGETTAXAMOUNT), fBUDGETTAXAMOUNT, value)
            End Set
        End Property
        Dim fCalc_Min_Wage_Bal As Byte
        Public Property Calc_Min_Wage_Bal() As Byte
            Get
                Return fCalc_Min_Wage_Bal
            End Get
            Set(ByVal value As Byte)
                SetPropertyValue(Of Byte)(NameOf(Calc_Min_Wage_Bal), fCalc_Min_Wage_Bal, value)
            End Set
        End Property
        Dim fWCACFPAY As Short
        Public Property WCACFPAY() As Short
            Get
                Return fWCACFPAY
            End Get
            Set(ByVal value As Short)
                SetPropertyValue(Of Short)(NameOf(WCACFPAY), fWCACFPAY, value)
            End Set
        End Property
        Dim fCHANGEBY_I As String
        <Size(15)>
        Public Property CHANGEBY_I() As String
            Get
                Return fCHANGEBY_I
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(CHANGEBY_I), fCHANGEBY_I, value)
            End Set
        End Property
        Dim fCHANGEDATE_I As DateTime
        Public Property CHANGEDATE_I() As DateTime
            Get
                Return fCHANGEDATE_I
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)(NameOf(CHANGEDATE_I), fCHANGEDATE_I, value)
            End Set
        End Property
        Dim fCONTENDDTE As DateTime
        Public Property CONTENDDTE() As DateTime
            Get
                Return fCONTENDDTE
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)(NameOf(CONTENDDTE), fCONTENDDTE, value)
            End Set
        End Property
        Dim fCONTSTARTDTE As DateTime
        Public Property CONTSTARTDTE() As DateTime
            Get
                Return fCONTSTARTDTE
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)(NameOf(CONTSTARTDTE), fCONTSTARTDTE, value)
            End Set
        End Property
        Dim fCREATDDT As DateTime
        Public Property CREATDDT() As DateTime
            Get
                Return fCREATDDT
            End Get
            Set(ByVal value As DateTime)
                SetPropertyValue(Of DateTime)(NameOf(CREATDDT), fCREATDDT, value)
            End Set
        End Property
        Dim fCRUSRID As String
        <Size(15)>
        Public Property CRUSRID() As String
            Get
                Return fCRUSRID
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(CRUSRID), fCRUSRID, value)
            End Set
        End Property
        Dim fDEPRTMNT As String
        <Size(7)>
        Public Property DEPRTMNT() As String
            Get
                Return fDEPRTMNT
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(DEPRTMNT), fDEPRTMNT, value)
            End Set
        End Property
        Dim fDIVISIONCODE_I As String
        <Size(7)>
        Public Property DIVISIONCODE_I() As String
            Get
                Return fDIVISIONCODE_I
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(DIVISIONCODE_I), fDIVISIONCODE_I, value)
            End Set
        End Property
        Dim fEEOCLASS_I As Short
        Public Property EEOCLASS_I() As Short
            Get
                Return fEEOCLASS_I
            End Get
            Set(ByVal value As Short)
                SetPropertyValue(Of Short)(NameOf(EEOCLASS_I), fEEOCLASS_I, value)
            End Set
        End Property
        Dim fEMPLCLAS As String
        <Size(15)>
        Public Property EMPLCLAS() As String
            Get
                Return fEMPLCLAS
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(EMPLCLAS), fEMPLCLAS, value)
            End Set
        End Property
        Dim fFLSASTATUS As Short
        Public Property FLSASTATUS() As Short
            Get
                Return fFLSASTATUS
            End Get
            Set(ByVal value As Short)
                SetPropertyValue(Of Short)(NameOf(FLSASTATUS), fFLSASTATUS, value)
            End Set
        End Property
        Dim fBUDGETEDFTE As Decimal
        Public Property BUDGETEDFTE() As Decimal
            Get
                Return fBUDGETEDFTE
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)(NameOf(BUDGETEDFTE), fBUDGETEDFTE, value)
            End Set
        End Property
        Dim fINHERITANCELOCK As Byte
        Public Property INHERITANCELOCK() As Byte
            Get
                Return fINHERITANCELOCK
            End Get
            Set(ByVal value As Byte)
                SetPropertyValue(Of Byte)(NameOf(INHERITANCELOCK), fINHERITANCELOCK, value)
            End Set
        End Property
        Dim fLOCATNID As String
        <Size(15)>
        Public Property LOCATNID() As String
            Get
                Return fLOCATNID
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(LOCATNID), fLOCATNID, value)
            End Set
        End Property
        Dim fNOTEINDX As Decimal
        Public Property NOTEINDX() As Decimal
            Get
                Return fNOTEINDX
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)(NameOf(NOTEINDX), fNOTEINDX, value)
            End Set
        End Property
        Dim fNOTEINDX2 As Decimal
        Public Property NOTEINDX2() As Decimal
            Get
                Return fNOTEINDX2
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)(NameOf(NOTEINDX2), fNOTEINDX2, value)
            End Set
        End Property
        Dim fGROSSPAYINDEX As Integer
        Public Property GROSSPAYINDEX() As Integer
            Get
                Return fGROSSPAYINDEX
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)(NameOf(GROSSPAYINDEX), fGROSSPAYINDEX, value)
            End Set
        End Property
        Dim fBENEFITEXPINDEX As Integer
        Public Property BENEFITEXPINDEX() As Integer
            Get
                Return fBENEFITEXPINDEX
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)(NameOf(BENEFITEXPINDEX), fBENEFITEXPINDEX, value)
            End Set
        End Property
        Dim fWCOMPTAXEXPINDEX As Integer
        Public Property WCOMPTAXEXPINDEX() As Integer
            Get
                Return fWCOMPTAXEXPINDEX
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)(NameOf(WCOMPTAXEXPINDEX), fWCOMPTAXEXPINDEX, value)
            End Set
        End Property
        Dim fTAXBENEXPENSEINDEX As Integer
        Public Property TAXBENEXPENSEINDEX() As Integer
            Get
                Return fTAXBENEXPENSEINDEX
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)(NameOf(TAXBENEXPENSEINDEX), fTAXBENEXPENSEINDEX, value)
            End Set
        End Property
        Dim fEMPLYRFICAMEINDEX As Integer
        Public Property EMPLYRFICAMEINDEX() As Integer
            Get
                Return fEMPLYRFICAMEINDEX
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)(NameOf(EMPLYRFICAMEINDEX), fEMPLYRFICAMEINDEX, value)
            End Set
        End Property
        Dim fEMPLYRFICASEINDEX As Integer
        Public Property EMPLYRFICASEINDEX() As Integer
            Get
                Return fEMPLYRFICASEINDEX
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)(NameOf(EMPLYRFICASEINDEX), fEMPLYRFICASEINDEX, value)
            End Set
        End Property
        Dim fEMPLYRFUTAINDEX As Integer
        Public Property EMPLYRFUTAINDEX() As Integer
            Get
                Return fEMPLYRFUTAINDEX
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)(NameOf(EMPLYRFUTAINDEX), fEMPLYRFUTAINDEX, value)
            End Set
        End Property
        Dim fEMPLYRSUTAINDEX As Integer
        Public Property EMPLYRSUTAINDEX() As Integer
            Get
                Return fEMPLYRSUTAINDEX
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)(NameOf(EMPLYRSUTAINDEX), fEMPLYRSUTAINDEX, value)
            End Set
        End Property
        Dim fPOSSTATUS As Short
        Public Property POSSTATUS() As Short
            Get
                Return fPOSSTATUS
            End Get
            Set(ByVal value As Short)
                SetPropertyValue(Of Short)(NameOf(POSSTATUS), fPOSSTATUS, value)
            End Set
        End Property
        Dim fREPORTSTOPOS As String
        <Size(7)>
        Public Property REPORTSTOPOS() As String
            Get
                Return fREPORTSTOPOS
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(REPORTSTOPOS), fREPORTSTOPOS, value)
            End Set
        End Property
        Dim fREVIEWSETUPCODE_I As String
        <Size(31)>
        Public Property REVIEWSETUPCODE_I() As String
            Get
                Return fREVIEWSETUPCODE_I
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(REVIEWSETUPCODE_I), fREVIEWSETUPCODE_I, value)
            End Set
        End Property
        Dim fSTMACMTH As Short
        Public Property STMACMTH() As Short
            Get
                Return fSTMACMTH
            End Get
            Set(ByVal value As Short)
                SetPropertyValue(Of Short)(NameOf(STMACMTH), fSTMACMTH, value)
            End Set
        End Property
        Dim fSKTMACAM As Integer
        Public Property SKTMACAM() As Integer
            Get
                Return fSKTMACAM
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)(NameOf(SKTMACAM), fSKTMACAM, value)
            End Set
        End Property
        Dim fSKTMHPYR As Integer
        Public Property SKTMHPYR() As Integer
            Get
                Return fSKTMHPYR
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)(NameOf(SKTMHPYR), fSKTMHPYR, value)
            End Set
        End Property
        Dim fSKILLSETNUMBER_I As Integer
        Public Property SKILLSETNUMBER_I() As Integer
            Get
                Return fSKILLSETNUMBER_I
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)(NameOf(SKILLSETNUMBER_I), fSKILLSETNUMBER_I, value)
            End Set
        End Property
        Dim fSUPERVISORCODE_I As String
        <Size(7)>
        Public Property SUPERVISORCODE_I() As String
            Get
                Return fSUPERVISORCODE_I
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(SUPERVISORCODE_I), fSUPERVISORCODE_I, value)
            End Set
        End Property
        Dim fEMPLOYMENTTYPE As Short
        Public Property EMPLOYMENTTYPE() As Short
            Get
                Return fEMPLOYMENTTYPE
            End Get
            Set(ByVal value As Short)
                SetPropertyValue(Of Short)(NameOf(EMPLOYMENTTYPE), fEMPLOYMENTTYPE, value)
            End Set
        End Property
        Dim fUNIONDUESAMOUNT_I As Decimal
        Public Property UNIONDUESAMOUNT_I() As Decimal
            Get
                Return fUNIONDUESAMOUNT_I
            End Get
            Set(ByVal value As Decimal)
                SetPropertyValue(Of Decimal)(NameOf(UNIONDUESAMOUNT_I), fUNIONDUESAMOUNT_I, value)
            End Set
        End Property
        Dim fUNIONNAME_I As String
        <Size(31)>
        Public Property UNIONNAME_I() As String
            Get
                Return fUNIONNAME_I
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(UNIONNAME_I), fUNIONNAME_I, value)
            End Set
        End Property
        Dim fVACCRMTH As Short
        Public Property VACCRMTH() As Short
            Get
                Return fVACCRMTH
            End Get
            Set(ByVal value As Short)
                SetPropertyValue(Of Short)(NameOf(VACCRMTH), fVACCRMTH, value)
            End Set
        End Property
        Dim fVACCRAMT As Integer
        Public Property VACCRAMT() As Integer
            Get
                Return fVACCRAMT
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)(NameOf(VACCRAMT), fVACCRAMT, value)
            End Set
        End Property
        Dim fVACAPRYR As Integer
        Public Property VACAPRYR() As Integer
            Get
                Return fVACAPRYR
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)(NameOf(VACAPRYR), fVACAPRYR, value)
            End Set
        End Property
        Dim fWRNSTFLSBLWZR As Byte
        Public Property WRNSTFLSBLWZR() As Byte
            Get
                Return fWRNSTFLSBLWZR
            End Get
            Set(ByVal value As Byte)
                SetPropertyValue(Of Byte)(NameOf(WRNSTFLSBLWZR), fWRNSTFLSBLWZR, value)
            End Set
        End Property
        Dim fWRNVCNFLSBLWZR As Byte
        Public Property WRNVCNFLSBLWZR() As Byte
            Get
                Return fWRNVCNFLSBLWZR
            End Get
            Set(ByVal value As Byte)
                SetPropertyValue(Of Byte)(NameOf(WRNVCNFLSBLWZR), fWRNVCNFLSBLWZR, value)
            End Set
        End Property
        Dim fWRKRCOMP As String
        <Size(7)>
        Public Property WRKRCOMP() As String
            Get
                Return fWRKRCOMP
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(WRKRCOMP), fWRKRCOMP, value)
            End Set
        End Property
        Dim fCONTACTNUM_I As String
        <Size(31)>
        Public Property CONTACTNUM_I() As String
            Get
                Return fCONTACTNUM_I
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(CONTACTNUM_I), fCONTACTNUM_I, value)
            End Set
        End Property

        Dim fTXTFIELD As String
        <Size(SizeAttribute.Unlimited)>
        Public Property TXTFIELD() As String
            Get
                Return fTXTFIELD
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)(NameOf(TXTFIELD), fTXTFIELD, value)
            End Set
        End Property
        Public Structure CompoundKey1Struct
            <Size(15)>
            <Persistent("PLANCODE")>
            Public Property PLANCODE As String
            <Size(7)>
            <Persistent("JOBTITLE")>
            Public Property JOBTITLE As String
        End Structure
        <Key(), Persistent()>
        Public CompoundKey1 As CompoundKey1Struct
        Public Sub New(ByVal session As Session)
            MyBase.New(session)
        End Sub
    End Class

End Namespace
