'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
Namespace Objects.MOP

	Partial Public Class IS010001
		Inherits XPLiteObject
		Dim fMANUFACTUREORDER_I As String
		<Size(31)> _
		Public Property MANUFACTUREORDER_I() As String
			Get
				Return fMANUFACTUREORDER_I
			End Get
			Set(ByVal value As String)
				SetPropertyValue(Of String)("MANUFACTUREORDER_I", fMANUFACTUREORDER_I, value)
			End Set
		End Property
		Dim fSOITEMDUEDATE_I As DateTime
		Public Property SOITEMDUEDATE_I() As DateTime
			Get
				Return fSOITEMDUEDATE_I
			End Get
			Set(ByVal value As DateTime)
				SetPropertyValue(Of DateTime)("SOITEMDUEDATE_I", fSOITEMDUEDATE_I, value)
			End Set
		End Property
		Dim fSOITEMPROMISEDATE_I As DateTime
		Public Property SOITEMPROMISEDATE_I() As DateTime
			Get
				Return fSOITEMPROMISEDATE_I
			End Get
			Set(ByVal value As DateTime)
				SetPropertyValue(Of DateTime)("SOITEMPROMISEDATE_I", fSOITEMPROMISEDATE_I, value)
			End Set
		End Property
		Dim fCUSTOMERPARTNUMBER_I As String
		<Size(31)> _
		Public Property CUSTOMERPARTNUMBER_I() As String
			Get
				Return fCUSTOMERPARTNUMBER_I
			End Get
			Set(ByVal value As String)
				SetPropertyValue(Of String)("CUSTOMERPARTNUMBER_I", fCUSTOMERPARTNUMBER_I, value)
			End Set
		End Property
		Dim fSOCHANGEDATE_I As DateTime
		Public Property SOCHANGEDATE_I() As DateTime
			Get
				Return fSOCHANGEDATE_I
			End Get
			Set(ByVal value As DateTime)
				SetPropertyValue(Of DateTime)("SOCHANGEDATE_I", fSOCHANGEDATE_I, value)
			End Set
		End Property
		Dim fITEMNMBR As String
		<Size(31)> _
		Public Property ITEMNMBR() As String
			Get
				Return fITEMNMBR
			End Get
			Set(ByVal value As String)
				SetPropertyValue(Of String)("ITEMNMBR", fITEMNMBR, value)
			End Set
		End Property
		Dim fREVISIONLEVEL_I As String
		<Size(51)> _
		Public Property REVISIONLEVEL_I() As String
			Get
				Return fREVISIONLEVEL_I
			End Get
			Set(ByVal value As String)
				SetPropertyValue(Of String)("REVISIONLEVEL_I", fREVISIONLEVEL_I, value)
			End Set
		End Property
		Dim fMFGNOTEINDEX_I As Decimal
		Public Property MFGNOTEINDEX_I() As Decimal
			Get
				Return fMFGNOTEINDEX_I
			End Get
			Set(ByVal value As Decimal)
				SetPropertyValue(Of Decimal)("MFGNOTEINDEX_I", fMFGNOTEINDEX_I, value)
			End Set
		End Property
		Dim fMRKDNAMT As Decimal
		Public Property MRKDNAMT() As Decimal
			Get
				Return fMRKDNAMT
			End Get
			Set(ByVal value As Decimal)
				SetPropertyValue(Of Decimal)("MRKDNAMT", fMRKDNAMT, value)
			End Set
		End Property
		Dim fMarkdown_Amount_Addition As Decimal
		Public Property Markdown_Amount_Addition() As Decimal
			Get
				Return fMarkdown_Amount_Addition
			End Get
			Set(ByVal value As Decimal)
				SetPropertyValue(Of Decimal)("Markdown_Amount_Addition", fMarkdown_Amount_Addition, value)
			End Set
		End Property
		Dim fCHANGEDATE_I As DateTime
		Public Property CHANGEDATE_I() As DateTime
			Get
				Return fCHANGEDATE_I
			End Get
			Set(ByVal value As DateTime)
				SetPropertyValue(Of DateTime)("CHANGEDATE_I", fCHANGEDATE_I, value)
			End Set
		End Property
		Dim fUSERID As String
		<Size(15)> _
		Public Property USERID() As String
			Get
				Return fUSERID
			End Get
			Set(ByVal value As String)
				SetPropertyValue(Of String)("USERID", fUSERID, value)
			End Set
		End Property
		Dim fQTYProcess As Decimal
		Public Property QTYProcess() As Decimal
			Get
				Return fQTYProcess
			End Get
			Set(ByVal value As Decimal)
				SetPropertyValue(Of Decimal)("QTYProcess", fQTYProcess, value)
			End Set
		End Property
		Dim fQTYMATCH As Decimal
		Public Property QTYMATCH() As Decimal
			Get
				Return fQTYMATCH
			End Get
			Set(ByVal value As Decimal)
				SetPropertyValue(Of Decimal)("QTYMATCH", fQTYMATCH, value)
			End Set
		End Property
		Dim fDEX_ROW_ID As Integer
		Public Property DEX_ROW_ID() As Integer
			Get
				Return fDEX_ROW_ID
			End Get
			Set(ByVal value As Integer)
				SetPropertyValue(Of Integer)("DEX_ROW_ID", fDEX_ROW_ID, value)
			End Set
		End Property
		Public Structure CompoundKey1Struct
			<Size(21)> _
			<Persistent("SOPNUMBE")> _
			Public Property SOPNUMBE As String
			<Persistent("SOPTYPE")> _
			Public Property SOPTYPE As Short
			<Persistent("LNITMSEQ")> _
			Public Property LNITMSEQ As Integer
			<Persistent("CMPNTSEQ")> _
			Public Property CMPNTSEQ As Integer
		End Structure
		<Key(), Persistent()> _
		Public CompoundKey1 As CompoundKey1Struct
	End Class

End Namespace
